### ISSUE TITLE
BDK Sim inaccessible 

### ISSUE THREAD

**Issue by BloodyGH** [wowsims/cata#1072]
**Describe the bug**
Blood DK Sim [Cata] currently inaccessible.
No settings save nor can any gear be selected. when navigating the gear to select/equip, the highlight denoting that it has been equipped is present but is not present in the main page nor does the sim run nor does it contribute to stats. See image below.

Reinstalling does not rectify.

**To Reproduce**
Difficult to describe reproduction, all other sims currently work, Frost and Unholy have no issues. Occured after I updated my sim last night, have attempted to download older versions to no success.

**Expected behavior**
> Launch Wowsims
> Death Knight
> Blood
> No gear appears, settings can not be changed, selecting different elixirs/potions meets with the same grey box - changes aren't recognised.
"Something went wrong running your raid sim. Reload the page and try again."

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](http://localhost:3333/cata/death_knight/blood/#eJzdlE9IFHEUx+e937g7+9xqHA22IXWaErYFaXa2YvPQjp4kOkh0sFuCGoGH0C51aYuwsL8Q1CpqfyiNArM6FEWHOlRGhcW2qKFEQQUFCZForNZvZnZLcovs2DvM7/2+v+/7vDc/dpaKJQiCBVshDpAAGAc4iNCPMIjwCqFqoQxRqIYdcBNgCKACZVAEtY06mKemqW5XQ7PklUl9CaTIXdMsMK7pnsvt4tdTLNgN5JX3plmwF8gvn+aHbzWdnUgwInk0zQL7teBxu6yH5628bOIUy5SRfIdro5oOAslyJ688pOk2UwheAFLlkRlmnJn55gb8qOy1ad3c3bdstuaXr3PaWKluC3ykgfssmAAS5edpxp9jzrM/bR9NceNFlQRec36K6RmCni+BEaiBWjgOEHqFAUZDIPynocT/8dXGY7nX+UeFUCVsEFUk4RauNyIR0zQNI2wvZiTM13B5xJgb5YYxV76HK6STSZSvpzBwNInakSQGr6XQuJrC6LEkWokXWJ1I4kMUB1EaQeE1TrAAUBFJqodE6cAU6hLxrHyt0fJDvR9nOdSOJ1lv2GhR+PgVglKiLiUlJEuiwkZAUL2UR8w0yhx/Yhpznq/OnN+9wpSwuorKlOVzPGuNMlqg55PvGmQGyg6WExnNIFMzqCxWC8lHXG6sa2ppcOR36dyTrHHL5BdppoTUINkev04kmXbVjT42a9fT545wYExUNLXEYXkU9ijLCpuGym9H+nSbaaD4VXJ2T1vtXalaTIWhAt47rw1RAhtEaLY4wLY+pnCzk09+yMzvvvaXKdGRn/H5bUZBaFG2p0OIzm6ZbeJR8vb9bBJ2mwy/wfdYP4mwl7k/wSLrbCbbYrWxYp+T7ktaBR3tdgzHVj55bAdZmkd/gNXMdcQbrYIsYIlrHYitc5XB2LJGJ1KxSrf4Y8w8jDsufYbd+Zvqttdrm+uatzXs1GoD3tA8/19q9lvz+8Qm9/yNK17/wOZujHZ1Vv6Z8yvv93znNuLnfJXtkL3LDFu0vgMc5AeO)

![image](https://github.com/user-attachments/assets/5a3a7f88-065e-4fba-ac73-aa8b732b61c5)
![image](https://github.com/user-attachments/assets/bcb1f726-32af-4160-aa60-76b7cfef2be5)
![image](https://github.com/user-attachments/assets/6c36884b-a7eb-4a87-8361-9b39607abefa)

**Desktop (please complete the following information):**
Windows 11
Chrome
v0.0.99

**Comment by hillerstorm** [comment]
Have you tried to Restore Defaults? Press the ⚙️ icon up to the right and press the "Restore Defaults" button. This won't mess with any of your saved saved sets or saved settings.
If that doesn't work you might have to clear your local storage, this will nuke saved stuff though.

**Comment by 1337LutZ** [comment]
@BloodyGH Closing this issue as we haven't heard from you in a while.
