### ISSUE TITLE
Suggest Reforges not working for Protection Warrior with custom EP weights

### ISSUE THREAD

**Issue by decio** [wowsims/cata#1100]
1. Go to https://wowsims.github.io/cata/warrior/protection/
2. Add any custom EP weight, it can be any stat and value, for example set melee hit to 2%.
3. Click on Suggest Reforges.
4. No reforge is suggested to achieve the 2% melee hit.

![image](https://github.com/user-attachments/assets/a2add680-3109-4662-90d5-d63177995873)

 - Browser Chrome, version 129.0.6668.101

I tested with a few other classes and specs and this process works, even with Arms or Fury warrior, changing any custom EP weight and clicking Suggest Reforge will give reforge results to achieve the respective custom stat, but does not seem to work with Protection warrior.

**Comment by 1337LutZ** [comment]
@decio works for me.
Are you sure you upped the Stat Weight for Hit to be above other stats?
Also make sure to read the description of custom EP weights
![image](https://github.com/user-attachments/assets/d1d10ff4-facb-45db-8c6e-e2b82a2fdd2d)

**Comment by decio** [comment]
Well, I'm not sure what I'm doing wrong then, no matter what value of hit or the value of any other stat I set, low or high, nothing changes. Even if I increase or decrease the current weight of hit in the Stat Weights screen, I get no reforges suggestions for my custom hit weight, same with any other stat.

Maybe I'm not understanding correctly how the custom EPs are suppose to work? I thought it's weird that it works out of the bat for any other spec/class but not for prot warriors.

If it is indeed working, I guess you can go ahead and close this.

**Comment by 1337LutZ** [comment]
@decio prot warrior doesn't have Hit as a reforge stat by default and almost all other classes do.

1. You can reset to defaults
2. Change Hit stat weight to 8 or something (a bit above other stats)
3. Enable custom EP in Suggest options
4. Set hit to a %
5. Press reforge
