### ISSUE TITLE
Missing items: Wrong iLevel, Band of Ghoulish Glee

### ISSUE THREAD

**Issue by alleac** [wowsims/cata#1124]
[Cataclysm Wowhead](https://www.wowhead.com/cata/item=71327/band-of-ghoulish-glee") 

Wrong iLevel in the sims, Showing as 353 but in game its 365

**Comment by zoristaken** [comment]
![image](https://github.com/user-attachments/assets/4a0dea97-8e03-45c9-b41a-385146d3f044)
This was updated after we got to know they were 365 instead of 353, are you using an old downloaded version?

**Comment by alleac** [comment]
I was using the webversion, But you are completely right, Its updated for
me, MAybe using some old cached.
Thank you

Den tors 24 okt. 2024 kl 00:04 skrev zoristaken ***@***.***>:
