### ISSUE TITLE
Blood DK Expertise is adding 180 from talents that doesn't exist.

### ISSUE THREAD

**Issue by SoDelirius** [wowsims/cata#1155]
**Describe the bug**
When using the Blood DK SIM tool it shows a +180 from talents to expertise that doesn't exist.

**To Reproduce**
1. Go to Blood DK sim
2. Edit gear, talent, etc to match wow character.
3. Hover over expertise to show values.
4. Check character values and they will not match actual in game values.

**Expected behavior**
Expect values in sim should match real values in game when configured to match.
![ingame](https://github.com/user-attachments/assets/9669c288-d8d8-4e23-a7df-b222744461c9)
![wowsim](https://github.com/user-attachments/assets/8754592e-99e0-468a-9577-86b452ddee72)

**Sim Links and Screenshots**
![ingame](https://github.com/user-attachments/assets/9669c288-d8d8-4e23-a7df-b222744461c9)
![wowsim](https://github.com/user-attachments/assets/8754592e-99e0-468a-9577-86b452ddee72)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 132

**Comment by rosenrusinov** [comment]
![image](https://github.com/user-attachments/assets/f0783631-8370-400f-b82e-1a8e2680d69d)

Did this get removed from the game? @SoDelirius

**Comment by rosenrusinov** [comment]
Nope it did not. You can clearly see in your screenshot that 687 rating gives you 22 expertise rating but your character sheet shows 28

![image](https://github.com/user-attachments/assets/fe6576ce-d625-49b4-8420-2e8c068ec03b)
![image](https://github.com/user-attachments/assets/82902bd2-d242-4abc-9464-f675a696c746)
