### ISSUE TITLE
Unable to launch wowsim on Windows 64

### ISSUE THREAD

**Issue by mrvaghani** [wowsims/cata#1193]
**Describe the bug**
Double clicking the "wowsimcata-windows.exe" binary does not launch the web interface. Executing the binary through CLI shows an error message

```cmd
D:\Utils\wowsimcata-windows>wowsimcata-windows.exe
Version: v0.0.132
2024/11/10 22:04:24 Embedded file server running.
2024/11/10 22:04:24 Launching interface on http://localhost:3333/cata/
Enter Command... '?' for list
> 2024/11/10 22:04:24 Failed to shutdown server: listen tcp 127.0.0.1:3333: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

D:\Utils\wowsimcata-windows>
```

**To Reproduce**
1. Download [wowsimcata-windows.exe.zip v0.0.132](https://github.com/wowsims/cata/releases/download/v0.0.132/wowsimcata-windows.exe.zip)
2. Extract the zip and open this folder in command prompt
3. Type "wowsimcata-windows.exe" into command prompt and hit enter

**Expected behavior**
Double clicking or launching the binary through CMD should start the app and open the web interface.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox 132.0.1 (64-bit)

**Additional context**
I don't think it's a port/permissions problem.
Launching CMD as admin and running the app while passing different launch URL still results in the same error.

```cmd
D:\Utils\wowsimcata-windows>wowsimcata-windows.exe -host "localhost:3334"
Version: v0.0.132
2024/11/10 22:11:18 Embedded file server running.
2024/11/10 22:11:18 Launching interface on http://localhost:3334/cata/
Enter Command... '?' for list
> 2024/11/10 22:11:18 Failed to shutdown server: listen tcp 127.0.0.1:3334: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

D:\Utils\wowsimcata-windows>
```

**Comment by Tharre** [comment]
@mrvaghani can you run this command in CMD and post the results:
```netsh interface ipv4 show excludedportrange protocol=tcp```

**Comment by mrvaghani** [comment]
> @mrvaghani can you run this command in CMD and post the results: `netsh interface ipv4 show excludedportrange protocol=tcp`

```cmd

Start Port    End Port
----------    --------
      5357        5357
      5426        5426
     23689       23788
     23789       23888
     23889       23988
     23989       24088
     24089       24188
     24294       24393
     24394       24493
     24494       24593
     24594       24693
     24694       24793
     25118       25217
     25218       25317
     25318       25417
     25418       25517
     25518       25617
     25950       26049
     26135       26234
     26235       26334
     26335       26434
     26435       26534
     27116       27215
     27216       27315
     27316       27415
     27416       27515
     27516       27615
     50000       50059     *

* - Administered port exclusions.

```
Also, I tested it again today and it seems to be working. I did not make any changes, nor did I download a different binary. Not really sure what is going on.
I do remember doing a manual restart when it wasn't working, and it still did not work after restart. So it's something else, but I am not sure what changed.

**Comment by Tharre** [comment]
> Also, I tested it again today and it seems to be working. I did not make any changes, nor did I download a different binary. Not really sure what is going on. I do remember doing a manual restart when it wasn't working, and it still did not work after restart. So it's something else, but I am not sure what changed.

Yeah, that's to be expected. Microsoft thought it was a good idea to reserve random port ranges for NAT purposes. The thought that program may sometimes want to use some of those ports never crossed their mind.

In any case, if this happens again you can manually set the reserved range, see [this comment](https://github.com/docker/for-win/issues/3171#issuecomment-1895729704).
