### ISSUE TITLE
'Suggest Reforges' sometimes removes all reforges

### ISSUE THREAD

**Issue by stako** [wowsims/cata#1208]
**Describe the bug**
Clicking the 'suggest reforges' button sometimes removes all reforges

**To Reproduce**
1. Restore Defaults
2. Use WowSimsExporter addon to import gear/talents/etc
3. Click 'Suggest Reforges'
4. After some loading time, reforges are all removed

**Expected behavior**
After clicking 'Suggest Reforges' expected to have gear reforged approriately.

**Sim Links and Screenshots**
[Sim Link](https://wowsims.github.io/cata/rogue/combat/#eJzdVF1oHFUUnnPv7O7dk6S5e5PYyZXS6RDLuJI6O5NITH92UxBCKRLEh/gYSP1rH0r0xT6t9YfE+hAVXRNUaEQoeZItDZKnUGyj/XFLlJj6A1IoVOmDNnnIw9p478w0mSZvIgoe5uGec77znb97Bx9iwKEEz8NxGAX4EOAMwBzAEsAtgDKBUQKfEziIlgL1w6CCCUPONE7S9MCxoVeOjLAsT8s3CAp+/U9q/WE76ekJs16h7juAGf5tnbqfATbyH5Xztu3QlQrFNl4/bXqrd9ciAesy0yDBv1egNxWDAmmGCmATn6xTa2qXA4b7rlaXFOTOTsdUEENFzC9SJ6uwK+HnjgPu4DfvUm9mg/yTDcIzgM18VRGORZVog8qq8BvFaFuGz6q6VT6Tn6xTpV64SN1TgMgvquDXbO1Cvlox9Xlc46fqumGHMeK1D5BBkv+FWBSXwPifiij/5631GgeNG5DDZnUrwCI2dVufuHrlyv5ZstcLfN+7Xzr9IPC9wAsKnh94XsEP/EKnpwyb5DzpYD/VCL9UI9bPNWJfrRF3/ibxFmukZ3mBlO4skP6VBfIVMa+R7A/EuEHG02rTLchkGk32zZfUyWAKaWfhJcxhWppIrNy6SZiS9BqiV/agI2xsdBBZFZSPnXWR57cxEPQkGFJZEDxfYEYf2VJTfDjrisdkFz4iHsa2fAujgs3G0VFIEJKYCZLgXtx+uRcL8tEYQE4Yul4k3R5mq6BLP/VBaksJ3WFTv71HxW7ZgQ/Kdtyeb2MpkZ2G2BGxFLrDNDNHxQWQ5wG/AHEOQrZ0kg0bnCxmfA2tqLU5DcnciWGcO5bUZo7GTORQXHTBx+1OG7ZUgeM2NvaAvXZPAA/IfdhUVe+a8JRi/m6UJNW1MiTV6TmaVD/9FWRUnNC9bqk/dFa56GAg7XAUagMv6gZGl1MyXHJhT4zaIw7Jfjwg9m1ZSRfmnOZk2rH3U+E6U5vXGY1fucVhlXGDDf4WW7DOpu/BbtERctH7FrTpdnR5YTO/N4mdcge2CrE1JL6gAuX6C7hFhl+l0SNtLZ2OT8+U3qKGM0/6aTbU50ZKucjzZKl9ckLL18XHI8u14q5nQ1ks9qknreR20X+bHJ9ehhMNTw29MGw/PTTy3JGX7UErk/+XfrIDr5f+Sbry8HyS73DPxx/1bcaE0yhPZfsmIBrQ9WKMMUt/AT6iMB0=)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox 132
 - Version: Wowsims 0.0.137 (Running locally)

**Additional context**
- Only happens with some gear/spec combinations. I've noticed my combat rogue sim having slow reforges fairly regularly
- Likely resultant from the timeout reduction to 10 seconds made in commit 4fb2e32
- Anecdotally works fine in Chrome 130 - I guess Firefox is slower

**Comment by NerdEgghead** [comment]
Can you try again on Firefox after a refresh and see if it works now? (It will still take a very long time compared to Chrome, Firefox performance is just intrinsically awful.)

**Comment by stako** [comment]
Looks to be working now!
