### ISSUE TITLE
Crash Report -1555404275

### ISSUE THREAD

**Issue by yasar11732** [wowsims/cata#124]
Link:
https://wowsims.github.io/cata/paladin/retribution/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnVg8gEqEGKT2s8xiZgvISaxMLeJgFWCRWsfIxS+w6jCTxEtZJbZth5mu7WDiYhF4tpcJKHylh0lisZwS254dTE+BwuwC/cuYJKbKAGUubmWS+CELlnkGlOES6Aaa0CqnxMjAxStwCSg5RUaJBSjJwMUj8G0vE1ghEAF1nlzEJPFPEi7ALtB5i0nivwLQzq69IJu3LgORr8+DyDd7QQruLGeSOCvLxQAUOLaUSYmDg92AN4AzgVHrKBPXBCaGUYAChAxI1WHF4MSwi5FNioWLSYL5EBPDCSaWC0zst5gYHjExSTC+YDrBuJAZojLSoYuZQekJEyeY15DmIAgRF3GQnDUTBE7aW0JELtgrpoHBNXtHiNROe6PVTAoREqxaNI4zjU4HcrQ1pBwnoC+YLHOJAZBA2/vewRHC/2GfwAgAD+5oeQ==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x114020, 0x17fbd40})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Aura).Activate(0x0, 0x2fc2000)
	/home/runner/work/cata/cata/sim/core/aura.go:536 +0x2
github.com/wowsims/cata/sim/paladin/retribution.(*RetributionPaladin).Reset(0x2f8a200, 0x2fc2000)
	/home/runner/work/cata/cata/sim/paladin/retribution/retribution.go:67 +0x15
github.com/wowsims/cata/sim/core.(*Character).reset(0x2fb0000, 0x2fc2000, {0x36ed58, 0x2f8a200})
	/home/runner/work/cata/cata/sim/core/character.go:516 +0xb
github.com/wowsims/cata/sim/core.(*Party).reset(0x2f7afc0, 0x2fc2000)
	/home/runner/work/cata/cata/sim/core/raid.go:76 +0x8
github.com/wowsims/cata/sim/core.(*Raid).reset(0x2eb4f20...

**Comment by InDebt** [comment]
Thanks for your report!
Right now the Retribution sim hasn't really been worked on so there's basically nothing present yet. So those kind of issues are expected unfortunatley :(

**Comment by rosenrusinov** [comment]
Retri sim not available yet
