### ISSUE TITLE
Dark Archangel seemingly triggers a GCD

### ISSUE THREAD

**Issue by TheHate123** [wowsims/cata#125]
**Describe the bug**
The sim casts Dark Archangel for Shadow Priests about 12-13 seconds into a pull, and then does nothing for 1 second. I assume it's coded to trigger a gcd which it does not, the spell is off-gcd.

**To Reproduce**
1. Run a sim.

**Expected behavior**
The spell should not trigger a gcd.

**Sim Links and Screenshots**

![Untitled](https://github.com/wowsims/cata/assets/118665346/7839177e-9bc8-443e-813e-b11f39868d61)

There is a full second between the Dark Archangel at 12.53 and the Mind Blast that I'm hovering.

**Comment by InDebt** [comment]
https://github.com/wowsims/cata/blob/0faece9a5448aa2d9657b7626a039c80168d0cc6/sim/priest/talents.go#L286

Yeah for some reason I assumed a gcd here. Will remove that
