### ISSUE TITLE
Missing items: [Belt of the Fallen Brood

### ISSUE THREAD

**Issue by DonHanson** [wowsims/cata#1254]
Links to [Cataclysm Wowhead](https://wowhead.com/cata/items "https://wowhead.com/cata/items") for each item:
https://www.wowhead.com/cata/item=60231/belt-of-the-fallen-brood

**Comment by hillerstorm** [comment]
> Links to [Cataclysm Wowhead](https://wowhead.com/cata/items) for each item: https://www.wowhead.com/cata/item=60231/belt-of-the-fallen-brood

![image](https://github.com/user-attachments/assets/a17c4282-44f9-45d8-b732-b04959677c6b)
I think you might have Phase 1 or 2 picked?

**Comment by DonHanson** [comment]
I have Phase 3 selected. The Waist tab has this issue but others do not.
![2024-12-10_10-52-34](https://github.com/user-attachments/assets/44c93c5f-c379-41fe-b09a-f1cc8388291c)

All Filters enabled.
![2024-12-10_10-57-23](https://github.com/user-attachments/assets/2f69c9c4-54aa-4c80-bcab-0a96175d164b)

Gloves dialog looks fine.
![2024-12-10_10-53-41](https://github.com/user-attachments/assets/aad9a3d6-b7a5-4e37-a88c-97d1b5f3e7a0)

Running latest MacOS Sim.

**Comment by DonHanson** [comment]
See same issue w/ online version. Happy to admit I'm doing something wrong, just not sure what.
![2024-12-10_11-00-27](https://github.com/user-attachments/assets/40803361-66fe-4f19-95bd-36a20c1dc188)

**Comment by hillerstorm** [comment]
> I have Phase 3 selected. The Waist tab has this issue but others do not. ![2024-12-10_10-52-34](https://private-user-images.githubusercontent.com/1934614/394411768-44c93c5f-c379-41fe-b09a-f1cc8388291c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjMyMjcsIm5iZiI6MTczMzk2MjkyNywicGF0aCI6Ii8xOTM0NjE0LzM5NDQxMTc2OC00NGM5M2M1Zi1jMzc5LTQxZmUtYjA5YS1mMWNjODM4ODI5MWMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAwMjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMTNlNzBkYjBiMDJkMWZiYTdlNGViNjY1YjhlOGE4NTMyNDUzYzBiZjM5ZWUwNmM0ODJhZGI3ZTY0ZTJmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7AW5bC5O_ClUUgAOPpoAL03H3lfEaOrejVEPnKVJvgg)
> 
> All Filters enabled. ![2024-12-10_10-57-23](https://private-user-images.githubusercontent.com/1934614/394412466-2f69c9c4-54aa-4c80-bcab-0a96175d164b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjMyMjcsIm5iZiI6MTczMzk2MjkyNywicGF0aCI6Ii8xOTM0NjE0LzM5NDQxMjQ2Ni0yZjY5YzljNC01NGFhLTRjODAtYmNhYi0wYTk2MTc1ZDE2NGIuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAwMjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OGM4ZDk2MWI5MTNmMTllNGZiNmE5MzMzOGQ0YjI4Y2UyNzU2YzQwY2QzNTgxZTYxMTJmOWI0NjkzODRjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5SHXb94AbJpBhABkHMWHZV9Z8e0_YI-EvCiqPqKEXc4)
> 
> Gloves dialog looks fine. ![2024-12-10_10-53-41](https://private-user-images.githubusercontent.com/1934614/394411939-aad9a3d6-b7a5-4e37-a88c-97d1b5f3e7a0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjMyMjcsIm5iZiI6MTczMzk2MjkyNywicGF0aCI6Ii8xOTM0NjE0LzM5NDQxMTkzOS1hYWQ5YTNkNi1iN2E1LTRlMzctYTg4Yy05N2QxYjVmM2U3YTAuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAwMjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZWZhNGEyNDA5YjdjNjNkNjZjN2NiY2I4YTkzYmIxNmYzZjRiOWQ2MDIxNGY2NWMzNjU0ZWEzNDE5NTVkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RxQMdeeu2-Jsj5TfFz9Nz70SccQujn15Lr8OOv-621U)
> 
> Running latest MacOS Sim.

Oh you're trying to use a leather belt on a Hunter. Since [Mail Specialization](https://www.wowhead.com/cata/spell=86528/mail-specialization) is a thing in Cata, we only show the appropriate armor type. It's never worth to equip a leather belt as a Hunter and loose 5% Agility :)

**Comment by DonHanson** [comment]
Awesome! Thank you for the explanation.
