### ISSUE TITLE
Enhancement Shaman, missing weapons..........

### ISSUE THREAD

**Issue by Ifartstarz** [wowsims/cata#1269]
1H Axe, Maimgor's bite, not available at all

**Comment by hillerstorm** [comment]
> Maimgor

<img width="660" alt="image" src="https://github.com/user-attachments/assets/3b17cdd2-2696-40a7-981c-c04c403e0b66" />

It is indeed available, but it's an Off-hand so it only shows up if you actually try to replace your Off-hand weapon :)
