### ISSUE TITLE
Crash Report -51356722

### ISSUE THREAD

**Issue by Mayf** [wowsims/cata#143]
Link:
https://wowsims.github.io/cata/hunter/beast_mastery/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnXg4GD0gSoBiQgxSy1lnMbMF5CRWphZxsAowSR1m5OIXuPucWeKjghLbqpksH6czc3EK/JvBrMT8BcjkF3i8g1nijQKYp9HFyMUu8PE9s8RpDqDMze3MEm1AXYtmgJVyCXwHyixSVGJk4OIV6D3GLDFNUokFKMPAxSNweyezEhuQDTHzENDMeRCdQASU3gh0wBt5iJWcAn9gtrMIzHoOIk/tAJEdQJJdYMJfZolmRS4GoH1/gQ44rwB0lRIHB5MBYwBTBJPWUSauCUwMowAFCBmQqsOKwYmpgLFKmUuRS15AXkqSg0mA0YDJgtmDOYIxg7kClJ4mMDLNYAQG+y4maSNjYwMjYwNjQ0NjIwNDQyMg1AXyjXQNjA8xCXBMOs8ksPg8k8SSp0wK084znWBiucDEfouJ4RETlwSjEpsQCxcTF8MLppSFzBDLIx26mBmUnjBxgnkNaQ6CEHERB8lZM0HgpL0lROSCvWIaGFyzdzx7BgTe2ButZlKIkGDVonEy0Oh0IEdbQ8pxAvqCyTKXGAAJtL3vHRwh/B/2CYwAtFqClA==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x114a20, 0x180ed20})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/hunter.(*Hunter).applyFocusFireCD(0x34a6000)
	/home/runner/work/cata/cata/sim/hunter/talents.go:439 +0x8
github.com/wowsims/cata/sim/hunter.(*Hunter).ApplyTalents(0x34a6000)
	/home/runner/work/cata/cata/sim/hunter/talents.go:62 +0x32
github.com/wowsims/cata/sim/core.(*Character).applyAllEffects(0x34a6000, {0x36d1d8, 0x2c1f0e8}, 0x2fc11a0, 0x2ffff50, 0x2fc0fc0)
	/home/runner/work/cata/cata/sim/core/character.go:275 +0x12
github.com/wowsims/cata/sim/core.(*Raid).applyCharacterEffects(0x2ec1080, 0x2fa9980)
	/home...

**Comment by ToxicKevinFerm** [comment]
Looking into this. Looks like BM has some other issues I need to solve as well.

**Comment by rosenrusinov** [comment]
This seems to have been fixed. Cant reproduce anymore on latest version
