### ISSUE TITLE
Can't add a target to encounters

### ISSUE THREAD

**Issue by Yungbalast** [wowsims/cata#213]
![wowsims error](https://github.com/wowsims/cata/assets/168205987/9217e1b4-f5ba-4f70-a552-c26f7f463902)
**Describe the bug**
So I accidentally deleted the target for Encounter, now there's no option to add it back and I get the error message provided in the ss. There's no way to add a new target either.

**To Reproduce**
1. Go to Encounter
2. Click on Advanced and then delete all current targets and try to sim again. It will provide the error message and no way to add a new target.

**Expected behavior**
The advanced tab should not disappear and allow you to add a new target.

**Sim Links and Screenshots**
![wowsims](https://github.com/wowsims/cata/assets/168205987/54e82529-bf77-44bf-abd0-8149c4424a24)
![wowsims error](https://github.com/wowsims/cata/assets/168205987/9217e1b4-f5ba-4f70-a552-c26f7f463902)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rosenrusinov** [comment]
You can restore defaults or follow a link from someone that has valid targets. We can look into fixing the possibility of deleting the last target
