### ISSUE TITLE
Crash Report -896605743

### ISSUE THREAD

**Issue by luckykasper** [wowsims/cata#233]
Link:
https://wowsims.github.io/cata/paladin/retribution/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnVg8gEqEGKQOs8xiZgvISaxMLeJgFWCR2szIxS/w7DqTxEtZJbZth5mu/Wfi4hT4cYdJiXneSSYuHoGmvUwSD2SVmPfsYOJiF7i8m0liqgxQy789TBI/gFqAikAyvAJdQJlWOSUWII+Bi0vgLlB+iowSIwPQiGu7mJTYgOIghfwCr4GWvUfoZBfoB9rwX4GLRaB7JxOQnLUHRL4+DyLf7wYpOAA0+qwsFwOQ+eQcE9BMJQ4OdgPeAM4ERq2jTFwTmBhGAQoQMiBVhxWDE8MuRjYpFi4mCeZDTAwnmFguMLHfYmJ4xMQkwfiCKWUhM0RhpEMXM4PSEyZOMK8hzUEQIi7iIDlrJgictLeEiFywV0wDg2v2jmfPgMAbe6PVTAoREqxaNI4yjU4HcrQ1pBwnoC+YLHOJAZBA2/vewRHC/2GfwAgATYZrFQ==

RNG Seed: 3685963467

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:123 +0x10
panic({0x11dec0, 0x1913200})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Aura).Activate(0x0, 0x354c000)
	/home/runner/work/cata/cata/sim/core/aura.go:536 +0x2
github.com/wowsims/cata/sim/paladin/retribution.(*RetributionPaladin).Reset(0x2e5bfd0, 0x354c000)
	/home/runner/work/cata/cata/sim/paladin/retribution/retribution.go:67 +0x15
github.com/wowsims/cata/sim/core.(*Character).reset(0x3536000, 0x354c000, {0x392aa0, 0x2e5bfd0})
	/home/runner/work/cata/cata/sim/core/character.go:503 +0xa
github.com/wowsims/cata/sim/core.(*Party).reset(0x349efc0, 0x354c000)
	/home/runner/work/cata/cata/sim/core/raid.go:76 +0x8
github.com...

**Comment by rosenrusinov** [comment]
Retribution sim is not in alpha and is not expected to work atm
