### ISSUE TITLE
orc mage racial is not activated .

### ISSUE THREAD

**Issue by SyuSyuGG** [wowsims/cata#253]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rosenrusinov** [comment]
Selecting the default APL and Orc shows the Racial being properly activated
Make sure your APL the action to activate other cooldowns or a specific action for Blood Fury

![image](https://github.com/wowsims/cata/assets/5707996/ad8c820c-4a7c-4340-bfb3-d05e9e6822d3)
