### ISSUE TITLE
Crash Report -577030771

### ISSUE THREAD

**Issue by BorniPL** [wowsims/cata#284]
Link:
https://wowsims.github.io/cata/druid/feral/#eJzjkuRgzGBsYGScwMi4gpFxByNjAxNjBxPjBiZGJ3YPxgLGGYyMQgxSe9hnMbMF5CRWphZxcAowSvUycQkJPJjALPFSVolt22GmefOZNCYzcvEInOxmVmLesBPM4xd4DFTxQBZJ4G43s8RpDiVmqHohgUdAFT+AZgBVQBUJCLwDKmqVU2IBCjBARO4DVU2TRIgICUzuYVbihGiC6hMSeAhU9R7FLCGB9UCzrrMji/EIbFiFcCOPwBqYi3sYudgFdncyg4TZBZZDGKIC63uYJc7KKnECnYwwhAGocUYX3BglAQ4mA8kApgimCsYOcFhqHWXimsDEMApQgJABqTqsGJwYslikmBQYdzHJ6RoZGxkYGxkZGxoZGBqBoIGRsYGhrgFQ1MDwEJMKx7H9TAJH9zNJLHzCpHDkEpPGvH4Wg7P7mSxmXWVyOH6JyePwJaYTTCwXmNhvMTE8YjrDKMGkdJyRax9jtVJuYmZeCRC7JaYWZaa6ZRalKlmVFJWm6ijlZuY55+cm5Re75RcFZRYoWZnqKJUWpwYlZsOVALlOmSVwbhKQHZKZC+QbGqLqh6gyhShxKS3KzEt3rUhNLkXoLcos8ElNLU+sBGoG6w3KTyzyT0srTi1RsjKyBAol5pUm5gQkFiXmFkM01QqxcDFxMbxgSmlkhoSaiMNCKCvSoYuZQamdmRPMa2hzEISI2zlIzpoJAiftLSEiF+wV08Dgmr3j2TMg8Mbe6BxTwde5TFVCPpnJGQreQNcqaHikFuVnJmsqBEtwaNE4hWt0OpCjreHkEQL6gvHJf7kxfYYjOfaCADgwOR4xOs5knBTzz/nX28P2ULN+2ANLWQDynO7N

RNG Seed: 816647542

MaxStacks required to set Aura stacks: Acid Spit-2
Stack Trace:
goroutine 107 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:123 +0x10
panic({0xf3d40, 0x374d7e0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Aura).SetStacks(0x354f520, 0x2fcc120, 0x1)
	/home/runner/work/cata/cata/sim/core/aura.go:187 +0x33
github.com/wowsims/cata/sim/core.(*Aura).AddStack(...)
	/home/runner/work/cata/cata/sim/core/aura.go:208
github.com/wowsims/cata/sim/core.applyDebuffEffects.func3(0x2fcc120)
	/home/runner/work/cata/cata/sim/core...

**Comment by rosenrusinov** [comment]
The link above does not actually reproduce the error which is a bit weird... The actual problem comes from Acid Spit armor debuff not having proper MaxStacks set
