### ISSUE TITLE
Crash Report 764077967

### ISSUE THREAD

**Issue by MrZapota** [wowsims/cata#286]
Link:
https://wowsims.github.io/cata/paladin/protection/#eJztUU0oREEcf///vPfse9GOjRqb3daUklIbJ3t5j5Ojklo3am0ODpub214UdhOFcCDlsJJIyUdWPhLK1uYguZFaSTg4yIV5+zzl5KPc/A7T/L7+M83olS6gYEIXxKAfYAIgBbADcA5wAxBH6EdYRmgstUJNEM4H1wGyeTOEFDySd1yZImpzd0dvZ49LobI3B7qbZhOE3fq4OrePmQ3UNfqSIJysia2bXgsv6edqbgMtoZBOJwkbK3fs3WHCLsu4mrHtIpoeI2zQz2XBJEH3hT/qUA9dGiJspJxrdtxqeOhjH2H3Pq6tfWhirDj1NcDVd0Gjp86NNLrtbGW6NUDEmhJrIV0VB5/4nNB88j1UQBefkIPEXS4tWNSshJXqA9SHUfrHJ3iCP22EpEaMwQqoXllHRjaR1NTV7qF0hHIWCy5QukJkcIORZ4RZYnfazEFSorVamEmbxbaIZkDl16jlSTzqyCVm2dSkhWOj3layRkU0jzOjIXNi4c6oXcBAmCnVf/yjVQPmb2rxyOEXvZZfzf0O7EdLP5gNNn822uENabGEoA==

RNG Seed: 1676839704

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:123 +0x10
panic({0x128e60, 0x1a674c0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Aura).Activate(0x0, 0x2fb67e0)
	/home/runner/work/cata/cata/sim/core/aura.go:536 +0x2
github.com/wowsims/cata/sim/paladin/protection.(*ProtectionPaladin).Reset(0x2f46d20, 0x2fb67e0)
	/home/runner/work/cata/cata/sim/paladin/protection/protection.go:91 +0x15
github.com/wowsims/cata/sim/core.(*Character).reset(0x2faa000, 0x2fb67e0, {0x3b7620, 0x2f46d20})
	/home/runner/work/cata/cata/sim/core/character.go:505 +0xa
github.com/wowsims/cata/sim/core.(*Party).reset(0x2efb7a0, 0x2fb67e0)
	/home/runner/work/cata/cata...

**Comment by rosenrusinov** [comment]
Retribution sim is not in alpha and is not expected to work atm
