### ISSUE TITLE
Cata: arcane mage is broken

### ISSUE THREAD

**Issue by burntfish44** [wowsims/cata#297]
Default settings of arcane mage is simming at 677 dps

**To Reproduce**
1. Go to mage->arcane, start the sim

**Expected behavior**
Realistic values, >30k expected

**Sim Links and Screenshots**
https://wowsims.github.io/cata/mage/arcane/

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera gx
 - Version: browser? if so it says LVL5 (core: 107.0.5045.89)

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by rosenrusinov** [comment]
Not Yet Supported
![image](https://github.com/wowsims/cata/assets/5707996/aafaa5ec-e17c-4407-92c1-878010517f46)
