### ISSUE TITLE
Crash Report -1337099298

### ISSUE THREAD

**Issue by Vitavy-Vita** [wowsims/cata#310]
Link:
https://wowsims.github.io/cata/paladin/retribution/#eJztUk0oRFEYvd9334z3XuSaLJ7JiFdKSt15s8HCe6wslQ07CllYyM5uFpQxUyS/s7NTElkIUYaEIrJAohA1SgZZKAvu8/yEhZ+yc/q6fefc79xzu101VwYGFjRCM3QADAKMACwA7AHEAYIIHQgTCGVSuRjxEO+kK0rdFU21rfUtsotJ3mVQU1l/iGrnPt09tYRz06gqbDdMdWq3yaxX7B35HCaxzSsU84NCuxPzQrNllV1fotaepQMR/dE96tLOA9r9QEL0YoQI0+E9aok3UzK7aaevTGEH0edIhR2/pEusJ0LFGhapHtYXodqGT1fGZ9AplahJbOwWRa4uy0k8pUKpgfxlVLuR/OMdPPynjmJSRmbB7ZVU1Ogslhjczz+igBufNF5gBAweMPyiBAKcGwHuX8RMuS2GbPwMta4YZodiWLi+jVYkhuXxbVxFaQvd+0hOEDWIY90wdW5RbXVSop+i8sSCDVaao6dbGdEhG2tmkaNsmTkNT9gxSzfWbVyYxihmV2mu/D/+D3kh6ze2YN3KF77KX537HTiPNp+wSh1+Z9bAI0X+iGA=

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x129920, 0x1a726c0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Aura).Activate(0x0, 0x2f88000)
	/home/runner/work/cata/cata/sim/core/aura.go:536 +0x2
github.com/wowsims/cata/sim/paladin/retribution.(*RetributionPaladin).Reset(0x2fc6440, 0x2f88000)
	/home/runner/work/cata/cata/sim/paladin/retribution/retribution.go:73 +0x15
github.com/wowsims/cata/sim/core.(*Character).reset(0x2ff4000, 0x2f88000, {0x3ba160, 0x2fc6440})
	/home/runner/work/cata/cata/sim/core/character.go:505 +0xa
github.com/wowsims/cata/sim/core.(*Party).reset(0x2fbafc0, 0x2f88000)
	/home/runner/work/cata/cata/sim...

**Comment by rosenrusinov** [comment]
Paladin sims not yet available
