### ISSUE TITLE
Sim doesn't properly reset during iterations

### ISSUE THREAD

**Issue by FelixPflaum** [wowsims/cata#327]
Currently not everything resets properly between iterations. See https://github.com/wowsims/cata/pull/326 and the error log it causes.

Affected specs (there may be more, but those error currently):

- [x] Blood DK
- [x] BM Hunter
- [x] Shadow (Specific tests, see below)
- [x] Feral
- [x] MM and SV Hunter
- [x] Combat Rogue
- [x] Elemental
- [x] Enhancement (TotemofQuakingEarth)
- [x] Arms (all tests)

Shadow fails
> --- FAIL: TestShadow (26.04s)
    --- FAIL: TestShadow/TestShadow-Settings-Troll-p1-Basic-default-NoBuffs-LongSingleTarget/ResetTest (0.05s)
        test_suite.go:338: DPS did not match! Base was 16813.207 and split was 16835.357!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-Settings-Troll-p1-Basic-default-NoBuffs-LongMultiTarget/ResetTest (0.07s)
        test_suite.go:338: DPS did not match! Base was 16813.207 and split was 16835.357!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-HeartofIgnacious-59514/ResetTest (0.08s)
        test_suite.go:338: DPS did not match! Base was 27907.194 and split was 28019.032!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-TomeofArcanePhenomena-36972/ResetTest (0.07s)
        test_suite.go:338: DPS did not match! Base was 27003.270 and split was 27121.625!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-HeartofSolace-56393/ResetTest (0.06s)
        test_suite.go:338: DPS did not match! Base was 26863.136 and split was 26979.285!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-WitchingHourglass-56320/ResetTest (0.05s)
        test_suite.go:338: DPS did not match! Base was 27720.496 and split was 27845.061!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-GaleofShadows-56462/ResetTest (0.07s)
        test_suite.go:338: DPS did not match! Base was 27670.974 and split was 27779.882!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-VestmentsofAbsolution/ResetTest (0.06s)
        test_suite.go:338: DPS did not match! Base was 13846.582 and split was 13848.450!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-RegaliaofFaith/ResetTest (0.07s)
        test_suite.go:338: DPS did not match! Base was 18432.618 and split was 18436.447!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-SanctificationGarb/ResetTest (0.10s)
        test_suite.go:338: DPS did not match! Base was 18594.541 and split was 18639.912!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-Zabra'sRaiment/ResetTest (0.06s)
        test_suite.go:338: DPS did not match! Base was 19488.236 and split was 19540.430!. Something probably doesn't reset correctly on sim reset!
    --- FAIL: TestShadow/TestShadow-AllItems-CrimsonAcolyte'sRaiment/ResetTest (0.05s)
        test_suite.go:338: DPS did not match! Base was 20867.558 and split was 20878.032!. Something probably doesn't reset correctly on sim reset!

Enh fails
> --- FAIL: TestEnhancement (33.35s)
    --- FAIL: TestEnhancement/TestEnhancement-AllItems-TotemofQuakingEarth-47667/ResetTest (0.10s)
        test_suite.go:338: DPS did not match! Base was 30467.322 and split was 30465.258!. Something probably doesn't reset correctly on sim reset!
        test_suite.go:346: TPS did not match! Base was 20643.339 and split was 20642.188!. Something probably doesn't reset correctly on sim reset!

**Comment by FelixPflaum** [comment]
BM fin in https://github.com/wowsims/cata/pull/329
Tyrande's Doll in https://github.com/wowsims/cata/pull/328 (affects multiple specs)

**Comment by ToxicKevinFerm** [comment]
Blood fix in #330

**Comment by ToxicKevinFerm** [comment]
Combat fix in #331

**Comment by FelixPflaum** [comment]
Updated issue with newly failing test cases after adding a 8-6-6 split to the test.

**Comment by ToxicKevinFerm** [comment]
#339 fixes Arms and Shadow

**Comment by rosenrusinov** [comment]
I didnt realize that i closed this issue with merging the PR. @FelixPflaum ill let you close this when you think it’s actually done.
