### ISSUE TITLE
Crash Report 25401003

### ISSUE THREAD

**Issue by Airunya** [wowsims/cata#343]
Link:
https://wowsims.github.io/cata/shaman/restoration/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYndg5gIqAXCEGqacss5jZAnISK1OLONgF2KVWMnKxCLx7ycjFLzB7GrPBnf9QABL+dgJErtoHIt8AlbAL/DjOqMTIwCUk0A1UuwKuFiK29AAjkn6QGIvAM7ARfdOYgeZPRzf/I1iy4zaIPH4aRM4/CXLI18OMBr8QCtkFVp8AGafExsFmwBjAo7WXiauDiWEUgIGQAak6rBicmAoYm5jYpFi4mDgYdzGJ6uoaGBsbGRkYGBkaGxkaGRkaAOlDTBIcR48wCZx/yqSw9giTxt4jTBZfLzE5/LzEdIKJ8QIT6y0mhkdMbBLMQkxSDC+YUhYyQ4yPdOhiZlC6w8QJ5jWkOQhCxEUcJGfNBIGT9pYQkQv2imlgcM3e8ewZEHhjb7SYSSFCglWLxhGs0elAjraGlONk6aMEQAJr73sHRwj/h30CowcnAAVqjg8=

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x103480, 0x3e40d0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x3972000)
	/home/runner/work/cata/cata/sim/core/unit.go:518 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x3972000)
	/home/runner/work/cata/cata/sim/core/character.go:463 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x32890e0, 0x31b7880, 0x31b7a00, 0x3324c00, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:159 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x31b7880, 0x31b7a00, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x33246c0)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6...

**Comment by rosenrusinov** [comment]
![image](https://github.com/wowsims/cata/assets/5707996/be03b2ec-a145-4d18-801d-e5144e58cf80)

Not Yet Supporte
