### ISSUE TITLE
Issues with generating shareable links from gearsets for other people to see.  Always defaults to the P1 BIS.

### ISSUE THREAD

**Issue by Goztrak** [wowsims/cata#349]
**Describe the bug**
Issues with generating shareable links from gearsets for other people to see. Always defaults to the P1 BIS that's standard on the webpage. (The Unholy Deathknight Sim).

**To Reproduce**
1. Create a new gearset and save it.
2. Click Export > Link to generate a shareable link.
3. Copy the link to clipboard and share it to other people, they should see your gearset.
4. The shareable link dosen't include the gearset that was just created, instead it always shows the default P1 BIS from the webpage. I have tried to reset to default multiple times through "Show Sim Options" > "Restore Default"

**Expected behavior**
I expect the generated sharable link will include the gearset I just created and saved.

**Sim Links and Screenshots**
https://i.gyazo.com/5f031c7c6af90c15003ff0e8943f576d.png
Example of me creating a gearset and exporting it. The resulted link still defaults to the default P1 bis from the webpage and dosen't show my gearset.

**Desktop (please complete the following information):**
I was using Google Chrome.

**Comment by 1337LutZ** [comment]
Hey @Goztrak,

Could you share the link with me? I just tried it with 2 specs and it seems to work. Could you try doing the same in a private/incognito window?
It could be that you have outdated settings.

**Comment by rosenrusinov** [comment]
Also make sure you have actually enabled the category you want to share in the link generation popup

![image](https://github.com/wowsims/cata/assets/5707996/c76e8f8d-5e3b-4709-9755-8c9b2022911a)

**Comment by Goztrak** [comment]
> Hey @Goztrak,
> 
> Could you share the link with me? I just tried it with 2 specs and it seems to work. Could you try doing the same in a private/incognito window? It could be that you have outdated settings.

https://wowsims.github.io/cata/death_knight/unholy/#eJztUc9LVFEUvuec5/y4JXMdXNzepuelxUMQ3pu3MTfv6aqlS2tlYK5aRDt3E4SokMxuZiQrkUhoI22aAjeRlZD0oOcIJQSBjIQ400Jpl++92/wBGu36uIvzfef7zv3FZQ4CmIQyQA2gAzCHsI4QIozlRdy5AxWAIjNf9SxRZvz2zZlbd3MguPkVeFF8+0SyY6n887qxG1IzJJ4V7RbZFeAFcdQm+cNSdFwl+ynEne0GyftW3Olskpy1VOaoSvHivWLxLcknA8qIGYtppUG61oPWW6Qyx6k3GVQQPzepG7arifD5Hcn9yyoVKslWi/oQF8XeiqG6waz4XSP7GXBDbDWIc3HSIrlm2o+As9i6+5K0dQHUhRw4chwmkssPbiCfQ/YfKYrOWRMjbIzdKJi9PN+nhY5fZK/RLDmeOzTkep7jeCW35Dme57pJ4b7BK7nDfRSPI5TLEVoPI7RfNNF5EOFwfQeD6g5eq0X4AY0Qs1+QfUeUcIBT90hv0B+s/KmuBwvE1B7mU1aeDvq6jktL9QRb/lWthP7AdIqmP7r9McGhX1pFa0L2DP7j37fng/PEylPvz5X7G+jH2mgHo5r/8ifhFD9AjYM=

**Comment by Goztrak** [comment]
> Also make sure you have actually enabled the category you want to share in the link generation popup
> 
> ![image](https://private-user-images.githubusercontent.com/5707996/328603035-c76e8f8d-5e3b-4709-9755-8c9b2022911a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDQyNTMsIm5iZiI6MTcxNTEwMzk1MywicGF0aCI6Ii81NzA3OTk2LzMyODYwMzAzNS1jNzZlOGY4ZC01ZTNiLTQ3MDktOTc1NS04YzliMjAyMjkxMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTc0NTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFjMGU1MWU4NzY5YWVjNmQzNGU1OTBkNDBlMDRjMTEyMTE3ZjcwYzQzNDU1OWE1OTgyNDAwNzMwYzJjZDNlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M3UdKWcwqbwmU4Y_5ZEM5MLFrmC1qB4P5Ul6DyZ6NUQ)

I understand but what if I want to share the whole profile I made? Also I tried unticking everything but "Gear". Same issue stands.

**Comment by rosenrusinov** [comment]
If you want to share everything you select all categories but i opened your link and i see that its not showing the selected gear. We will investigate.

**Comment by 1337LutZ** [comment]
@Goztrak I've found the issue, thanks for sharing your link!
Should be fixed in the next release, keep you posted.

**Comment by rosenrusinov** [comment]
@Goztrak can you try exporting a new link and check if its fixed

**Comment by Goztrak** [comment]
> @Goztrak can you try exporting a new link and check if its fixed

Works! Big thanks and well done!
