### ISSUE TITLE
Crash Report -2014523872

### ISSUE THREAD

**Issue by Thiccmatty** [wowsims/cata#359]
Link:
https://wowsims.github.io/cata/paladin/retribution/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnbgEGC0YPRgjgAqFGKResMxiZgvISaxMLeJgFWCRWs3IxS9w8BGTxEtZJbZth5n27GDiYhH4/ZSJi0egaS+TxANZJeZzZ5m42AXagIpOcwBVn3rBJLFFUokNqBSkmktg7j4miVY5JUYGLl6B/3uYJA7zKLEAZRi4OAUanjEpMYNU8Qs0Ak17LwvWdmIHyMC+XUwSn2SBtr1+ArJz13MQ+WYviHx9HqTgwG4mibOyXAxA5uNzTEDzlbg5GA0kAoB+mcDIqAVU2cHEMArAQMiAVB1WDE4MuxjZpFi4mCSYdzFJGxkY6xoY6RoZGwGRIRABgbGBoREQH2IS4Wg5yKTw/BKTRvdBJosXl5gczlxiOsHEcoGJ8xYTwyMmJgnGF0wpC5khRkc6dDEzKN1h4gTzGtIcBCHiIg6Ss2aCwEl7S4jIBXvFNDC4Zu949gwIvLE3WsykECHBqkXjyNXodCBHW0PKcbL0UQIggbX3vYMjhP/DPoERAODAdyI=

RNG Seed: 1420814848

Spell {OtherID: 3, Tag: 1} missing CritMultiplier
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:123 +0x10
panic({0x1039a0, 0x302e370})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*SpellResult).applyAttackTableCrit(0x338e870, 0x338e6c0, 0x31604d0, 0x3feaa2c2b2545b21, 0x3aff9c8)
	/home/runner/work/cata/cata/sim/core/spell_outcome.go:471 +0x1f
github.com/wowsims/cata/sim/core.(*Spell).OutcomeMeleeWhite(0x338e6c0, 0x335eea0, 0x338e870, 0x31604d0)
	/home/runner/work/cata/cata/sim/core/spell_outcome.go:166 +0x95
github.com/wowsims/cata/sim/core.(*Spell).calcDamageInternal(0x338e6c0, 0x335eea0, 0x33f2000, 0x408cda74faa6730b, 0x3ff07ae147ae147b, 0x0, 0x3affc38)
	/home/runner/work/cata/cata/sim/core/spell_result.go...

**Comment by rosenrusinov** [comment]
When will paladins learn to read… the paladin sim is not released yet.

**Comment by Thiccmatty** [comment]
Hey, just gonna say, replying like this is super unprofessional. People
make mistakes, and this could have been handled much better.

**Comment by Thiccmatty** [comment]
Something I'd like to point out, is that I found this tool through Google
and assumed it would work. There was nothing easily visible on the sim page
that suggested that it wouldn't work. I was simply doing as the website
instructed to submit the report.

You need to do better to make this tool easier for the average player to
understand if you want to avoid getting more reports like this. Get off
your high horse.
