### ISSUE TITLE
Crash Report -1994001352

### ISSUE THREAD

**Issue by AugustFloden** [wowsims/cata#380]
Link:
https://wowsims.github.io/cata/shaman/enhancement/#eJztU09IFFEYn+974+7bZ9brqdv0ChynhGXBmN3BMA/u6kmig9DFbgUlEQXSnrotJGXuITHC3EPhKUkI8ShItU1mQSESJgVBRiAhRCKksmlvZmwJO1RCt77D473fv/fjDcPqKHBIw1nogh6AWwDDAA8B5gAWALIIPQijCK2VHBqhDTqUbNRnFSU0OULzJNR+/tSlMxcp4WGZQyb4h2/E+GJaoXuD+uIAiQ2DwlaGdPvr+kYwEOsHtot/VLpF0yLLSpQDxniuSIxuM9bnGd4r8ooKUaTHDwKr4N2Kf2daoHl+zueVJGdauuJ9RPK5dWLfLN1SMiuumk/OEuO2aUUCzIP7vBJ3VeZijfXjEsFfq4yfmipRmI8X/RCdP5kkal0uEtU2q5yXzdgAbNnfWSVexTxYlKJd3Y4dGJ9A1oPa//FH2H/raNJasQvWICqr2E6KgqahDdXDggmcGDiO+xw7mbRtpz7pqEnYdsJRJzuRdJKJAh6krov8sYvGpIvmIxdj9120x11sLM5genUG29ZmcAr1aaRvUJtHJSRMsLAsY4S6aIWZ2tQfzrBKRmWI6TTfq2+CToZVb4Iv+okVYQquTxxqyAhdYpMmGqTD4iLGjHiU6iJ8zku8vl/6OlXzQobtsBijY+ARL6My4AWTQWZhXheGjLIKq5xFkspDl5pN8FVLzaJW1rBovIqCiBTAkz/vJx7HoMGX3CCloFdXQRyTR1mLSPmW0C8Wh9XFD1Ai5Bju8RK9ho7XUNI8BmmSFFDbmjz9QBcRGbzVRnlp+6l5AadgiAQf8ES6l2jWW4z4p2xneneAV6X35ge9eZY6EiDTqdpOf2ZTyRE0O4yyeN+//XNi19LbsWVPP/2N7/i2cv9kgrea+JxuCc4rqZPwHcQz2ZU=

RNG Seed: 2063253675

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x1349a0, 0x1bc1840})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/shaman.(*Shaman).registerFireNovaSpell.func2(0x307de60, 0x3922000)
	/home/runner/work/cata/cata/sim/shaman/firenova.go:48 +0x1d
github.com/wowsims/cata/sim/core.(*Spell).CanQueue(0x39ef200, 0x307de60, 0x3922000)
	/home/runner/work...

**Comment by rosenrusinov** [comment]
Fixed
