### ISSUE TITLE
Crash Report -2126668227

### ISSUE THREAD

**Issue by Taywer73** [wowsims/cata#395]
Link:
https://wowsims.github.io/cata/paladin/holy/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYndhBioBcIQapU8yzmNkCchIrU4s4WAVYpPS5OAV2XGBWYmZgYOBiEXj0nJmLAR9UYuNgM2AM4NDay8TVwcQwCsBAyIBUHVYMTkwFjKsYOaTYhFg4mCSYDjExnGBiucDEfouJ4RETkwTjC6aUhcwQxZEOXcxCnKEgMH+vgyBEkMlB6Q4TJ5jZkAYTFHGQnDUTBE7aW0JELtgrpoHBNXvHs2dA4I290WImhQgJVi0aR6BGpwM52hpSjpOljxIACay97x0cIfwf9gmMHpwASMA8lw==

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0xfea20, 0x3d6670})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x3200000)
	/home/runner/work/cata/cata/sim/core/unit.go:518 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x3200000)
	/home/runner/work/cata/cata/sim/core/character.go:463 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x38e7b00, 0x38f4100, 0x38f4200, 0x304de00, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:159 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x38f4100, 0x38f4200, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x38e3dc0)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x38d8a50, 0x1, 0x1})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall...

**Comment by rosenrusinov** [comment]
Paladin not release yet

**Comment by Taywer73** [comment]
Will it be released before 05.15.2024?

**Comment by rosenrusinov** [comment]
I dont think anyone is working on the paladin code atm so probably not.
