### ISSUE TITLE
Crash Report 651491452

### ISSUE THREAD

**Issue by CharWS** [wowsims/cata#401]
Link:
https://wowsims.github.io/cata/death_knight/unholy/#eJztVF1oFFcUnnPu7Gb2JDF3b2Icb/7GIciyujK7iyWNlF2liPgUgg/qg6RgfepDaZ4EHxIQYwQh+qAm/iQqlkJBJMW2FEWIgkZUoqwBRfvQkFKsaGhVFHX1zszOuoYlYMQ3z8Nwzvm+75x7z5wZMg3IQhf0ABwCmAHYjXAGYQJhTYQr5HsYABCa7KseYuGO777Z/u0PBnCST4AEP/qamTOWHf55UH92kMWOAVXyi5PMZo9UtIOq+LAiPLC8mIjff8XMnVZsAKiGH1bILiVVyFMFCn5pkpkjS7yEqx5w6x9RpD1WMXfKFd7Js1JSE5/KM+dm/o1vYB4rFvUb/aKaTrf4RxoBdaax4ICqnM7/zjP1HP+dUQU/88qjEP/3JTN/krF9QJoSnHjBArldaYBjdsBGdyrx80i7UftsngnnQxXt2hptc42spkjUT8xkhPYHNqScdCqRSiTTaUd5yVTaSaaTjuskx7DVeDiNfDiH5tEcWkdyGBudRGdvDtsGb2P24G1cdyiHV1CfwIq7qP2FZytMRnVkyDDpRv8LtA1SXiLldBezQ9eDbFJlawvZ/y4wu4JCxBLJbopSWOqEZrSYErrEdk00y0bi8QWGLnC95uoI091SVTNGTzML5sDPDYcU3ihlGdztf/Z/FCvkcrKFRVU2kZFys7+dZgG//X3+qSkUjlwxi/9jWb7b/8AUqv5LZauHwzt8ZbfktMDor7feBAaCpD+VKzNMtMgmqh0FLgzOTLCR6z7gEZ7ncW5Cvjc0N+F4H4om2VCe4L0E0SptMkU9RUbBVTwdYYE7/TjkFen7UxedsoPWiq/LFqKEXEaRE1A4ciB3XZc++/5ezV97mIjLGDWLxllv5L15F/sHM+u9hcKSzSTiXM059ADQYFJtEUGqZFPa5BcUF7GAtR/RgAKrNIelSn+HuuQW2iA76SuxihbZC8vf14o3G0zUjs2CboyH/IIrKRqvMcKCXYXCHrQ5xT2sklRy0iDyuy+Wi6jargyGqYZUlNnSonpRV3rxwpX80nfUyqpSnSV+8On9g1t7mf9XqMseL3ibsnuYZt/DiBf1bMtGA8bioUHXxjNf+pmJzJJtnk1mVl+/5trDTOokWhvNUPwT/7Jj/dn5yHq2Xp6X7mPMH9b5x9nVfvw80wVvAQuaM1U=

RNG Seed: 0

When validating reforging for item 65369, the reforging could not be validated. 144
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0xfeac0, 0x324abe0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem(...

**Comment by rosenrusinov** [comment]
This happens when you remove the random enchantment on a reforged item. I guess we should make sure to clear reforging when a random enchantment gets changed for an item. @1337LutZ @kayla-glick

**Comment by rosenrusinov** [comment]
In this specific link -> its the belt @CharWS
