### ISSUE TITLE
Crash Report 212406270

### ISSUE THREAD

**Issue by Xeano5** [wowsims/cata#436]
Link:
https://wowsims.github.io/cata/hunter/survival/#eJztVE1oE0EUzpvZbCfPardj1e0QNVkRYzB1d2NK7CXbnoogeqwHUaEW8QfEveit/iDVg4iC1Z40/lTqxYMVKRTEg1VU6klFBEEsSqloMQfFWJ3ZTWurXqx487HszHvve9/79s2wuJyBAR7sgL3QBXAW4CrAbYBnAG8BOgl0EbhOoCXGoDWE8Ig4gT1U37h724Ht+5huEDEKyI2bX6k5nrD0vnPaeDdNXVaxTxc0+/PEt9Ag1Q1YY9ySuLGERUsSdEWByjNA5gMmQTck6Kgkk6ByN8Vq40iZmsVkUCXT/TJ9pj5Il4L0WJlOedy4+4Sa7xdbsbB6PED0SoJjsq2i04yBsqJ5OkHtL1OdZbhUVslD8o3GR1lwOJnqBYxIryi94YT0rLmM2As2kjayNXoSID1IsItE/ltg3P7TiqZIC9kLx8HGBlxm6KKOEQPy1INWuoPuD68kSYbYDwUbah89VDZWGCBxO5txs7absbOuLdfwcR3XyTrOHWKyiyPEuDRCzFPDJHF2mKR6R4h9epjcI9pjUvWcRF6Ra5op7w3XkMhDno9VIoqUlXZZDHXUMm7Ol0FdyLRZa8WwCqMZp2GNjwuQCQlgQy+16eFJgncdFQLH9pFXgqPMkkCkmazPF4o6NNLzWJSTpohiQuL4TRG+WmRwiYijSJuM8lgfqCZvzlMRNHFz9h5/3xyMFSfjHEUoRO23iM24ga9H5qpI/3ka0Oic7az4AlHKcmxb0mCsB6bDtF9hqpsV7FHLOXt83iI8dPjqmer6Z6jD2nSN/Cp6Sqt8Vs7+IVhCeV404iqRxmrFPEMo/b1QMVmpqpJ8Kc5RE3fVRAdqgiHqnKyrdGv0RZjgK8UKXMLjPwPyPrIiKMzzuAgXHhcikK1Pk92YC7KvF01NWB71W9J+kIY3Me9dqOw2ecdpxHpBYoHX2eHVhvE6r77nnLL7hbVh5HEh2RHYk0Lz5CV2L5JEmxlN/+M/SOqYN5uyzvahWdX9jYXDGnzvNYf+p8JW+A62EP0i

RNG Seed: 3838599252

Tried to add new aura in a finalized environment!
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0xffe80, 0x3d8768})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*auraTracker).registerAura(0x3382f30, 0x3382a80, {{0x2999f8, 0xf}, {0x0, 0x0}, {0x16cfb, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/cata/cata/sim/core/aura.go:353 +0x43
github.com/wowsims/cata/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/cata/cata/sim/core/aura.go:393
github.com/wowsims/cata/sim/core.(*Unit).GetOrRegisterAura(0x3382a80, {{0x2999f8, 0xf}, {0x0, 0x0}, {0x16cfb, 0x0, 0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/cata/cat...

**Comment by ToxicKevinFerm** [comment]
Please try a different pet other than Cat while I fix this. They do the same dps anyway.
