### ISSUE TITLE
Scaling not right on some things

### ISSUE THREAD

**Issue by cwilson21** [wowsims/cata#439]
**Describe the bug**
Scaling on various items in the UI are not right, looking at tooltips for different things is like it is 50% of what they maybe should be and the item selection window when you are trying to play with different slots is squished.
**To Reproduce**
1. Go to any page, gear for example.
2. Hover over any piece of gear and notice that tooltips are so small you cannot read them.

1. Go to gear page. 
2. Click on any gear slot and notice the modal/window is squished.

**Expected behavior**
For the gear selection window that pops up I would expect it to be scaled properly. 

For the tooltips, i would also expect them to scale properly so they are readable. 

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.
![image](https://github.com/wowsims/cata/assets/17466712/5e7422ee-7612-415f-8fb0-9c930024e133)
![image](https://github.com/wowsims/cata/assets/17466712/17e37ec9-c1d4-4aeb-8283-aae5b5af1f80)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 124.0.6367.202 (Official Build) (64-bit)

**Additional context**

**Comment by rosenrusinov** [comment]
@cwilson21 can you see if this is still an issue? I can't reproduce the visuals you are getting so it might have been a bug that got fixed already

**Comment by jjayrex** [comment]
I managed to track down the issue. It occurs on a high DPI display. The issue happens if you have 4K, and you set Windows Scaling to 100%. Normally, it should display all of the content at the same scale, however, for some reason, Chrome doesn't. Going further, if you zoom-in, it will actually zoom-out, because it will be set to what a 110% scaling should be.

https://github.com/wowsims/cata/assets/45790781/99b51526-bdad-4cc2-927a-d968d55178f8

**Comment by rosenrusinov** [comment]
@kayla-glick @1337LutZ do we want to action this in any way?

**Comment by 1337LutZ** [comment]
I will adjust the value for 2560/4k screens. I feel you lose the benefit of a big screen by scaling the whole UI proportionally.
![image](https://github.com/wowsims/cata/assets/1216787/5d1dbf46-022f-4046-9ba5-0a9dac6516be)

**Comment by 1337LutZ** [comment]
Tooltips are kinda out of our control since that is a wowhead integration
