### ISSUE TITLE
Bearweaving: Not sure if bug or result of rotation logic

### ISSUE THREAD

**Issue by baelrayneVessdren** [wowsims/cata#443]
Description:
Simed the new bearweaving logic in Duid - DPS and while checking the timeline the sim switched into bear for 1.6 seconds without doing anything. After that it switched back into cat and continued the rotation. Happened during the last minute or so of the simed fight. 
Not a major issue for that particular simulation. Might have larger implications for future simulations.

Reproduce:
Not sure if even reproduceable. Have not checked since Friday, last week. My settings: 
1. P1 preset with changes to professions (Engi+Blacksmith instead of Eng+JC) and added 2 AGI gems
2. Turned of Bleed buffs to check Mangle casts during sim
3. Ran a single iteration from the "Results" tab and checked the timeline

Screenshots / Link:
![image](https://github.com/wowsims/cata/assets/131447339/b5290a84-56d1-4d94-9d7f-cda9493d33f4)

<a href="https://wowsims.github.io/cata/druid/feral/#eJztUk1oE0EU3nmzJumIOIYi2x40GTwspYXNhoLNJduqxYNgKIL15tZOdDU/ZZNoiwgRRdpaUERam0OhClI8eWsVavxtlSKEgAVFhBShFQpF8CAi6Gy2pHq04s23DHzfe9/35u1jyE4fOoXyCF1HaAqhGYTygO4D6oB+5Jcap70F7IklzAFu+zwUNS4h4qfFElY+B1jdvXF5sYQrJUy89MmIrN5CZDsdncPKaoDhL2NYvYEIoY9GZGXB52DhFPhKgHlE0alPIbKNfljDyu0gQ5JDKa0sY2W0gcmiLqkFp+PbB7jmuOp0uSmumNjoctcRLYguq7tr13ppYRk7A3npYzHZuAMur1S1Xjo4g9UhZ7SxGaxcCqrDiEikjn6fxlU/2+oDrSEG3SB20jQLZBCk/1ENv/anjojUIZ2WGyGAHsKuFj2sa2FdD4d0LaQ7n6aHtVCLJrJa6Cns8c0Vgb4ogjL5EQLPy6BOXJO110XYW3gDxnwZDj4rw0uQS+B9B9IS/EAKsG+IVNB51sNN+yg3z3IWydo53sySppXKitNpctvinZa9UbFS+9LJnnSmM213WX0s0trMchneZZ6pSQTtsLI12iPwESspeCj0u99VtbqS/TnbSp080M9P5Da8ttV3iPNz5oAwV71dadM+HI9neJZF9DZn0FTOTMRM20xmaiPyBOe//M4Ffz3xENk3MYQJiNe6flag9yJ2F91mTK6jY8Ywlth7qKuyfNzY4ebrjYbCuBOvom1uphQNxquxGG13S5+i+h0IdCtbmv7xo1eHjM3Y8r3zm/L9TbjLml0z2l3+NXoc/QRWm90v">Link to Sim</a>

Expectations:
None. Only wanted to check the new bearweaving function to encorporate into macro and get some more information on potential windows for weaving

Desktop:
 - OS: MacOS Sonoma 
 - Browser: Google Chrome
 - Version: 124.0.6367.119
 
 EDIT: Did another Sim and encountered the same behaviour. Added link and screenshot

**Comment by Bisonpasfute** [comment]
Did you check that you didn't proc clearcasting on your bear autoattack? Bear autos have a 2.5x higher chance to proc omen clearcasting. If you did proc clearcasting, it's perfectly normal to go back to cat to use that proc.

**Comment by baelrayneVessdren** [comment]
That is a very interesting thought. Checked another few sims for the same occurence and you are right. Found another one and the sim changed back to cat during a clear cast proc.
