### ISSUE TITLE
Crash Report -1976502824

### ISSUE THREAD

**Issue by Yotsutester** [wowsims/cata#446]
Link:
https://wowsims.github.io/cata/death_knight/blood/#eJztVW9sU1UUf+fe1+71boPXy5C3i4y7h9PSOOx7taQsxnbEmEnALOqH6Qdjwwo2dn9kTaaGmKqLXWZCyEygW9QIfnYQ/LBlhBAVEY3oYsYETJBo2CYSNZKYkfDH+/6060YlusRv3i8995zf73fOPefeV7JGgQDE4TnIAuQBfgfoR3AYwQSCiwg2+1WIQgt0wxjAWYAsgiakApXY8WXD2NuaTryc3KVUqoR9D4SqP3yDtV+57juZx2cn8HcTmFSot0Zx4A0gy9Wbo1ib5jq+sR8HBoD41EMzWOvjgd0iNjiCtZyIDeZx4ACQanXPCawN1OlyLo8loqpXxrA2xHVZcCVLbZn69gjWvQJuMXYTv/rnZ1gbqde9Ocf1qhD9VuhfWOuICk6Fen3Mzlyhzs7gwPtWCVdPYTtOZDU3a1W7TyTK1RGJVKkfTDuxwFugVys4tLbV0+Z5CfYCDh5DpB9J/y970dC/ZTRJm6UtMkNEGkfMDBtm2AyFjXDINMVG/BqN4cZQKPwJukf5aAqpeyaR9t4k4kemUGDmEgrtnUTRoTMovv8MaslPolNIFpf1PJJ+RNOKhkkNUZiXyEruGtIVIqzGjaEessL1zv2C9AriIbgxPO/84zh2nUZPkT98usA3QvPek1nseiPC6ydeJhOk+Yt0Ks7VJNE1bDXxB5crXip2zA5GN/XYCvkbiN7HGki1Xkl8R8AVNQsJzv2E5lPR1QqwVYugxaDBHiANdN2iMKFBVZEpPg9u4kiowaZ8fAjT+1mQcFq3mFKyFSgb3XcL0Tp2921qD7pqUzfvHJ+5jmgTi5aLm7p7womriBAm2ql8/SbmUGrTlWxFoaQPj3lsePZ1D93KtpCH2UO2LFDPZUAKYkKWgFnqw2V8susrSRJlG0mQBmyUd4GaUepzmcadmfifMa2plRmRWUsqdR+xt8aGyIJe6OIW1JWd6zyGuwgvxV8WEOIt2YjfjlqIR9kjxJoIC2pCp3pcfLGR6hF9vXzNLTNye2x0xD1WxHlUF2S6jtWTVcGVCqa+cXDflBUkyOwpjr5wNdzeQ6H3VnxgBNMq4VKKF62KlR73Gdb2NzM2yszYKDNjw7yr5DmVahcyOS0hrPgBKNriNMXqPQuqDxWqn0X7YA7Ba9j5ntXED7jW0/EBfK/PNvs/jfsd51xsvWNcjNUWDO7Rf8YOUHq2AKyJ1w4PWeuL2CbHMxGr32GvqVjz6a+sdSVmHsbdl06gVyq3JXZ2JHq5GeEtvE2D4H/8l9TaF18KLdv++VJ4W6PvvtO8lHzWsruXPehrHgKnoedirpYcH4QXxWWpeayjO5FO8ieSie2ZVFcnfyrVkQw+3tLVy9NdnTt5byqd5pnnBSCRaueZxAtJnuniLqklmWjnqU7+ZHJ7V2d7zwYeaN6RSe6y8anOVCaVSHPxn7G+3slZE/8LFctZvg==

RNG Seed: 3225119170

Wrong APL controllingAction in pop()
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x100060, 0x3d8eb8})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*APLRotation).popControllingA...

**Comment by rosenrusinov** [comment]
The provided RNG Seed in combination with this action seems to be what causes the crash to happen.

![image](https://github.com/wowsims/cata/assets/5707996/8a5dab56-7b05-47a2-9294-04b7bab83b50)

I'm not entirely sure yet why it crashes with this action and this seed specifically. For now I would suggest you to disable this strict sequence with a wait in it. Strict sequences are suited for chaining multiple Non GCD actions and they dont really work well with waits and gcd bound actions.
