### ISSUE TITLE
Crash Report 2121836889

### ISSUE THREAD

**Issue by Faramitas** [wowsims/cata#459]
Link:
https://wowsims.github.io/cata/shaman/restoration/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYndg5gIqAXCEGqZXMs5jZAnISK1OLOJgF2KWUuBgIQSU2DjYDxgAerb1MXB1MDKMADIQMSNVhxeDEVMDYxMQmxcLFxMF4iInhBBPLBSb2W0wMj5iYJBhfMKUsZIYojXToYmZQusPECeY1pDkIQsRFHCRnzQSBk/aWEJEL9oppYHDN3vHsGRB4Y2+0mEkhQoJVi8aRpdHpQI62hpTjZOmjBEACa+97B0cI/4d9AqMHJwAViDS6

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1000c0, 0x3da1b0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x334a000)
	/home/runner/work/cata/cata/sim/core/unit.go:518 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x334a000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x31f06c0, 0x305ce80, 0x3302280, 0x32c8dc0, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x305ce80, 0x3302280, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x304d900)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x301c700, 0x1, 0x1})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.9/x64/src/syscall/js/func.go:100 +0x26

**Comment by kayla-glick** [comment]
The resto shaman sim is non-functional right now and that's expected
