### ISSUE TITLE
Crash Report 34222232

### ISSUE THREAD

**Issue by Yotsutester** [wowsims/cata#468]
Link:
https://wowsims.github.io/cata/death_knight/blood/#eJztVG1oW1UYvu85N9ntyWpvzrqZHl13ezEuC1RubmzJipjbKlI/Jt0muCEMY5vNYJrUNlIsOLIxbC0oo/5YWnSsY/+EOhRxVETc5nTDSYWuuKK1KHNjEycOpdW189yPZNc1f6z4RzyE3Pc87/O85/0495K1EoTAgKchD1AA+BlgAMFRBBMIZhG0+GWIQSt0wTGArwDyCJqQDFRgY5Uj2NuWTryY7JZ8MmG/A/HLhxdw4CdF9Z4q4P4CDu0mPvnEFFatTR+5TT7C/T8oKl44YDor5N9GxcAZwl1UPsRd/VzKXUOcvQeILJ+cwoHBWlXkgBB63URGOWtYcZB9QGrk6UWsHVy8YS8o6V8iVfJBTh6rU718z388vU94vJl1Jc5uDn3N5fkbRTmXrZSPmxmb/iEgoly4jvl//yVMiHzlD55jrZmJwCs7Mu/w+lSfhLV1bZ5tnv2Awx8iMoCE/5e1qPZ3FU1Ci/CIyBARxhHTolFd1zUtYj70aIQ/I/XRek2LHkd3Se9OIfm1SRQ4OImUVydR6OIFpO2fRLHhc8g4cA61FibRZ0jkN3kaCd+hYysCmFQTiXmJKPXPI1Ui3Kpv1HpK6Kk8dtAGFzpytsiNcHSVg85dQeoK4iG4PnoT/OUj7ICRHuInXiYSFPCXIMrrahLoWnYH8YerJC/lO2Y5Yxt7rACFBUQfYg+SJhYjLByQRFo5DoQi2cOdl+dFxrkEIkt9749hx2fXNyPS9SxIKlUfqXgHnOL0Yknnv0c3S6a17E5CwzIPiKfBSahRC1r+j9/GdDVbVQzCtxac3+txw29d9Vjw1CKiURYh62lwScQGLUiq1EriGwHeTemLl7EClmjiGqJPse1kE3vUEgH1XAYkIbse3Y1hN3ZrcFet334jstIhVGG1lsBL8ZmiIKJrFuPqByYjyzrJVrqZ3M/uK5NCpEwKf8FKY7m1Pn2Nq+HEldJK5t41sntJmIaWVBXTgu5jwKm+1GrXBH7ld8N8fnkdleZZTjY4hukzHNpBttA2pytuVqRM/VqZ+rUy9bs7GuQB68jt4dUSphXj4LwxZgoE6fZdv8hTLfbBFnG7+BqVbK66hGbQHII92P5CVBujjrXdGMR3V1jmwAnDb4Nz8Q22MRuvKRqKR33PaxOFHUVitVEzMmyu0/GNNjIRr9tpral489nPzfVjXD+Kuy6cRH2+TYldnYleRW9QWpVtAQj/yx/5tn3GcmT5jk+Xo3ss9uYbzcs5z1xW9/KHK5qHwW7o+bgTSzSG4Hl+S6of7uxKpJPKlmSiPZfKZpQnUp3J8OOt2V4lnc3sUnpT6bSSe5YTEqkOJZd4Lqnksoojak0mOpRURtmabM9mOnruUULNO3PJboufyqRyqURa4V/mDXX2mdWGfhp1vbIX961pSSf6Ujz8A9lMT677hfacPb0n/2vTEwbCm//Z9ISBa8Yw2MBscXqCocGfZXxxVw==

RNG Seed: 2022067270

When validating reforging for item 69878, the reforging could not be validated. 122
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x100220, 0x32e9a80})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsim...

**Comment by 1337LutZ** [comment]
Closing this issue as this was fixed a while ago. Fixing it in the gear picker and creating a new export link will fix this.
