### ISSUE TITLE
[Cata] DoT + Haste mechanic

### ISSUE THREAD

**Issue by InDebt** [wowsims/cata#50]
## DoT and Haste mechanics in Cata

This issue is primarily design for documentation. I have gathered some sources and references for implementing the DoT and haste mechanics regarding DoTs in Cataclysm, that putting all of them into the source code as reference might be too much.

**So what changes wicht cataclysm?**

* Any **DoT** that is reapplied to a target will not reset the tick timer refresh the duration and keep the tick timer rolling
  * Player hastened DoTs: https://cynwise.wordpress.com/2010/10/29/how-warlock-dots-work-in-cataclysm/
  * Player HoTs: https://typehforheals.com/2010/09/23/cataclysm-beta-haste-and-hots-a-quick-example/
  * Non hastened DoTs: https://youtu.be/VMK_huoSnVQ?si=Au9pfHNPkcgTBqvk&t=215
    * Serpent sting is not affected by haste, on refresh the total duration exceeds it's baseline of 15 seconds
 * To account for the remaining tick time to the next tick, the total duration of the repsectiv Aura will be extended by the remaining tick time

The moving parts of the DoT/HoT can be computed like this. Given the spell is affected by haste. For non-haste DoTs Player_TotalHaste simply is 1.

![DoT Aura calculations](https://latex.codecogs.com/png.image?\dpi{110}\bg{white}tickLength=\frac{Duration_{base}}{Player_{totalHaste}}\newline\newline\left|ticks\right|=\left\lfloor{\frac{Duration_{base}}{tickLength}&plus;0.5}\right\rfloor\newline\newline&space;Duration_{total}=tickLength*\left|ticks\right|&plus;time_{nextTick})

## Snapshotting

Snapshotting has changed drastically in comparison to Wrath. 
* Target damage debuffs (i.E. 8% spelldamage) update dynamically and are no longer snapshot
* Player damage mods (% damage done) now update on refresh. `Shadow Word: Pain` and Warlock's `Corruption` should profit from this.
* Critical strike chance is no longer snapshot on apply
  * > One miscellaneous point of mechanics that people should understand: DoT's read their spellpower and haste values, and any %damage buffs, at the moment they are cast. These do not update while the DoT is ticking. Crit chance and target debuffs, however, do update dynamically.
  *  [Elitest Jerks Balance Forum](http://web.archive.org/web/20110207210200/http://elitistjerks.com/f47/t66856-druid_balance_pve_updated_cataclysm_release/)
* The next tick that gets carried over when refreshing a DoT or HoT is already subject to the new snapshot
  *  [Example for Devouring Plague](https://youtu.be/hbmtLM3xBsI?si=5IHkechVubGqQStF&t=43)

### To research
* There are some mentions of channeled spells being affected by the same logic.
* There are however also contradicting statements that clarify this does not work. Need to test as soon as it's properly implemented on beta
* it would be lovely if someone can verify as soon as it's implemented that crit is indeed no longer snapshotted

**Comment by rosenrusinov** [comment]
@InDebt anything else left on this issue or can we close it?

**Comment by InDebt** [comment]
Well we have good understanding on how things should work right now. The only thing missing is blizzard actually implementing things like they should. So in theory we have everything imlemented as it 'should be'. It just does not align with current beta as stuff like dot roll over is not working yet..

**Comment by InDebt** [comment]
With build 54501 pushed to live, our implementation now seems to match the live version. We might discover some edge cases but I'll close this one for now.
