### ISSUE TITLE
Crash Report 539553728

### ISSUE THREAD

**Issue by danial1412** [wowsims/cata#512]
Link:
https://wowsims.github.io/cata/priest/discipline/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnYQFGC0YPRgjgMo2gGWBUkIMUutYZjGzBeQkVqYWcbAKsEptZOTiFtg+gVnijawSEwMDF7vAkh5mJUYGLi6BnUDRR7IQ9pFuZokuMJtDYPcEZrBSboHbQNE5QlDODqDyKTJgDqfA1m5mJWYGIJNHoK2HWaJdFsLjFugG8v4rQK160Q22il3gXieYwSKwppMZSO4FklwC64BKf8lCxOf3MAOV/QGrV+LgYDNgDGCJYNFay8T1g5FhhAIhA1J1WDE4MRUwHmJkk2LhYuJgPMTEcIKJ5QIT9y0mhkdMTBKML5hSPjClLGSGqI506GJmUDrDxAnmNaQ5CELERRwkZ80EgZP2lhCRC/aKaWBwzd7x7BkQeGNvNJlJIUKCVYvG8aPR6UCK8oaU4ySppwRAAmfvewdHCP+HfQKjBycAdv1btg==

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x102ea0, 0x3e20c8})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x33e0000)
	/home/runner/work/cata/cata/sim/core/unit.go:516 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x33e0000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x32d0c60, 0x305ce80, 0x3355080, 0x3368400, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x305ce80, 0x3355080, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x304d980)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x31bca80, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by kayla-glick** [comment]
The priest sim hasn't been worked on at all yet
