### ISSUE TITLE
Warrior simulations end with an error 

### ISSUE THREAD

**Issue by Skorp88** [wowsims/cata#517]
**Describe the bug**
Every time I run a simulation on either the fury or arms warrior sims the sim finishes (or apperas to finish the iterations) and then comes up with an error that says "Something went wrong running your raid sim. Reload the page and try again."

**To Reproduce**
1. Go to 'https://wowsims.github.io/cata/warrior/arms/' OR 'https://wowsims.github.io/cata/warrior/fury/'
2. select any tab 
3. click run sim
4. See error in bottom right 

**Expected behavior**
the simulation finishes and the dps output is displayed in teh bar on the right with the usual save reference options, results tab display results of which abilites were used and how much damage and dps they did

**Sim Links and Screenshots**
https://i.imgur.com/H0NG6fO.jpeg

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome 
 - Version 124.0.6367.210 (Official Build) (64-bit)

**Comment by Solo-Wolo** [comment]
I believe this issue is tied to selecting Blood Elf as the race; other races appear to function fine.
