### ISSUE TITLE
Warlock Demonology SIM uses both pets when only one defined

### ISSUE THREAD

**Issue by dubl3a** [wowsims/cata#518]
**Describe the bug**
When checking the sim, I found that it lists DMG from both a Felgaurd AND Felhunter.  But, only one is possible at a time.  I even see they are BOTH doing dmg throughout the SIM timeline.

**To Reproduce**
1. Setup gear and
2. Settings shows Felguard

**Expected behavior**
Results should only show dmg done by Felgaurd

**Sim Links and Screenshots**
https://wowsims.github.io/cata/warlock/demonology/#eJzlUr9LHEEU3vdm9lxHg+NBYDwMrksEEQJ7e42mcFcrSyu5MgFzpLCQdOnurM5oYRT81V1nQMEuKgiiiT+4C2yM6EUTFPVwC+VshBMxZPY2/8AhqfyKj/e+73vzYGZYiwYcHHgLg5AGmAaYA1gDyAN4AEmENMIiQnc9hx6Iy9Bi2ZNGWImMqrMk1Dvw+v2bd5rKtcgqsDBfdoko6kb1/AwtuCTvEka5e0FYLf+1T4SnG6Q4RVgV/75JxITO6viRlEvPjJCUb6XD+NclIjLNBijsCc9Lc0Q3qDQVmb34RMTHxnLWP6WOH0p/TDdCV4FQy2+2iUj/W0J5btPn9J3PKc/n43N/+V6GipQui40vRNw1Sd37TIwaTTWf9tI4HQNoW0BWAuWRImxWOvFS6VYH/a8xjiFGGWrqCkZexGJRSyJmmrGoack6GpWaZVrr+Fw7ySI/yKLYK6B+lsXWnwU0fxew/c8uOkM/sOd+F7eRulhziMopogAP+69xElIkWNnhZIIq2ed8IIqRw+qgTTj1QaLTaZid8bFjdwSKazcnyti3u77lfFza1gTqcaG2/efnbh12Kokn+7cqyj8EweWsFp2uoC/Zr+AvwiqOpg==

**Desktop (please complete the following information):**
 - OS: Fedora, Windows 11 23H2, and Ubuntu
 - Browser:  Attempted with Chrome and Firefox
 - Version: Most up to date versions

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: Android
 - Browser: Chrome & Firefox

**Comment by Tharre** [comment]
The APL switches to felhunter on prepull; that is how demo is played and not a bug.
The bug here is specifically that when you're summoning felguard during the prepull actions, it will not correctly despawn the old felguard.

So it works correctly if you just don't summon felguard (again) during prepull actions.
