### ISSUE TITLE
Hunter talent - Pathing - Not showing up in the stats menu but does increse dps

### ISSUE THREAD

**Issue by Agatigithub** [wowsims/cata#524]
Hunter talent - Pathing - Not showing up in the stats menu but does increse dps.

Just cosmetic, but could be misleading to players who don't realize it trying to hit the 20% haste "softcap".

**Comment by rosenrusinov** [comment]
@ToxicKevinFerm did we fix this already? I remember you mentioning something about it

**Comment by ToxicKevinFerm** [comment]
Sorry yeah it's fixed. When Cata released it wasn't present in the stat screen so I didn't have it either, but it's added now since blizzard changed it. 
Closing this
