### ISSUE TITLE
SIm not working properly

### ISSUE THREAD

**Issue by tygrwood** [wowsims/cata#525]
I copy my info from the sims exporter and import it onto wow sims- cata. I get the message that its been accepted and brings up my info but the only slots I can click on to review item options are the trinkets. So for me to see if a copy new pieces of gear are upgrades is to equip them rerun exporter, import again onto the sims and run sims. Never had this problem in the last tier. I have a horde rogue.
If I just pull up the site and don't import my set up I can click on the slots and I can choose item options

**Comment by tygrwood** [comment]
![image](https://github.com/wowsims/cata/assets/170813545/6cfaa85b-8afa-44a3-b7e0-bd4638e36943)
here is a picture

**Comment by Tharre** [comment]
Post what you're trying to import please, but I'm pretty sure this happens because you're trying to import something that's not in the sim (and is wrongly imported anyway).

**Comment by tygrwood** [comment]
I am trying to import the chain below as I always have throughout wrath from the add on: When I click on the add on it gives me this below and I paste onto wowsims cata. Not sure what I am doing wrong.

{"talents":"0333230013122110321-0030000000000000000-2030020000000000000","glyphs":{"minor":[{"spellID":58038},{"spellID":58039},{"spellID":58033}],"prime":[{"spellID":63249},{"spellID":63268},{"spellID":56801}],"major":[{"spellID":56804},{"spellID":63256},{"spellID":63254}]},"class":"rogue","unit":"player","race":"Troll","name":"Tygrwood","gear":{"items":[{"id":66936,"gems":[68778,52204],"reforging":154},{"id":52314,"gems":[],"reforging":168,"random_suffix":-136},{"id":66905,"gems":[],"reforging":153},{"id":56518,"gems":[],"reforging":168},{"id":62374,"gems":[52212,52220],"reforging":168,"enchant":3832},{"id":50670,"gems":[40159],"reforging":153,"enchant":3845},{"id":67234,"gems":[],"reforging":168},{"id":50707,"gems":[40114,40114,40114],"reforging":153},{"enchant":4122,"random_suffix":-133,"id":56513,"gems":[],"reforging":146},{"id":50607,"gems":[40159,40159],"reforging":146},{"id":55994,"gems":[],"reforging":168},{"id":56120,"gems":[],"reforging":146,"enchant":4079},{"id":55266,"gems":[]},{"id":55795,"gems":[],"reforging":139},{"id":55870,"gems":[],"reforging":168,"enchant":3789},{"id":66968,"gems":[],"enchant":3789},{"id":63795,"gems":[]}]},"professions":[{"name":"Enchanting","level":525},{"name":"Engineering","level":525}],"level":85,"spec":"assassination","realm":"Whitemane"}

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by tygrwood** [comment]
***@***.***
From this add on:


***@***.***
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Tharre** [comment]
I can't reproduce your problem, try resetting to defaults and see if the problem persists.

**Comment by rosenrusinov** [comment]
@tygrwood I've tried importing from the addon string you pasted above and it works fine for me. As Tharre mentioned can you try restoring defaults (top left cogwheel button opens a menu with Restore Defaults button) then try importing it again?

**Comment by 1337LutZ** [comment]
@tygrwood I closed this issue for now due to no response for the past 2 weeks. 
Please open a new Issue / ask in Discord if you still encounter this after doing the previous mentioned suggestions.
