### ISSUE TITLE
Crash Report -1522447497

### ISSUE THREAD

**Issue by tthouvenot** [wowsims/cata#526]
Link:
https://wowsims.github.io/cata/shaman/restoration/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYndg5gIqAXCEGqZnMs5jZAnISK1OLONgF2KWUuBgIQSU2DjYDxgAerbVMXD8YGUYoEDIgVYcVgxNTAWMTE5sUCxcTB+MhJoYTTCwXmNhvMTE8YmKSYHzBlLKQGaI00qGLmUHpDBMnmNeQ5iAIERdxkJw1EwRO2ltCRC7YK6aBwTV7x7NnQOCNvdFkJoUICVYtGkeORqcDKcobUo6TpJ4SAAmcve8dHCH8H/YJjB6cAExINVw=

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x102ea0, 0x3e2228})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x334c000)
	/home/runner/work/cata/cata/sim/core/unit.go:516 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x334c000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x3314000, 0x305ce80, 0x32fc280, 0x32bce40, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x305ce80, 0x32fc280, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x304d980)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x31bca80, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by Tharre** [comment]
Restoration shaman sim is not released yet.
