### ISSUE TITLE
Cataclysm PVP Set Bonuses

### ISSUE THREAD

**Issue by ToilettHD** [wowsims/cata#528]
**Describe the bug**
pvp 2 set doesnt seem to be working, doesnt give the 70 agi

**Comment by ToilettHD** [comment]
bloodthirsty dragonscale
![image](https://github.com/wowsims/cata/assets/135880636/5cc800cd-fb40-4757-8a85-ed880a8a628d) 
viscious glad 2 set
![image](https://github.com/wowsims/cata/assets/135880636/c55bfd01-a121-4b32-988b-c6536ec812d4)

**Comment by rosenrusinov** [comment]
We dont have any of the PVP sets added atm. I'm leaving this issue open to track that task
