### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by ablib2** [wowsims/cata#531]
Links to [Cataclysm Wowhead](https://wowhead.com/cata/items "https://wowhead.com/cata/items") for each item:

I'm starting to think....what IS there to choose from, instead of what is missing.

https://www.wowhead.com/cata/item=57353/calcified-gizzard
https://www.wowhead.com/cata/item=50468/drape-of-the-violet-tower
https://www.wowhead.com/cata/item=47603/merlins-robe
https://www.wowhead.com/cata/item=47585/bejeweled-wizards-bracers
https://www.wowhead.com/cata/item=57337/heraldcall-censer
https://www.wowhead.com/cata/item=40682/sundial-of-the-exiled
https://www.wowhead.com/cata/item=57346/mindfletcher-talisman
https://www.wowhead.com/cata/item=211844/the-horsemans-seal
https://www.wowhead.com/cata/item=57322/signet-of-nascent-fire
https://www.wowhead.com/cata/item=57319/lightheart-sandals
https://www.wowhead.com/cata/item=57379/clutches-of-the-worgen-spirit

**Comment by Tharre** [comment]
We don't include items below ilvl 272 right now (with some exceptions) so you won't find any of those.

**Comment by kayla-glick** [comment]
> We don't include items below ilvl 272 right now (with some exceptions) so you won't find any of those.
Just to add onto this, the reason we don't is for our Database size and setting reasonable boundaries of what people will/won't use at lvl 85. Realistically all ICC / Wrath gear should be replaced by 85 / during the dungeon grind, so that's why we've chosen not to include them.

**Comment by ablib2** [comment]
Thank you for the reply.  Makes sense.
