### ISSUE TITLE
Crash Report 968922160 / Balance druid Sim problem / error

### ISSUE THREAD

**Issue by Svekken** [wowsims/cata#535]
Link:
https://wowsims.github.io/cata/druid/balance/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnYQFGC0YPRgjgMo2gGWBUkIMUqtYZjGzBeQkVqYWcXAKMEpVcrEI/L7PDCSfrweRrzaDyIUPQOQqIMkuMO8BsxIjA5Axp4kFwrh6HyzCIjAZrKxzC4g8AtTOL/BrA7PB7f9QwAgUfrmLBWQqmGxvYuEC6f+9B2SQEgcHq4FoAEsEi9ZaJq4fjAwjFAgZkKrDisGJqYAxiU2KhYuJi2EXk4yxsREQGRkaGhkbGRoYGhoaGBvq6hoYGRgbGB5iEuC4vZ9J4Pp+Jokr+5kUbu5nOsHEcoGJ+xYTwyMmJgnGF0wpjcwQg40cFkJZkQ5dzAxKZ5g4wbyGNAdBiLiIg+SsmSBw0t4SInLBXjENDK7ZO549AwJv7I0mMylESLBq0ThSNTodSFHekHKcJPWUAEjg7H3v4Ajh/7BPYAQAOB9psw==

RNG Seed: 2105251032

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 25 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x139b40, 0x1c52c60})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/druid.(*Druid).registerStarfireSpell.func1(0x38179e0, 0x387b800, 0x3901180)
	/home/runner/work/cata/cata/sim/druid/starfire.go:22 +0x17
github.com/wowsims/cata/sim/core.(*Spell).applyEffects(0x3901180, 0x38179e0, 0x387b800)
	/home/runner/work/cata/cata/sim/core/spell.go:571 +0x13
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFuncSimple.func5(0x38179e0, 0x387b800)
	/home/runner/work/cata/cata/sim/core/cast.go:236 +0x2e
github.com/wowsims/cata/sim/core.(*Spell).Cast(0x3901180, 0x38179e0, 0x387b800)
	/home/runner/work/cata/cata/sim/core/spell.go:547 +0x1d
github.com/wowsims/cata/sim/druid.(*Druid).registerStarfireSpell.func2(0x38179e0, 0x387b800, 0x3901400)
	/home/runner/work/cata/cata/sim/druid/starfire.go:67 +0x22
github.com/wowsims/cata/sim/core.(*Spell).applyEffects(0x3901400, 0x38179e0, 0x387b800)
	/home/runner/work/cata/cata/sim/core/spell.go:571 +0x13
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFunc....

**Comment by stn-ms** [comment]
I will take care of this. In the meantime you can remove glyph of starfire - you shouldn't need to use that anyway.
