### ISSUE TITLE
Crash Report 742175569

### ISSUE THREAD

**Issue by mathwro** [wowsims/cata#541]
Link:
https://wowsims.github.io/cata/druid/balance/#eJzlVV9oHEUY329m7zL7XU33Js25nSK5rmk9N17Y3WslOYS7FCt9EK34En1SaYsEH0oDoi9yRS2JkBAVbHoWRZ/UWloC1bRQTiL4ByweQW0TxbQlbVIQglawtkKd2b1/jbHamoeC38PMN7/5fd9+f2ZmcR0DE/LwNOyEAYBRgPcAPgE4BTAPUCAwQOAwgU0tJnTBFuiVtMPBrtzimhiNF2l06zNPPr99FzNMEIcAuXm8TK2FpG18uE8/WabzZYq6WZ6jaJjvj1ObLuyl2GT+Mk6tQhJXmD8fpdZMWwijeeFjap1ps0GT+rBk6xLWJOubOWpHpa5YK839n1FrKGlHT+ylv75B5fbBId06V3GimwNX1Dgyp8aZWTUOH1XfvPAbtS62oSYjubogI5HmdoxF3Nateq8+AuAcJHgJtP+pcPdGLbLaJrITnooKHQlqx0hPJuNnfN/3PDl5cvJc10u7vruEKDjjeovQCdLOpkvEPFki1vclkjxVIqmPZok7VSJdl38k+eK3ZMunk+QLAmWiTxPtLPkjZlFsRSaiqLMDRyK2gU0YSW/ozPQvAWc6/aVgv9PrxzgGiVhxW0JI0xJqqTAnz+s1kK8X7Wg6zSzCSVZT20g29gsTm9lgInm1KsAtkUDumAw4fVfXRGAv881qPCu6sJPfs9QuJpxVEjMmoBKhkDhCJgjj0JEIfwnEbsDn+LOYEuvxdqeVUd7UJ0lsokOwoh5qGFOZ+ZVFO7fxNjuGxljg9eUrBOPOSmkYfDrIoLt7MWtPnfVBnSVCl3wGxA+Ak8C/BiyAeAEdnsI1zmpJN/pkMmxqcxIEFvWqjoZfU9fytvBLdajZXoHoM4yy6amIXKd5B97hrJHusK+GilhRr1Ma6cud4dRm/oh4GB/g999AmVXDG1zXY6kW7S0QbwK+Cnz4lihaPdZqzm+D2H/rBagqqGYJ8teAgRgCfBF4AfBesQHXOXc29iYxRlrkutai8P5413ZK9fVvuxV0fPHp8Tb+5aj4brWvoyqo1wEHge8BvE9k8W7nrmtrZo0RdYQaSlcNbFHJljM02dG06Agao56aaMioPTUN/Vfz75cJf1z04kP8wWW9T5UHlLcL+zpXpMoyRTNGxnTCwkM5nqojNEBOJ7ghmirqPNm2m4Y/Iz//TkV7LP8K1exZYgSrwo58PMRX5VcX9yn5MtcdIuXc2h2BfJfrOfGVkp9y/gGS7LUizgj5z3/U60lqMH8zZoVtn/+D3aM35fffSFi04wv5nnB9KfcE/AmDAnps

RNG Seed: 674008286

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x139b40, 0x1c52c60})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Dot).TickPeriod(...)
	/home/runner/work/cata/cata/sim/core/dot.go:68
github.com/wowsims/cata/sim/druid.(*Druid).applyOmenOfClarity.func7(0x30491e0, 0x33ff8c0, 0x397ef00, 0x3...

**Comment by 1337LutZ** [comment]
Seems to be related to the Hurricane enchant.
