### ISSUE TITLE
Crash Report 629687622 (hurricane enchant)

### ISSUE THREAD

**Issue by lutoriollc** [wowsims/cata#546]
Link:
https://wowsims.github.io/cata/druid/balance/#eJzlUj1oFEEU3vfe3mVv/Ml4KowH4dZFYQkEZnebaLN7qVKmPDuVGCwsglZ2ZxeDCUaFyx022mhh4AoxRggrKkYlwSUkJsZCkMhdIZwmzTUBZ3etxOYQK79m5vt5Mx/DsJMGcAjgIozDBMAswEOA5wCbAC2ACsIEQgNh6DCHQRiGsoo1EldZea0QZuqUHbl07uqFy0aOQ2ENWJ4vRiTappV7VNM3ItqMiPXwqEn2FLD9/FWTRMu0aKYayztPSUz2sV7+Y4FEp8+idjXJMf7uMYm9ogUaO8DnmmTpjSpp9n1gB/maotnv1SR7Rd139zWJW6aVVfzGLMWZXr4+T+JrMT3vJqibdufJfgAsx2f2KJGVNr1A9p3Y/LydmD38vRrbLTJNFa3tUNJS1bEMIyOPjuhlvX8OWQe0/xR52e3EaW0Ix+F8tqAzZNozLHme60nXdRzXcx3pqFU6A9KRf8CAdKXn/W69wBPGRoh8K0TxKURzJUT7yTbKjyEOLq1iUF/H4Zer+Ab1CPdtofYFUUALR69R2sgN7v3anQkmSbOWMZewylhwKNWPBMfqtRhv/VOpEvnHxxJ88EsryzG++e5tNMsi0/+Pf4N9PegmXhld6ir/N0gfZ7EdlFLe8c/CTz4Plg0=

RNG Seed: 42

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x139b40, 0x1c52c60})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Dot).TickPeriod(...)
	/home/runner/work/cata/cata/sim/core/dot.go:68
github.com/wowsims/cata/sim/druid.(*Druid).applyOmenOfClarity.func7(0x38ff520, 0x307cb40, 0x3820780, 0x3820938)
	/home/runner/work/cata/cata/sim/druid/omen_of_clarity.go:86 +0x23
github.com/wowsims/cata/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/cata/cata/sim/core/aura.go:803
github.com/wowsims/cata/sim/core.(*Spell).dealDamageInternal(0x3820780, 0x307cb40, 0x0, 0x3820938)
	/home/runner/work/cata/cata/sim/core/spell_result.go:305 +0x9a
github.com/wowsims/cata/sim/core.(*Spell).DealDamage(...)
	/home/runner/work/cata/cata/sim/core/spell_result.go:313
github.com/wowsims/cata/sim/core.(*Spell).CalcAndDealDamage(0x3820780, 0x307cb40, 0x3368000, 0x40742a0796673518, 0x393fb78)
	/home/runner/work/cata/cata/sim/core/spell...

**Comment by stn-ms** [comment]
I got this.

It's the hurricane enchant aura that clashes with the druid spell that also applies an aura with the same name.
