### ISSUE TITLE
Crash Report -1951538681

### ISSUE THREAD

**Issue by Necrotic416** [wowsims/cata#553]
Link:
https://wowsims.github.io/cata/paladin/holy/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYndhBioBcIQapA8yzmNkCchIrU4s4WAVYpEy5OAT+HGVWYmJg4GIRuPCcmYtdoGsHsxIjAxceqMTGwWbAGMChtZaJ6wcjwwgFQgak6rBicGIqYFzFyCHFJsTCwSTBdIiJ4QQTywUm9ltMDI+YmCQYXzClLGSGKI506GIW4gwFgfl7HQQhgkwOSmeYOMHMhjSYoIiD5KyZIHDS3hIicsFeMQ0Mrtk7nj0DAm/sjSYzKURIsGrROMI0Oh1IUd6Qcpwk9ZQASODsfe/gCOH/sE9g9OAEABtePuU=

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1033e0, 0x3e3578})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x3818000)
	/home/runner/work/cata/cata/sim/core/unit.go:516 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x3818000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x33f2900, 0x3397080, 0x3397180, 0x33ef140, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x3397080, 0x3397180, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x33eed00)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x33e95f0, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by Tharre** [comment]
The Holy paladin sim is not released yet.

**Comment by Necrotic416** [comment]
That would make since why then, thank you


Sent from Yahoo Mail for iPhone


On Tuesday, May 28, 2024, 07:31, Tharre ***@***.***> wrote:




The Holy paladin sim is not released yet.
