### ISSUE TITLE
Crash Report -196797633

### ISSUE THREAD

**Issue by Kaninchenbun** [wowsims/cata#559]
Link:
https://wowsims.github.io/cata/druid/restoration/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnYQFGC0YPRgjgMo2gGWBUkIMUsuYZzGzBeQkVqYWcbAJMEqpcbEIdH9i5mLAD5XYONgMGAM4tNYycf1gZBihQMiAVB1WDE5MBYxFbFIsXExcDIeYGE4wsVxgYr/FxPCIiUmC8QVTSiMzRKWRw0IoK9Khi5lB6QwTJ5jXkOYgCBEXcZCcNRMETtpbQkQu2CumgcE1e8ezZ0Dgjb3RZCaFCAlWLRrHkkanAynKG1KOk6SeEgAJnL3vHRwh/B/2CYwenACrNzqG

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x104120, 0x3e6f98})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x3818000)
	/home/runner/work/cata/cata/sim/core/unit.go:516 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x3818000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x33ed0e0, 0x33f0600, 0x33f1200, 0x33eb600, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x33f0600, 0x33f1200, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x33eaec0)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x33e7500, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by rosenrusinov** [comment]
![image](https://github.com/wowsims/cata/assets/5707996/87f8caa9-814b-4ae8-98fe-e7cccaac63f7)
