### ISSUE TITLE
Arms Export Not pulling Hit

### ISSUE THREAD

**Issue by Shuttlestomp** [wowsims/cata#561]
Siming Cata Arms warrior. The export for pawn is not pulling hit stat weight. I am using Chrome. Other specs are exporting all stat weights. Just Arms warrior isn't pulling Hit. See below string:

( Pawn: v1: "Arms WoWSims Weights": Class=Warrior,Strength=2.210,Agility=0.880,Ap=1.000,CritRating=1.130,HasteRating=0.530,ExpertiseRating=1.080,MasteryRating=0.530,MeleeDps=9.270 )

**Comment by rosenrusinov** [comment]
Are you sure you didnt sim with hit above the cap already so the weight just got calculated at 0?

**Comment by Shuttlestomp** [comment]
That nay have been it. I thought I was under but could have been mistaken. I’ll try a sim purposely under cap and see if it’s still the same.Thanks Sent from my iPhoneOn May 29, 2024, at 1:38 PM, rosenrusinov ***@***.***> wrote:﻿
Are you sure you didnt sim with hit above the cap already so the weight just got calculated at 0?

**Comment by 1337LutZ** [comment]
@Shuttlestomp I am closing this issue, please make a new report if this still isn't fixed in the meantime.
Make sure to be more at least 40 points under the cap.
