### ISSUE TITLE
Mastery being rated as 0.00 for demo warlock

### ISSUE THREAD

**Issue by IOEggception** [wowsims/cata#576]
**Describe the bug**
Sometimes when i go to calculate stat weights, mastery will calculate to 0.00 for my Demonology warlock spec.  Sometimes it will have a weight similar to haste, a little under, but other times its 0.00 which doesnt seem right... unless theres a cap that i dont know about.

**To Reproduce**
Using this import string "from addon":
**{"talents":"000000000000000000-3312212300311212211-3320200000000000000","glyphs":{"minor":[{"spellID":58079},{"spellID":58094},{"spellID":58070}],"prime":[{"spellID":56218},{"spellID":56228},{"spellID":63303}],"major":[{"spellID":56240},{"spellID":63320},{"spellID":63312}]},"class":"warlock","unit":"player","race":"Orc","name":"Dothappy","gear":{"items":[{"id":59449,"gems":[68780,59479,59493],"enchant":4207},{"id":57933,"gems":[],"reforging":167},{"id":66910,"gems":[],"reforging":165,"enchant":4199},{"id":62357,"gems":[],"reforging":144,"enchant":4115},{"id":60251,"gems":[52207,52235],"reforging":144},{"id":64723,"gems":[]},{"id":62364,"gems":[52235],"reforging":165},{"id":57921,"gems":[52235,52207],"reforging":144},{"id":56375,"gems":[52207,52207],"reforging":115,"enchant":4113},{"id":56436,"gems":[],"reforging":115,"enchant":4092},{"id":62352,"gems":[],"reforging":144},{"id":65169,"gems":[52207],"reforging":167},{"id":55810,"gems":[],"reforging":165},{"id":62047,"gems":[],"reforging":165},{"id":56461,"gems":[],"reforging":144,"enchant":3854},null,{"id":55823,"gems":[],"reforging":144}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"demonology","realm":"Mankrik"}**

**Expected behavior**
some sort of weight for mastery

**Sim Links and Screenshots**
https://wowsims.github.io/cata/warlock/demonology/#eJzlkj9IHFEQxndmdm/3ngm+OwisFmazEFiEwO5eoxbZ1SqllVxpQCVFCkmqdBcrY4iein9Jk0K0SMBCUAOCimDCebBo0GjIH5IcZxG4FCkMRMh7u1VIdYRUftU33/xmGB6PXTeAQwh3YBCGAWYBlgA2Ad4CnAIUEIYRlhG6MhxuQV5Ay3FPNLJK85o2T6nuu7cf9N8zdG40l4Fl+XpEZs2y08/n1KOIKhExnZd3yFkExviHEdWsWs6C9FNVMictpwiskb87JDtVm6HHsyQDnR/8JBsUdpk/rZKtiliRQ418a0eAohSsBDN8dY3McSseltl9luY/RPTrqrA6L1Zj7BIfPyc7Bhbl9qEVkut0/vErJcc8WSdztEWyiojHVuSY3WBo7pVuNa8WAVpfIDsD5YIq69Y70aF0aYPyq0xgiqkMDe0ldrh/6UYu5/m+5+dcN+d5vvSeyHzX/5PbRss4KiH/VELzTQWtLyV0jivovq9g2/k+hkMH+ArVCBtOUPmMaMIp9n3HaXhIyTnt4bPEFXrCEVLsPUwn5UCYSYibYdP8nNTroD1JouDaQKzDoLO8J/Ut8CfRypta63/+Cs6jsB680LdbF/8vSh5noxZ2JvVZ0Au/Af8vkws=

**Desktop (please complete the following information):**
Chrome Windows 10

**Additional context**

**Comment by Tharre** [comment]
This is not a bug, but a consequence of how mastery works; the total percentage points are rounded down and give you nothing.
See https://github.com/wowsims/cata/issues/544
