### ISSUE TITLE
Crash Report 294455266

### ISSUE THREAD

**Issue by Squisher123** [wowsims/cata#579]
Link:
http://localhost:3333/cata/rogue/assassination/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnbgkgIo8GCOAyoQYpDpZZzGzBeQkVqYWcXAKsEkdY+QSEth/gVnio4IS56qZLNcvMN+4wMzFLvBsB7PGQkYufoGL25kl3igoMX+ZzqwxjxEoM/M5s8Q0BaDMm/fMEvflldiAMkDExSVwcwezxE95JUYGLgGBi0BVd+WVWIAyDBoTGLl4BG7uZIar5Rf4CjR2ngJY4A9QgEdg1l+gPfJge7hYBO7sAJGznoPIU2D20WMgZ70DajsrC2T0A+36LA9kPAE6dDKjEhcHk4FkAFMEUwKL1lomrh+MDCMUCBmQqsOKwYnhFqMgFz8XrwCjBJMCk4aI69kzZ2x3MVlbmCRbphpbGCRZJpsbJCcZGiQbGSZZGBmYW6QaGCeZpBibJlrqAskUc8MkY4uUJDDX3DzFLNH8EBPDCSaWC0zct5gYHjExSTC+YEpZyAyxMdKhi5lB6QwTJ5jXkOYgCBEXcZCcNRMETtpbQkQu2CumgcE1e0egm4Dgjb3RZCaFCAlWLRrHsUanAynKG1KOk6SeEgAJnL3vHRwh/B/2CYwAqN2JgA==

RNG Seed: 3401733038

runtime error: index out of range [4] with length 4
Stack Trace:
goroutine 176 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x98
panic({0x1525580?, 0xc000a0c2a0?})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/rogue.(*Rogue).registerEviscerate(0xc00056a000)
	/home/runner/work/cata/cata/sim/rogue/eviscerate.go:49 +0x349
github.com/wowsims/cata/sim/rogue.(*Rogue).Initialize(0xc00056a000)
	/home/runner/work/cata/cata/sim/rogue/rogue.go:159 +0xe5
github.com/wowsims/cata/sim/rogue/assassination.(*AssassinationRogue).Initialize(0xc0002b6428)
	/home/runner/work/cata/cata/sim/rogue/assassination/assassination.go:31 +0x25
github.com/wowsims/cata/sim/core.(*Environment).initialize(0xc000704000, 0xc000f0c000?, 0xc000f0c280)
	/home/runner/work/cata/cata/sim/core/environment.go:141 +0x166
github.com/wowsims/cata/sim/core.NewEnvironment(0x951060?, 0xc0000616c0?, 0x4?)
	/home/runner/work/cata/cata/sim/core/environment.go:55 +0x6e
github.com/wowsims/cata/sim/core.NewSim(0xc0004d82d0)
	/home/runner/work/cata/cata/sim/core/sim.go:189 +0x25
github.com/wowsim...

**Comment by rosenrusinov** [comment]
Duplicate #573
