### ISSUE TITLE
not calculating mastery=0 in Stat Weights with this profile(afli warolock)

### ISSUE THREAD

**Issue by Pred-ok** [wowsims/cata#582]
{"talents":"223222003013321321-0300000000000000000-3300000000000000000","glyphs":{"minor":[{"spellID":58079},{"spellID":58107},{"spellID":58070}],"prime":[{"spellID":56241},{"spellID":56218},{"spellID":63302}],"major":[{"spellID":56224},{"spellID":56240},{"spellID":56226}]},"class":"warlock","unit":"player","race":"Orc","name":"Предд","gear":{"items":[{"id":58155,"gems":[68780,52217],"enchant":4207},{"id":62416,"gems":[],"reforging":167},{"id":56399,"gems":[52217],"enchant":4200},{"id":56371,"gems":[],"reforging":138,"enchant":4072},{"id":56417,"gems":[52208,52217],"enchant":4063},{"id":64723,"gems":[],"reforging":138,"enchant":4089},{"id":62364,"gems":[52217],"reforging":166,"enchant":4068},{"id":57921,"gems":[52217,52257],"reforging":167},{"id":58154,"gems":[52257,52208],"enchant":4111},{"id":62450,"gems":[52257],"reforging":137,"enchant":4092},{"id":58188,"gems":[]},{"id":62352,"gems":[]},{"id":52353,"gems":[]},{"id":56320,"gems":[]},{"id":64489,"gems":[],"enchant":3854},null,{"id":56296,"gems":[],"reforging":138}]},"professions":[{"name":"Engineering","level":472},{"name":"Jewelcrafting","level":515}],"level":85,"spec":"affliction","realm":"Пламегор"}

**Comment by rosenrusinov** [comment]
@Tharre this is gonna hunt us till the end of cata 😅.

**Comment by Tharre** [comment]
@rosenrusinov I still haven't given up hope that Blizzard will fix this shit :/

This is not a bug, but a consequence of how mastery works; the total percentage points are rounded down and give you nothing.
See https://github.com/wowsims/cata/issues/544, https://github.com/wowsims/cata/issues/576
