### ISSUE TITLE
Can we make this more portable pls (node rollup dep)

### ISSUE THREAD

**Issue by MikeJakubik** [wowsims/cata#586]
Node deps don't compile on BSD because of non-portable deps.

**To Reproduce**
1. gmake host

```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
/root/cata/node_modules/rollup/dist/native.js:84
        throw new Error(
              ^

Error: Your current platform "freebsd" and architecture "x64" combination is not yet supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead.

The following platform-architecture combinations are supported:
android-arm
android-arm64
darwin-arm64
darwin-x64
linux-arm
linux-arm (musl)
linux-arm64
linux-arm64 (musl)
linux-ppc64
linux-riscv64
linux-s390x
linux-x64
linux-x64 (musl)
win32-arm64
win32-ia32
win32-x64

If this is important to you, please consider supporting Rollup to make a native build for your platform and architecture available.
```
Use WASM build "@rollup/wasm-node" instead perhaps, or not use deprecated APIs?

**Desktop (please complete the following information):**
- OS: [FreeBSD 14, node v20.14.0]

**Comment by Tharre** [comment]
I don't think the deprecation warning has anything to do with this.

Have you tried substituting @rollup/wasm-node? If this works then we can just conditionally enable that for the BSDs I guess.

**Comment by 1337LutZ** [comment]
@MikeJakubik For development purposes I would suggest overriding the dependency in the `package.json` by adding the following:
```
"overrides": {
	"vite": {
		"rollup": "npm:@rollup/wasm-node@4.13.0"
	}
}
```

Make sure to revert that + the `package-lock.json` update when comitting any changes.

**Comment by 1337LutZ** [comment]
Closing this as my previous comment should be sufficient to make this work.

**Comment by MikeJakubik** [comment]
> "overrides": {
> 	"vite": {
> 		"rollup": "npm:@rollup/wasm-node@4.13.0"
> 	}
> }

Yes, I have tried this, and it works! Is here any way to conditionally add that to package.json if OS == BSD?

[root@fbsd14 /tmp/cata]# uname -a
FreeBSD fbsd14 14.1-STABLE FreeBSD 14.1-STABLE stable/14-9d7622367a GENERIC amd64
[root@fbsd14 /tmp/cata]# go version
go version go1.21.11 freebsd/amd64
[root@fbsd14 /tmp/cata]# node -v
v20.14.0


```
"overrides": {
	"vite": {
		"rollup": "npm:@rollup/wasm-node@4.13.0"
	}
}
}
"package.json" 77 lines, 2218 characters
[root@fbsd14 /tmp/cata]# npm install
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 462 packages, and audited 463 packages in 31s

145 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[root@fbsd14 /tmp/cata]# gmake wowsimcata
protoc -I=./proto --go_out=./sim/core ./proto/*.proto
Starting webassembly compile now...
WASM compile successful.
...
✓ built in 27.53s
touch dist/cata/bundle/.dirstamp
touch dist/cata/.dirstamp
rm -rf binary_dist
mkdir -p binary_dist
cp -r dist/cata binary_dist/
rm binary_dist/cata/lib.wasm
rm -rf binary_dist/cata/assets/db_inputs
rm binary_dist/cata/assets/database/db.bin
rm binary_dist/cata/assets/database/leftover_db.bin
mkdir -p binary_dist/cata
touch binary_dist/cata/embedded
cp sim/web/dist.go.tmpl binary_dist/dist.go
Starting server compile now...
Build Completed Successfully
```

**Comment by 1337LutZ** [comment]
> @1337LutZ
> 
> > "overrides": {
> > "vite": {
> > "rollup": "npm:@rollup/wasm-node@4.13.0"
> > }
> > }
> 
> Yes, I have tried this, and it works! Is here any way to conditionally add that to package.json if OS == BSD?
> 
> [root@fbsd14 /tmp/cata]# uname -a FreeBSD fbsd14 14.1-STABLE FreeBSD 14.1-STABLE stable/14-9d7622367a GENERIC amd64 [root@fbsd14 /tmp/cata]# go version go version go1.21.11 freebsd/amd64 [root@fbsd14 /tmp/cata]# node -v v20.14.0
> 
> ```
> "overrides": {
> 	"vite": {
> 		"rollup": "npm:@rollup/wasm-node@4.13.0"
> 	}
> }
> }
> "package.json" 77 lines, 2218 characters
> [root@fbsd14 /tmp/cata]# npm install
> npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
> npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> added 462 packages, and audited 463 packages in 31s
> 
> 145 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> [root@fbsd14 /tmp/cata]# gmake wowsimcata
> protoc -I=./proto --go_out=./sim/core ./proto/*.proto
> Starting webassembly compile now...
> WASM compile successful.
> ...
> ✓ built in 27.53s
> touch dist/cata/bundle/.dirstamp
> touch dist/cata/.dirstamp
> rm -rf binary_dist
> mkdir -p binary_dist
> cp -r dist/cata binary_dist/
> rm binary_dist/cata/lib.wasm
> rm -rf binary_dist/cata/assets/db_inputs
> rm binary_dist/cata/assets/database/db.bin
> rm binary_dist/cata/assets/database/leftover_db.bin
> mkdir -p binary_dist/cata
> touch binary_dist/cata/embedded
> cp sim/web/dist.go.tmpl binary_dist/dist.go
> Starting server compile now...
> Build Completed Successfully
> ```

Unfortunately not. NPM doesn't support this kind of logic :(

**Comment by dexxiez** [comment]
I was wondering if pnpm or yarn can do conditional patching (which is a terrible idea anyway), but yeah it's such a massive edge case. 

One awful approach, but better than manually doing it, is below how I think it might work out.  Forgive my `jq` query skills. 

```bash
#!/bin/bash

git restore package.json package-lock.json

git pull

# Check if the overrides section exists, if not create it
if ! grep -q '"overrides"' package.json; then

    # Add the overrides section
    jq --argjson vite '{ "vite": { "rollup": "npm:@rollup/wasm-node@4.13.0" } }' '. + { "overrides": $vite }' package.json > temp.json && mv temp.json package.json
else

    # Append to the overrides section because it might exist already for some reason
    jq --argjson vite '{ "vite": { "rollup": "npm:@rollup/wasm-node@4.13.0" } }' '.overrides += $vite' package.json > temp.json && mv temp.json package.json
fi

npm install
```

**Comment by 1337LutZ** [comment]
I don't think any package managers have these kind of overrides supported.
But the Makefile script can work indeed

**Comment by MikeJakubik** [comment]
> I don't think any package managers have these kind of overrides supported. But the Makefile script can work indeed

Something like this pseudo code, with echo or sed?

```
build:

OS := $(shell uname -s)
 ifeq ($(OS),FreeBSD)
  echo "new code" >> package.json

```

**Comment by dexxiez** [comment]
PR submitted for this. You can force it by running `make package.json` if it doesn't trigger by itself for whatever reason. First time doing anything with a makefile, but according to my tests it works
