### ISSUE TITLE
Crash Report 978234047

### ISSUE THREAD

**Issue by muhnow** [wowsims/cata#592]
Link:
https://wowsims.github.io/cata/rogue/assassination/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnbgkgIo8GCOAyoQYpJ4wz2JmC8hJrEwt4uAUYJNS4mIgBJW4OJgMJAOYIpgSWLTWMnH9YGQYoUDIgFQdVgxODLcYBbn4uXgFGCWYFJg0RFzPnjlju4vJ2sIk2TLV2MIgyTLZ3CA5ydAg2cgwycLIwNwi1cA4ySTF2DTRUhdIppgbJhlbpCSBuebmKWaJ5oeYGE4wsVxgYr/FxPCIiUmC8QVTykJmiI2RDl3MDEpnmDjBvIY0B0GIuIiD5KyZIHDS3hIicsFeMQ0Mrtk7At0EBG/sjSYzKURIsGrROI41Oh1IUd6Qcpwk9ZQASODsfe/gCOH/sE9gBACPXEr5

RNG Seed: 0

runtime error: index out of range [4] with length 4
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1bffa0, 0x3070b70})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/rogue.(*Rogue).registerEviscerate(0x3844000)
	/home/runner/work/cata/cata/sim/rogue/eviscerate.go:49 +0x25
github.com/wowsims/cata/sim/rogue.(*Rogue).Initialize(0x3844000)
	/home/runner/work/cata/cata/sim/rogue/rogue.go:165 +0x10
github.com/wowsims/cata/sim/rogue/assassination.(*AssassinationRogue).Initialize(0x30316b0)
	/home/runner/work/cata/cata/sim/rogue/assassination/assassination.go:31 +0x4
github.com/wowsims/cata/sim/core.(*Environment).initialize(0x33fea20, 0x381ee80, 0x381f000)
	/home/runner/work/cata/cata/sim/core/environment.go:141 +0x25
github.com/wowsims/cata/sim/core.NewEnvironment(0x381ee80, 0x381f000, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:55 +0x4
github.com/wowsims/cata/sim/core.ComputeStats(0x3812840)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x3816e70, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by muhnow** [comment]
Attempted to import the following wowhead link and it's causing this exception to be thrown:

https://www.wowhead.com/cata/gear-planner/rogue/troll/BBg1T4TJ44C5xwyxDCG4IHjgO001qf011xs421qf131qf441qfb51xrr61rnp71rnh81rngRNB4GQf4IiK4GQ44GQ34M92AC4IIhgFD4GgOiB4EfU4M9bgFF4FjShz4EfU4J3qJG4Fi54EfU4EfU4FLIgJH4FfVh64EfU4EfU4K07gFI4GBSh34EfU4J3FgBJ4Fg5h64PPoGK4GgL4EfU4J3v4LzfAL4G96AM4IisAN4G_fgAO4F8lhsgCP4IIehz4GjX4FK6CQ4FfO4J3mx3HCR4Ffv4J3mwbngAS4IYihz

**Comment by TheBackstabi** [comment]
Looks like wowhead import isn't reading talents right, this has come up in a few other crash reports where it's attempting to assign more points than possible into Coup de Grace which causes this error during initialization.

**Comment by 1337LutZ** [comment]
The Wowhead import/export hasn't been supported since Cata. I've created a PR to update the UI.
https://github.com/wowsims/cata/pull/769
