### ISSUE TITLE
reforging not coming along with a sixtyupgrades import

### ISSUE THREAD

**Issue by rdmqwerty** [wowsims/cata#594]
**Describe the bug**
when importing a gearset from sixtyupgrades/cata, the reforges on the item do not get translated into wowsims

**To Reproduce**
1. Go to https://sixtyupgrades.com/cata
2. create a gear set including reforges
3. click the three dot menu - export
4. import the data string into wowsims
5. observe that reforged items are not reforged in wowsims

**Expected behavior**
i would expect the gear to be imported exactly as it was exported

**Comment by kayla-glick** [comment]
Hey @rdmqwerty 👋 we were missing this for a while because 60U was missing some data we needed to pull reforges. They should be imported now though as of https://github.com/wowsims/cata/pull/619
