### ISSUE TITLE
Import from WowSimsExporter to wowsims website applies incorrect talents for fire mage

### ISSUE THREAD

**Issue by RikPerry** [wowsims/cata#595]
When I import my Equipped Only data from the WowSimsExporter Vv2.11.0 on my mage the talents are incorrect.

**To Reproduce**
1. Generate Data (Equipped Only)
2.  EG {"talents":"0003000000000000000000-230330221120121213231-0300000000000000000","glyphs":{"minor":[{"spellID":57924},{"spellID":57928},{"spellID":57925}],"prime":[{"spellID":56382},{"spellID":56368},{"spellID":56384}],"major":[{"spellID":63095},{"spellID":56380},{"spellID":56373}]},"class":"mage","unit":"player","race":"Worgen","name":"Raithan","gear":{"items":[{"id":59449,"gems":[68780,59493,59478],"enchant":4207},{"id":62434,"gems":[],"reforging":165},{"id":58157,"gems":[52166],"reforging":165,"enchant":4200},{"id":62357,"gems":[],"reforging":151,"enchant":4115},{"id":60244,"gems":[52207,52217],"reforging":151,"enchant":4063},{"id":64723,"gems":[],"reforging":137,"enchant":4071},{"id":62364,"gems":[52217],"reforging":166,"enchant":4068},{"id":57921,"gems":[52217,52173],"reforging":165},{"id":54505,"gems":[52173],"reforging":151,"enchant":4113},{"id":62450,"gems":[52166],"reforging":152,"enchant":4069},{"id":62352,"gems":[],"reforging":151},{"id":65169,"gems":[52173],"reforging":166},{"id":62470,"gems":[]},{"id":56407,"gems":[],"reforging":137},{"id":56357,"gems":[],"reforging":151},{"id":57923,"gems":[],"reforging":152,"enchant":4091},{"id":56296,"gems":[],"reforging":166}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"fire","realm":"Remulos"}
3. Note my current talents in game: 
![image](https://github.com/wowsims/cata/assets/93174642/8d0fb87d-341a-46fe-824d-e61b27c4895c)
4.  When i look at the talents on the wowsim site, ![image](https://github.com/wowsims/cata/assets/93174642/77dc6c2d-7117-42f5-8e0b-5de5741988fe)
5. Torment of the Weak is talented instead of Netherwind Prescence

**Comment by rosenrusinov** [comment]
There seems to be an extra 0 at the start of your talents string that got exported from the addon which causes this bug.

@RikPerry can you generate a new export data from the latest addon version using this mage character and paste it here again?

**Comment by RikPerry** [comment]
@rosenrusinov 
{"talents":"0003000000000000000000-230330221120121213231-0300000000000000000","glyphs":{"minor":[{"spellID":57924},{"spellID":57928},{"spellID":57925}],"prime":[{"spellID":56382},{"spellID":56368},{"spellID":56384}],"major":[{"spellID":63095},{"spellID":56380},{"spellID":56373}]},"class":"mage","unit":"player","race":"Worgen","name":"Raithan","gear":{"items":[{"id":59449,"gems":[68780,59493,59478],"enchant":4207},{"id":62434,"gems":[],"reforging":165},{"id":58157,"gems":[52208],"reforging":165,"enchant":4200},{"id":62357,"gems":[],"reforging":151,"enchant":4115},{"id":60244,"gems":[52207,52217],"reforging":151,"enchant":4063},{"id":64723,"gems":[],"enchant":4071},{"id":62364,"gems":[52217],"reforging":166,"enchant":4068},{"id":54503,"gems":[52217,52207],"reforging":166},{"id":60245,"gems":[52239,52207],"reforging":152,"enchant":4113},{"id":62450,"gems":[52208],"reforging":152,"enchant":4069},{"id":62352,"gems":[],"reforging":151},{"id":65169,"gems":[52207],"reforging":166},{"id":62470,"gems":[],"reforging":137},{"id":56339,"gems":[],"reforging":166},{"id":56441,"gems":[],"enchant":4083},{"id":57923,"gems":[],"reforging":152,"enchant":4091},{"id":56296,"gems":[],"reforging":166}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"fire","realm":"Remulos"}

**Comment by Sepulchre49** [comment]
It looks like there is a bug in WoW's talents API. There is an extra talent at position 1 of the Arcane tree for "Improved Polymorph" that doesn't actually exist in the game. You can see this by running `/run print(GetTalentInfo(1,1))` on a mage in game:

![Screenshot 2024-06-09 112715](https://github.com/wowsims/cata/assets/25937672/9eb433b0-464b-4246-82ee-6ba1a8531bd2)

I'm looking into a fix on the exporter side to resolve this issue.

**Comment by 1337LutZ** [comment]
@RikPerry This should be fixed in the latest WSE version.
https://github.com/wowsims/exporter/releases/tag/v2.11.3
