### ISSUE TITLE
Microsoft Defender detected Trojans - rly?!

### ISSUE THREAD

**Issue by Patiivs** [wowsims/cata#596]
Downloaded the simulator and got the information from Windows, it detected a trojan
![image](https://github.com/wowsims/cata/assets/105670942/1a2ce3f2-e792-4ed4-8d96-97a5de0887a0)

**Comment by Tharre** [comment]
This is a false positive.

We get these on occasion, but not much we can do about it on our side.

**Comment by kayla-glick** [comment]
Here's an issue from our SoD repo where this was brought up and I tried to look up what causes the sim to be flagged https://github.com/wowsims/sod/issues/715.

It basically seems to be our inclusion of a Discord link and Google metrics API that are just normal parts of the site

**Comment by dexxiez** [comment]
Just an idea, might be stupid but I don't know. Would signing the executable with something like [Cosign](https://github.com/sigstore/cosign) give the exe more reputation and not flag a false positive when some stupid defender definitions get released?

**Comment by Tharre** [comment]
> Just an idea, might be stupid but I don't know. Would signing the executable with something like [Cosign](https://github.com/sigstore/cosign) give the exe more reputation and not flag a false positive when some stupid defender definitions get released?

No that won't work. We could use the Microsoft signing thing in theory, but last I checked that was pretty expensive.

**Comment by kayla-glick** [comment]
@Tharre what in the world I just looked into pricing. That's ridiculous. Upwards of $100-200+ per year just to sign the executable

**Comment by Tharre** [comment]
@kayla-glick yeah it's wild. And they don't even have a free open source program or something to my knowledge
