### ISSUE TITLE
Pet are stronger on the Sim

### ISSUE THREAD

**Issue by Francoporto** [wowsims/cata#598]
**Describe the bug**
The melee attack and the Claw spell do stronger damage on the sims than the game.

Class: Hunter
Spec: Survival
Pet: Cat

5 min fight on the boss, i was checking why i was missing with less dps in the game than the sim, and i found the pet seems stronger on the Sim.

In game : 
Cat average melee : 105 hits - 1282 dps average hit - DPS 
Cat average Claw : 57 hits- 2620 dps average hit

On the Sim:
Cat average melee : **194 hits** - 2189 dps cast hit
Cat average Claw : **91** hits- 5149 dps cast hit

Because of hits numbers, i think the pet has no Focalisation issue and he's always full, so there is 2x more attacks, and because of that, the talent https://www.wowhead.com/cata/spell=62762/wild-hunt - 
When your pet is at or above 50 Focus, your pet's Basic Attacks will deal 120% more damage, but cost 100% additional focus. - This talent i think should be perma active.

**Comment by ToxicKevinFerm** [comment]
> **Describe the bug** The melee attack and the Claw spell do stronger damage on the sims than the game.
> 
> Class: Hunter Spec: Survival Pet: Cat
> 
> 5 min fight on the boss, i was checking why i was missing with less dps in the game than the sim, and i found the pet seems stronger on the Sim.
> 
> In game : Cat average melee : 105 hits - 1282 dps average hit - DPS Cat average Claw : 57 hits- 2620 dps average hit
> 
> On the Sim: Cat average melee : **194 hits** - 2189 dps cast hit Cat average Claw : **91** hits- 5149 dps cast hit
> 
> Because of hits numbers, i think the pet has no Focalisation issue and he's always full, so there is 2x more attacks, and because of that, the talent https://www.wowhead.com/cata/spell=62762/wild-hunt - When your pet is at or above 50 Focus, your pet's Basic Attacks will deal 120% more damage, but cost 100% additional focus. - This talent i think should be perma active.

Could you paste the log url?

**Comment by ToxicKevinFerm** [comment]
https://classic.warcraftlogs.com/reports/RPc1AzwHMhCNpm3Z#fight=50&type=damage-done&source=7

https://wowsims.github.io/cata/hunter/survival/#eJzlVF1oHFUUnnPu7O7dE2smt4mdXhazGamuS7fOzG5gDdKd5CmtfQjiQ/Wpwf5rIWZ8qD6l2IdYEYoKJkElXf9KaEEFaS0+FJG2tkoWlBLTh9LSZYu0YGkfBBW9c2dHt/jSPPjkYWDu+e53vvNz5w6t42BBALthAqYBZgCOApwGWAK4DjCFMI3wKcJIlsNoTBGGvEJzLD32wvjLOyZ5xkL5I5CwTjeYfSvvZBdmzYsN1mwwMq0L3zDqtl5fYvaNvMPuvMMKM0AZ67cTzL7A1c5XvzP7cr+TVjvqoVXW2yeZ3ep3wIiIq6zpJeaYascovAaKfulLlnALH0U5Z1X8+/m/sY8j0mctla3fSYCMNdfSC9NaPsGU+2erjZ8/qRdkHf6D2a8ORIqG8upKczGvPKebo9s3hltxW2o/HAYoHkf6FYz/qQl3pRFDxghOwCFwaQM9ZPXLXo4WVFkAo2w32x9/bjgQc3+pudDz/XeR3aidwpxbLvll1y+5Zd9V7/jxPd8re97XaPMPmmh92ER7fhHzM4tY+KSJ7luLeA7NBmaW0biK9ZTNaDVlZIoYv/O8wylNZskfDBWYliah3eNkKUOpkrehElIfcakI/OxlsxNOBG7ubAt4bkiiDf7MHUUkVir/E/9GnbXBSmiDeED2klW8n6cEDhkRgdALhwxRkA9TTkpKnUfkQD3Fbm4K3GxIHauqjLjWkTNMK3RFJflRylPdOvMPvYJknLA1z8RBkAeAQvEicT/CvphntL5Y5GnB97Z9mfsc13IQ2QVMECLVkue67r6QsnPQGWjeS+CgCnT0msxBb18oRmRAnniMZNHmTAUkklIP1I/4utOUYG+a7WlUKpNdlK0nVLFZjtJG+QTdFynf1Qy712ZkovWofIQeFDl9AGk9XZ2yGhKvQzTG5ZyMXyI6i6i0dEdpVVfvXlsjnpSbKBAb/8WouFrbvEt7TbFPkTq61xvlMBFLDk59adfx2QMsvgDV4Eh79UxwiBlOE7Pam3ou6EmuyNq52ci+rT0eI43awE5tF2vDyd3xj+HEwm14peup8T3b80+PT+7a8VJ+q50p/sd/rrGDwUroU9vProS/pfreu8MrqqfD9LSm6tnhWYgH+FOtrWUGfwHuZgGp

Rng seed: 3799392633

The amount of attacks matches, 48/110 vs 47/105

However Claw and Bite seems to do more damage than in game.

**Comment by ToxicKevinFerm** [comment]
https://classic.warcraftlogs.com/reports/f4mdPj7Vz1r3gQDT#fight=34&type=damage-done&source=8

https://wowsims.github.io/cata/hunter/survival/#eJzlVF1oHFUUnnPu7O7dk9ZMromdXhazGamui1tnZjewBulO8hRrH4L4UH1qoH9qC2mmD9WnFPsQK0JRwSRoSddqS7BQBekPfSgiVlslCy0lxodScdkiFZT2oaCid+7s2C2+NA8+eRiYe777ne/83LlD6zhYEMBOmIBpgBmA4wDnAZYAbgBMIUwjnEQYyXIYjSnCkNdpjqXHdo2/um2SZyyUV4CEdb7B7N/yTnZh1rzaYM0GI9O69CWjbuvNJWbfzDvs9nusMAOUsX4/xexLXO2c+4PZ1/qdtNpRD6223j3N7Fa/A0ZEXG1NLzHHVDtG4Q1Q9B/OsIRb+CjKOaviD+f/wT6OSJ+2VLZ+JwEy1lxLL0xr+RRT7l+tNn7xtF6QdehPZr8+ECkayqsrzcW88pxujm7fGG7GLal9cAigeALpDhj/UxPuSiOGjBGcgIPg0np6xOqXvRwtqLIARtlOti/+3HAg5v5ac6Hnu28ju1k7izm3XPLLrl9yy76r3vHje75X9rwv0OYfNtE62kR7fhHzM4tYONZE951F/BrNBmaW0fgR6ymb0YOUkSli/PYrDqc0mSV/MFRgWpqEdo+TpQylSt76Skh9xKUi8AvXzE44Efhle1vAc0MSbfBn7igisVL5bvxbddYGK6EN4iHZS1bxAZ4SOGREBEIvHDJEQT5KOSkpdRGRA/UUu7kpcKMhdayqMuJaR75iWqErKsmPUp7t1pkv9wqSccLWPBMHQO4HCsUe4n6EfT7P6IlikacFf7nty9xnuJaDyC5gghCpljzXdXeHlJ2DzkDzfgIHVaCj12QOertDMSID8sSTJIs2ZyogkZR6oH7E152mBHvbbE+jUpnsomw9oYqNcpQ2yKdpVaR8TzPsfpuRidbj8jF6WOT0AaT1dHXKaki8DtEYl3MyfonoLKLS0h2lVV29+9Ma8ax8hgKx4V+Miqu1zXu01xT7FKmje71RDhOx5ODUl3YDX9zP4gtQDY60Vy8EB5nhNDGrvfyeoCe5ImvnZiP7pvZUjDRqA9u1Xa0NJ3fH/wQnFm7Ba13Pjb+0Nf/8+OSObXvzm+1M8T/+c40dCFZCn9p6YSX8TdUP3h9eUT0dpqc1Vc8Oz0I8wO9rbS0z+Bt96gFX
Rng seed: 3799392633

Seems to match perfectly.

**Comment by ToxicKevinFerm** [comment]
Closing since logs seem to confirm that the sim is correct.
