### ISSUE TITLE
Scourge strike shadow portion incorrectly calculated

### ISSUE THREAD

**Issue by patrulek** [wowsims/cata#605]
**Describe the bug**
I see differences between simulation and details.

With 17.07 mastery (which is 42.675% shadow dmg increase) + scourge strike glyph + two diseases + ebon plaguestrike applicated) and 220 spell pene shadow portion should be around 108% of physical portion dmg. You can see its accurate on details but not in simulation (which is almost equal in % of physical portion dmg). Tested on 85 lvl / training dummy.

![obraz](https://github.com/wowsims/cata/assets/7295272/7c345428-1ed6-4d5c-8aeb-a5edee682e88)
![obraz](https://github.com/wowsims/cata/assets/7295272/9fc3379c-426e-4a02-8a0f-6f5559549717)

Diseases uptime seems to be almost 100% and i guess sim would restrain from casting scourge strike if not all diseases are applied.

![obraz](https://github.com/wowsims/cata/assets/7295272/f50a377b-8917-491e-ad19-7cab1ae80fab)

**Comment by rosenrusinov** [comment]
@patrulek 

After investigating the Scourge Strike shadow strike spell is scaling with mastery and after a certain number of mastery rating the shadow portion becomes higher then the physical.

Trying the 17.07 mastery I also get the same results as you but I think that is correct as the shadow strike should not scale with 8% magic damage taken debuff. If you think that the 8% debuff should apply and have logs that show it to be true we can update to account for that but from the spell flags in the db it is assumed that the spell doesnt scale with target modifiers.

**Comment by patrulek** [comment]
> Is it possible that you had a temporary mastery proc that you didnt account for when you recorded the SS hits in your details

No, i didnt had any mastery procs. The `details!` screenshot was taken from current patch at given time and as you see 8% additional damage from ebonplague is counted in shadow portion damage, otherwise the shadow portion would be almost equal to physical portion (it should be exactly 100.15785% of physical dmg without ebon debuff, but looking at `details!` we see that it is ~108.05%; adding (multiplying) ebonplague would equal that values out).

You even tested it for yourself, where did you think that 8% additional dmg came from? :P

**Comment by rosenrusinov** [comment]
After further investigations I did find a small problem where Ebon Plaguebringer would drop when it should not (due to the diseases last tick being added to the new application but not for EP). This would lead to a couple of SSs per run that do the damage with only 2 active diseases instead of 3. Today I will test in-game if what you say about the 8% is true and if it really scales the shadow portion damage.
