### ISSUE TITLE
ReforgeLite Integration

### ISSUE THREAD

**Issue by jlukestephens** [wowsims/cata#612]
**Is your feature request related to a problem? Please describe.**

The addition of reforging to classic wow is ruining my simulation experience. Manually selecting reforges and trying to hit the right stat weights is making me very sad.

**Describe the solution you'd like**

There is an addon called 'ReforgeLite' which helps with calculating reforges in game based on preset stat weights. If this addon were integrated into the simulator, it would make my life much easier as I would not have to manually set reforges for all my gear based on what pieces I'm swapping in and out.

**Describe alternatives you've considered**

I am not aware of any alternatives. If I am only simming gear that I currently have, I can reforge using the addon and then export to the sim, but this costs gold every time and it not possible for gear I do not yet have.

**Additional context**

ReforgeLite is the addon I am using in game to calculate reforges. If possible to integrate with the simulator it would be insane.

Thanks!

**Comment by 1337LutZ** [comment]
@jlukestephens This feature was added to WowSims and ReforgeLite!
Sims currently supported
- Elemental Shaman
- Arms / Fury Warrior
- Survival / Beast Mastery / Marksmanship Hunter
- Fire / Arcane Mage

If your spec isn't listed please be patient whilst the class author adds it.

You can export the WowSims JSON and then import it into ReforgeLite to automate the full process.
