### ISSUE TITLE
Firelord Gloves (N) Missing from Fire Mage Cata sim

### ISSUE THREAD

**Issue by breenscream** [wowsims/cata#618]
Links to [Cataclysm Wowhead](https://wowhead.com/cata/items "https://wowhead.com/cata/items") for each item:
https://www.wowhead.com/cata/item=60247/firelords-gloves

**Comment by Tharre** [comment]
Check your filters, these are already in the sim:

![image](https://github.com/wowsims/cata/assets/2140018/c3874b11-48b9-49e6-b0f7-f0a4c7ae7c44)
