### ISSUE TITLE
Crash Report 1424048224

### ISSUE THREAD

**Issue by amphere1620** [wowsims/cata#621]
Link:
https://wowsims.github.io/cata/priest/holy/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnYQFGC0YPRgjgMo2gGWBUkIMUutZZjGzBeQkVqYWcbAKsEptYuTiEdh5gVnijawSMwMDAxe7wJIeZiVGBi4ugZ0TmCUeyULYR7qZJbrAbA6B3ROYlZiASrkFbgNF5whBOTuAyqfIgDmcAlu7mSHm8Qi09TBLtENN5xboBvL+K4BVsQu86AZbxS5wrxPMYBFY08kMJPcCSS6BdUClv2Qh4vN7mIHK/oDVK3FwsBkwBrBEsGitZeL6wcgwQoGQAak6rBicmAoYTzGySbFwMXEwHmJiOMHEcoGJ+xYTwyMmJgnGF0wpH5hSFjJDVEc6dDEzKJ1h4gTzGtIcBCHiIg6Ss2aCwEl7S4jIBXvFNDC4Zu949gwIvLE3msykECHBqkXj+NHodCBFeUPKcZLUUwIggbP3vYMjhP/DPoHRgxMAhWpcBA==

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1050c0, 0x3e9b20})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x38be000)
	/home/runner/work/cata/cata/sim/core/unit.go:516 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x38be000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x38705a0, 0x337a580, 0x337ab00, 0x33324c0, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x337a580, 0x337ab00, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x386c9c0)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x3882030, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by kayla-glick** [comment]
Hey @amphere1620 👋 our healing sims are currently unsupported and as of right now there are no plans to support healing sims in Cata
