### ISSUE TITLE
Crash Report -2046024166

### ISSUE THREAD

**Issue by Shellemental** [wowsims/cata#622]
Link:
https://wowsims.github.io/cata/shaman/restoration/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYndg5gIqAXCEGqS3Ms5jZAnISK1OLONgF2KVsuTgEbl5gVmJiYOBiETi2kIWLXWD6dWYlRgYuBqDU1OsQKRxQiY2DzYAxgEdrLRPXD0aGEQqEDEjVYcXgxFTA2MTEJsXCxcTBeIiJ4QQTywUm9ltMDI+YmCQYXzClLGSGKI106GJmUDrDxAnmNaQ5CELERRwkZ80EgZP2lhCRC/aKaWBwzd7x7BkQeGNvNJlJIUKCVYvGkaPR6UCK8oaU4ySppwRAAmfvewdHCP+HfQKjBycA0Ew8Tw==

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1050c0, 0x3e9b20})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x399e000)
	/home/runner/work/cata/cata/sim/core/unit.go:516 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x399e000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x32e9200, 0x32eae80, 0x32eaf80, 0x382e040, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x32eae80, 0x32eaf80, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x32d9b80)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x32fa630, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by kayla-glick** [comment]
Hey @Shellemental 👋 our healing sims are currently unsupported and as of right now there are no plans to support healing sims in Cata
