### ISSUE TITLE
Crash Report 1354589653

### ISSUE THREAD

**Issue by Swelfyn** [wowsims/cata#625]
Link:
https://wowsims.github.io/cata/paladin/holy/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYndhBioBcIQapaSyzmNkCchIrU4s4WAVYpLoYuTgEjv5lVmJiYOBiEfi1kIWLXeA4kM/IAGScuAZmcAgchqrgEDh1DcY6Ahe7/w/GegllsQvs+APWyiJw9x8zkHz8B0Q+AZMnr4HIJVNYgOQcoAi7wMKfIMVKbBxsBowBHFprmbh+MDKMUCBkQKoOKwYnpgLGVYwcUmxCLByMEkyHmBhOMLFcYGK/xcTwiIlJgvEFU8pCZojiSIcuZiHOUBCYv9dBECLI5KB0hokTzGxIgwmKOEjOmgkCJ+0tISIX7BXTwOCavePZMyDwxt5oMpNChASrFo0jTKPTgRTlDSnHSVJPCYAEzt73Do4Q/g/7BEYPTgCQWFnQ

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x105d20, 0x3ea4a8})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x3100000)
	/home/runner/work/cata/cata/sim/core/unit.go:533 +0x46
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x3100000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x38ca6c0, 0x3869400, 0x3869580, 0x3272380, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x3869400, 0x3869580, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x38bfe40)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x38c6f30, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by kayla-glick** [comment]
Hey @Swelfyn 👋 our healing sims are currently unsupported and as of right now there are no plans to support healing sims in Cata
