### ISSUE TITLE
Ele shaman base rating for spirit not counting towards hit rating.

### ISSUE THREAD

**Issue by dingoezz** [wowsims/cata#628]
**Describe the bug**
Ele shaman base rating for spirit not counting towards hit rating.

**To Reproduce**
make any gear set up in game set it to 17.00% in game and it will not read 17% in sim because its not detecting
the base spirit stat as hit, while the game is.
**Expected behavior**
Adding the base spirit stat to the hit rating stat if specced into the proper talent.
**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Comment by kayla-glick** [comment]
This might be the known Elemental Precision bug in-game that causes you to gain 3% extra hit. I main Ele and use the sim and the numbers I see in the sim match what I see in-game. You could try clicking the ⚙ in the top-right of the sim, then "Restore Defaults" just in case it's a sim caching issue, but I suspect it's the bug I mentioned
