### ISSUE TITLE
Crash Report -1529426629

### ISSUE THREAD

**Issue by VilleHamalainen** [wowsims/cata#639]
Link:
https://wowsims.github.io/cata/druid/balance/#eJztmF9sU1Ucx+/v3Nvu9jcZdweY5aBwVgeWzi7t7ZjrfFhBIDwYxEQjGl/KehdGunZpOxASTfEPmQgI+qBM0bDEaFAjWSCOIQ4HBk0kzhmEoRElalhCQnwwKjzgubftWgjSzfhAY0+a3HO+53d+53d+n3PObS7OV0GDEKyFLugBeA3gXYCjAGcALgCkCfQQ2E9giaZBM6yA1cJsv9VLJTY4o1e2r4qGNxoJ1a4BGwek2pER2XmJuxzv71ZOj8i/jMhYoQ1uU9x9ZufW47LzAnfZL70qi597F+B07fA2xfkKd1lCnyn8dkh2bskKwmKaNv6R7Nxb6wLJvR1Q03YMyM4XuUsR/ZL7VdPtGTFi1x0Tbi3ta2G1Iz/V26bnU8JRT9bzThCBHRKBbTcrPVesyRUtPWAGfO5n2f0OIGrjf8jOzdy0kbBSOzAgZwZvcKmqzTdrlbJa8XxA8E+Q/qeF+qY6okVaQrpgjZ0pSFAaJHMDAT3g03W/Xw/ofvHw+3x+r/nTfYGAf5jUqaeHiPbdEHGeHSJ8bIi4Tw4RX/ocab78AwkdGyUrToySz4kyQirPEuk82VrlBJyFKrOjor530OZyYAXavI0NgeQN5ECDfiNZb/AnsRqtKJ3VLiGh7BXSjKzl6K/KhEgXsDrUPFWqjZIWyexGsijJNKxSX6jhV3MFqJPVIPVoKlB5nyIxa7xYbYtEW1gzNtB7cr19Bb1Y45kpNMcwZCNkQkcIWGF8eNBGnwO2GfBJuh7dbAHe7pmlyrRinTBSh+uZ2qtkalhprkzPNuqoC6e5KtHRb3l9/grBas90VclMba2gyXe91Za81b6cVTDIMi7pOWDfA44C/QowDexp9FA3zvHMFtE41onFqGPLODDsVXJ1dOgT1Vo6LzNTXqpy3Yaoq2hXz47ZRNtL6/FOzxzhDtdNqKyyV8mbFJr/1yscW0YfYg/icrp0Cmk2gRe4zseSS9qbwF4H3AV0xy2RtHysuTW/BeyNWy9AM4PmU4h0JzBxOz8LNA3YxBpxvueuQjI1/WSGaE8Ayp6eazktZ0uR07k32wa6r9DiRtvJ35ijOgpMHILPgA4D7gHWC9hMm3Ch5+5rs+bsJ+YmKkheLrip5fA+GsR6z8Lrcji7n9QIqTCVOfeFg4suO7cTvgE2UoKL+gdSud3jZfVWNObFa7/2Wi48Debzr8uEPs5W40r2wGRul2BwkrdL9nVC65jrJhdGzkpjVWjrV4iaOaID7rwiW8qPNdTBKrLVCySyWc68d/XQ3mztsdBWWXKNex1WK90eqs7oM0Oze3eb5YvWYEYZaa1tt8q3rYtPfmmWi636T3LXoYtXYdPcxbGOznDKiPAl8ZjBHw0nEh3xBNcX8RXcy/38EafqubX+GKUjJ0JTMA/t2fjM4n87VyaDB/pCu+HY7+4nXho+1ZrzFXoZ9oB4pVcvixptqUS8rTtl8Pvj3bGU56mV3Z1rjASPt/PCzrZwMpXkqTjvjEeMaAN/OJ4KR3mbOYRv6IhG+RqDJ7sSRjjCjfVGLLqRx9cLL6m1BjdilploRboT4VRHPCZGpNbyME+EY5F4Z8cmATDe3p40Ug21mfhmhkzGg8UZ62XGUkkzPlyccaDMWCppxh8XZ9xYZiyVNOMjxRkvKjOWSprxJ8UZN5UZSyXNeKg443vLjKWSZny0OOPmMmOppBl/WpxxsMxYKl3G5+WuYZPxvJt/A/GVIUslDfnYJCCXv3SZpYQhH58E5PKnLrOUKOS/AccxiAg=

RNG Seed: 1118149193

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 25 [running]:
runtime/deb...

**Comment by stn-ms** [comment]
Not related to druid, this has to do with the "Blackwing Descent/Nefarian 25 H Adds" encounter. It crashes on a lot of classes.
