### ISSUE TITLE
 Resto sham imported with addon and got error report 

### ISSUE THREAD

**Issue by Eddienord** [wowsims/cata#641]
http://localhost:3333/cata/shaman/restoration/#eJzlUjFIG1EYvv//z8vlkdJn6PDMcudhQYTCy2XRUrjTydGxbhZUOjhIt25BKKRih7ZDEnXJJhShm1AqFA22hYjHDaa4iGJoBiEOHUwV8V0OCsUpiJPf8L/3f3zf+z8eP3tsAgcfXsI8FABKAGsA3wB+ATQB8ggFhM8IYwlTiVSb1jLlnmUyJuZevJ55ZSJPZL4CS/OtgETLdpKfyno9oGZATOenG8SSvFgnh86KxBI83CGRt9lDXm+ROLQco1KipRIxxq8UcWQ5oLEH/INSnViOrjwaS/GjK3IMpVJa5Xx/RuKd/c+Z4iu/STSseILOCxdR3d2J6pt2VI9PosnbKt4fS11WL0lcWCpWpa1itYrqbdOQMJEaWkd2Dto9RVp263iqjeE8LKCZMZhuqr34gs9y8gaeuFKx7v+czOVc15VuNudmpcx2zi0cMGsN5HsNFBtVtNerOBg2UG5Wcbgdon8Z4vjfEH+gHmDiALVjRAFNnK5QnGfSXyTNqWGy0+Vn/d6Yf+T3LZcj/PRGYibw+mc72PdGd2sRTj33I9rPRc/QHW/A4Fu/G3l++ntX+tsg/pzNlj8a9+feFIwnrwEWWozV

**Comment by kayla-glick** [comment]
Hey @Eddienord the Resto shaman sim isn't implemented yet and as far as I know we don't have plans to support healing sims in Cata
