### ISSUE TITLE
Crash Report 86104818

### ISSUE THREAD

**Issue by silverselo** [wowsims/cata#647]
Link:
http://localhost:3333/cata/warrior/arms/#eJzFVV1oHFUUnnPvzuzsWded3N1uJzeGbAfF6UDqzGyXmiLdaZ78AeljfTKBJPjQB8k+SN8ihjaNKGmVNrtYY0opoSKWvDSGFtRq1RAlsKjRl2JAWoqmtYL0KXrnb7tNUzAU63mZe797vu/8zLkz+IQKGnjwCrwKYwCTADMAnwIsA1wDGCEwRuAcgd60Bs/CfuH0AQCT+OVsnSr7DvQfHBxWZS3Fvwdk2q0vqX6zaCgf1hKrJ6h5BjCp3bhKzROAWW3tPNWvFw06NUnNGf9kYTphTvm0m4J2pctQBMenvQmY0X4X3r90GSCZE4Bp7afvqEEkyaz5SueuUkMRMpES0/4QAvViUyAId3GO6r92GbFiUrsyR81j/mJtKXBJaLeWqNh+cZmaRwBRG/uE6n92mpOAkoDnhPsoGGkVbH2fKHwCwPqI4G2QHoo97j2cOP/emL1Zxm6pVzpFEFXRa6KLKZsnlZLtunbJLjmu7TqueLiO022XBLjeuh37XvBzUlRPNog21SD6+w1SPN4g5ukGsc80yNMX/ibeaIN8TRJLJPkzkVbIYdTFeGCSy0jVWs5Iolh0u1XMR9jRnUYKBdrt7ChXMYcKTyDR2yLQ3uE0QXWgBWQJTnZL7DHOUbMeVWVGV0DyBREcrmBCXVwlrIO3b3DqR53pY1t4DgO9of4D1cGAs/YXZYeAvwF4kL+GBZZHZmkqZSISV1F4OE5PFS1mBriyDvcxmZHnY6xkV9FhT93Xl67zlRcIUSFIZPowYZ284x6qaFGQ/vkMew+4uIlvAxc3a6OM/G7+T9mvnJTZNt7VbOBGFayqLMszMSt45awG/DjgW8DHIXptZFjyFZHsKmNqFiJxVI9RX+P0IPazl3GrtUVkkzobH4cMMTfc0LFg5cWhehbCtjXP1umXbCwY+Y0KCybvRabzAmZmxSgTTRZhFk7JQRkTJVbmJexkHZj2p9P1wVEFHzHEnZuFcOjdO/MfLUYVVuD5uygxvoc/gyXmxOX+uEwx5d+aoFHYbm1VEyw1H5+FeZbjrtZyD8Zf7mHia8vDJA/1sV7u4S5evq/C9XfllnHLGOk47Mef0VjDn+M2I7u+e0r4ZC/w59Bje1rzpeMghR2sQygSStchImHWyvhTNRzd6XJcfJ6zFqG4pHgWW/KLwwQu9RxLRTVf2M628yex0+oQRWbm78r4zgDHucesuXRzKbSQq4HHpQlowkd3XiMDr9Pwo5z3pqPVS944lYxFkgp2I0NeW+zRXq/59k2lJ0SWKtuGAvuhsvfbRd9+q7jvkOJ+Xbb+4x+iecTbjPvIwFeb8n8QC5tz8Ya3N9zfrvTBP7cUORM=

RNG Seed: 427740402

When validating reforging for item 69834, the reforging could not be validated. 159
Stack Trace:
goroutine 196 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x98
panic({0xf132e0?, 0xc0011d4b80?})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.NewItem({_, _, _, {_, _, _}, _})
	/home/runner/work/cata/cata/sim/core/database.go:355 +0x...

**Comment by 1337LutZ** [comment]
@silverselo Could you let us know the following:
- How did you create the gaer set? Weakaura import, Addon import or Manually?
- Can you validate that this also happens on the latest release of the local client?

**Comment by 1337LutZ** [comment]
Closing this issue due to no response.
