### ISSUE TITLE
Reforging Bug: the reforging could not be validated - <id>

### ISSUE THREAD

**Issue by nosoju** [wowsims/cata#658]
Link:
https://wowsims.github.io/cata/hunter/survival/#eJzlUk1oE0EUnvfeJm5GxOmiMM3BbFaEpaBsNh6iCDvtqcce661ClR5Eiie9RUSIUSQQ6B8iFn8RBL0FUSha8IfqLkUS8SIIhQqFRhDswYKzHfWgpyCe/JjDe+/73nvfDMP32SBAwQRMQg1gBuAuwALAO4BVgCpCDeEBwlDOhmEjcVj+U2aOsiMnj509ftrOCczHwB2xkJD87Hq5e7NWO6FOQnybeDZv+XXgO0X7Dck116Mv0+TfAc7F25jklJvGjmh0SH4oeFlNftP87ZT/uk7ywh4PGBeiqfmpfs/SPPOnU/bxIplUd1/pkrzm/uq+nK67tKjXFcw6Pc4S1W5qZ7O1xVvioXZniVqL9KzGJsnzRf8WcKYlLe0rdr0dNga7R3AUxzINgIH7yDeA/adwgl47DrMhnIQ6BPwA3ysK+V02CqiQgmGaoDPmn2HRaLtRAH2vl1KsRY/wSFAOfsf+sByEf9bCVKoZfcJSWCqXSk/RtW+soLgeo7y5gu7VGP1mjMFMjJVXy6g6y/gCrQS3v0f2EbkEL+tYHDlbxfFzZPxU1PyP6KiqE/OWMGfSU6rPBAdV/9xsipfRIVNJouKJLbSjwZ9XCZvojsrMwD/+N/5F1Yu8Ov68J/3fwDzOk3U1aPKNaAy+Axdcmn4=

RNG Seed: 696638688

When validating reforging for item 69827, the reforging could not be validated. 138
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x105bc0, 0x3800ed0})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0x110c3, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x8a})
	/home/runner/work/cata/cata/sim/core/database.go:355 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe840, 0x0, 0x1071, {0x33d8a10, 0x3, 0x3}, 0x0}, {0x110c3, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:413 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x335b300)
	/home/runner/work/cata/cata/sim/core/database.go:420 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x33d45a0, 0x0, 0x3358620)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x33d45a0, 0x0, 0x3358620)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x33e2580, 0x0, 0x32ce640)
	/home/runner/work/ca...

**Comment by kayla-glick** [comment]
![Image](https://github.com/wowsims/cata/assets/12898988/3772d465-8305-4c6f-bdb2-f2e8ad637f65)
![Image](https://github.com/wowsims/cata/assets/12898988/8710912a-9607-49f8-801b-1917108165d4)

**Comment by 1337LutZ** [comment]
@nosoju Could you let us know the following:
- How did you create the gaer set? Weakaura import (not supported by us), Addon import or Manually?
- Can you validate that this also happens on the latest release of the local client?

@kayla-glick most likely a Wowsims weakaura issue

**Comment by rosenrusinov** [comment]
This should be fixed with the fixes to the bulk item DB generation? @1337LutZ

**Comment by 1337LutZ** [comment]
@rosenrusinov Unsure, the description doesn't really mention if it was a Bulk item issue and/or an outdated link. I will close it for now since we didn't get a response.
@nosoju Feel free to open a new issue if above suggestions didn't work.
