### ISSUE TITLE
Missing hit rating for Raz's Pauldrons set bonus

### ISSUE THREAD

**Issue by Nezz** [wowsims/cata#660]
**Describe the bug**
When importing my gear from the game, the sim shows that I have 951 hit rating instead of 961.

**To Reproduce**
1. Import the following addon data:
```
{"talents":"20320000000000000000-10000000000000000000-13300321230231021231","glyphs":{"minor":[{"spellID":58680},{"spellID":58677},{"spellID":58640}],"prime":[{"spellID":58642},{"spellID":63333},{"spellID":58686}],"major":[{"spellID":59332},{"spellID":58657},{"spellID":58623}]},"class":"deathknight","unit":"player","race":"Human","name":"Nezzer","gear":{"items":[{"id":59359,"gems":[68779,59479,59478],"enchant":4208},{"id":62447,"gems":[]},{"id":56318,"gems":[52255],"reforging":167,"enchant":4202},{"id":63467,"gems":[],"reforging":144},{"id":58096,"gems":[52176,52081],"reforging":138},{"id":57870,"gems":[52081],"reforging":167},{"id":56336,"gems":[52176]},{"id":62384,"gems":[52081],"reforging":167},{"id":58097,"gems":[52255,52255],"reforging":144,"enchant":3823},{"id":62382,"gems":[52176]},{"id":62350,"gems":[],"reforging":144},{"id":56365,"gems":[],"reforging":160},{"id":56393,"gems":[]},{"id":58180,"gems":[],"reforging":138},{"id":64377,"gems":[],"reforging":145,"enchant":3368},null,{"id":56279,"gems":[52081],"reforging":145}]},"professions":[{"name":"Engineering","level":525},{"name":"Jewelcrafting","level":520}],"level":85,"spec":"unholy","realm":"MirageRaceway"}
```

**Expected behavior**
The sim should show 961 hit rating

**Sim Links and Screenshots**
<img width="515" alt="Screenshot 2024-06-11 at 13 15 04" src="https://github.com/wowsims/cata/assets/431167/efeddf69-22f2-4db7-86d2-766b61d9114e">
<img width="345" alt="Screenshot 2024-06-11 at 13 14 30" src="https://github.com/wowsims/cata/assets/431167/4d85f8cf-e84e-4017-b855-6938a766afab">

**Desktop (please complete the following information):**
 - OS: Windows and macOS
 - Browser Firefox
 - Version 126.0.1

**Comment by rosenrusinov** [comment]
There is an issue with a shoulder socket bonus giving 20 instead of 10 hit in game. I would guess you have those shoulders equipped. Right now you can just add 10 hit manually in the stats panel. I will look into updating the socket bonus to be the same as the bugged version that is in game.

**Comment by Nezz** [comment]
Thanks, that's it. It's [Raz's Pauldrons](https://www.wowhead.com/cata/item=56318/razs-pauldrons).
