### ISSUE TITLE
Reforge error

### ISSUE THREAD

**Issue by pappabgren** [wowsims/cata#673]
Importing via the weakaura export feature.

{"talents":"0003000000000000000000-230330221120121213231-0300000000000000000","glyphs":{"minor":["Glyph of Arcane Brilliance","Glyph of Conjuring","Glyph of Slow Fall"],"major":["Glyph of Dragon's Breath","Glyph of Blast Wave","Glyph of Evocation"],"prime":["Glyph of Molten Armor","Glyph of Fireball","Glyph of Pyroblast"]},"class":"mage","race":"Troll","name":"Athzine","gear":{"items":[{"enchant":4207,"gems":[68780,59478,59493],"id":59449},{"id":56288,"gems":[],"reforging":165},{"enchant":4199,"gems":[52208],"reforging":115,"id":56324},{"enchant":4115,"gems":[],"reforging":115,"id":56434},{"enchant":4063,"gems":[52217,52217],"reforging":144,"id":60244},{"enchant":4089,"gems":[],"reforging":165,"id":59475},{"enchant":4068,"gems":[52207],"reforging":165,"id":60247},{"id":59217,"gems":[52208,52239],"reforging":115},{"enchant":4113,"gems":[52208,52217],"reforging":167,"id":63507},{"enchant":2940,"gems":[52217],"id":62450},{"id":56333,"gems":[],"reforging":144},{"id":59501,"gems":[],"reforging":165},{"id":62047,"gems":[],"reforging":165},{"id":62465,"gems":[],"reforging":138},{"id":63536,"gems":[],"reforging":165},{"id":57923,"gems":[]},{"id":56296,"gems":[],"reforging":167}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"","realm":"Golemagg"}

Getting this error.

![Untitled](https://github.com/wowsims/cata/assets/151083957/42b8fa7b-3bb6-4ec2-9065-4743b101b9c6)

**Comment by 1337LutZ** [comment]
@pappabgren We are not the authors of the WowSims Weakaura. The last update to the Weakaura was the 28th of May and we've fixed quite a lot of issues after that.
Make sure to install the WowSimsExporter addon to have the most up to date export feature.
