### ISSUE TITLE
Ravager pet for the hunter survival sim is casting curse of the elements instead of phys invul.

### ISSUE THREAD

**Issue by AnttiGoos** [wowsims/cata#675]
**Describe the bug**
Ravager pet for the hunter survival sim is casting curse of the elements instead of phys invul.

**To Reproduce**
Remove all raid buffs. choose ravager pet.

**Expected behavior**
Ravager to cast acid spit or ravage

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 1337LutZ** [comment]
@ToxicKevinFerm it looks like there might be some leftover testing code that was comitted?
![image](https://github.com/wowsims/cata/assets/1216787/0d380007-fd1b-419b-8a13-00a246cd7cca)
