### ISSUE TITLE
Crash Report -699670768

### ISSUE THREAD

**Issue by nkoerner93** [wowsims/cata#677]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzlkk1oE1EQx3fe26bJ1uIzVF17yXPxEAOVzUZBvWRTL/GgBhWsxyXZtovbJLQrweChrT0UUaRekvQgeCmKCoqHxo+TBD/QaIhY0YMVSWkOQrA9tEKL7kcEQS9BPIj/d3n7n9/MDjOP2+oGGQYhDZMAeYBrAHWA2wh6WWIGvEz3g7Zp7Irpyhl12O0huPs1cBvJjceYb1DBdbPAfs1hrp2US9g/A5yHXFnDAna8u0XMr/g4L3m4jvl5n+Bq5KyIPwdcJ1law/yiTwDGSuskb+cwX/MJrIkwZv0vs9jGGw7uJW/M+JT5w0t528tbTSwtYn7BJ+CJvG20k4tFm95AptbNJixuxrIrRfvCkrE65jjyahbzyz4rgzGDpYoVFNzuNnFzjO1jA7cQtwrMfyqv2GrGfqYXpWEaWA5xzH0UFsWQ+It6pJAYComSFAxKYlAyT0gKBXt+gz5CO9zfyogslxG/UkZ09QPyX19A4vhLtHe+iuRaFUWfV9FTBBXU8R4xnxDioY4SY9hpZ7d8tXk7KZ/HjHDB5bG/RvvlTY7fJW+bLlh6Ft7nOJXw9n5bc+FI+YWlz2Eph9O1Esp2HFIGhpQMDYo0Svt4CPzltxGbkFvBRxNPWuL9d8YjrfA/y57W6BEUKYAzwHfhZi1WvgyDbvB2HRxKK7pKj6pK3NBSSXpcG1IDh6OpDNVTyQGa0XSdGoMmoGgJaiinVGqkaDMpqioJqiXpMTWeSiZGdlF/pN9Qh21eS2qGpujmFkZ2SvdQenIcZ7f06kpWM6seSCVHjOHTccNZ0ol/fkmVc3v+bEnM2QW50BzBxx9LYmQRvgNNQdQz

RNG Seed: 3122934634

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x13c800, 0x1c9ede0})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Dot).periodicTick(0x3081f80, 0x3099560)
	/home/runner/work/cata/cata/sim/core/dot.go:224 +0x26
github.com/wowsims/cata/sim/core.(*Simulation).Step(0x3099560)
	/home/runner/work/cata/cata/sim/core/sim.go:526 +0x25
github.com/wowsims/cata/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/cata/cata/sim/core/sim.go:483
github.com/wowsims/cata/sim/core.(*Simulation).runOnce(0x3099560)
	/home/runner/work/cata/cata/sim/core/sim.go:370 +0x7
github.com/wowsims/cata/sim/core.(*Simulation).run(0x3099560)
	/home/runner/work/cata/cata/sim/core/sim.go:338 +0x3f
github.com/wowsims/cata/sim/core.runSim(0x3853b...

**Comment by kayla-glick** [comment]
I've been prodding around with gear and can't figure this out at face value. I change to the P1 preset and it runs fine, but no matter what I do with this set - removing items over and over - I can't find something reliable to point to

**Comment by kayla-glick** [comment]
Oh wait nope figured it out. Removing the 4p breaks it

**Comment by 1337LutZ** [comment]
Removed the Mage flag because afaik this is most likely Dot related since Druids also have this issue.

**Comment by 1337LutZ** [comment]
This was fixed by: https://github.com/wowsims/cata/pull/755
