### ISSUE TITLE
Crash Report -1361219546

### ISSUE THREAD

**Issue by oldarn32** [wowsims/cata#684]
Link:
https://wowsims.github.io/cata/paladin/holy/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnVhAioQYpNYzz2JmC8hJrEwt4mAVYJFS42LAA1kEDj5nArGU2DjYDBgDOLTWMnH9YGQYoUDIgFQdVgxOTAWMqxjZpFiEmASYDjExnGBiucDEfouJ4RETkwTjC6aUhcwQpZEOXcxCnKEgMH+vgyBEkMlB6QwTJ5jZkAYTFHGQnDUTBE7aW0JELtgrpoHBNXvHs2dA4I290WQmhQgJVi0aR5dGpwMpyhtSjpOknhIACZy97x0cIfwf9gmMHpwANRI6mA==

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x107800, 0x3f0b60})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x33c6000)
	/home/runner/work/cata/cata/sim/core/unit.go:533 +0x46
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x33c6000)
	/home/runner/work/cata/cata/sim/core/character.go:467 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x305a360, 0x306e380, 0x306ea80, 0x3055640, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x306e380, 0x306ea80, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x3055200)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x3304ae0, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.11/x64/src/syscall/js/func.go:100 +0x26

**Comment by 1337LutZ** [comment]
@oldarn32 Closing this issue since the Holy Paladin sim is not supported. You can also see that on the left side.
![image](https://github.com/wowsims/cata/assets/1216787/fa3a4aec-e442-4b27-bbda-5f965217bb29)
