### ISSUE TITLE
(Mage) Hardcast Pyroblast does not apply PyroblastDot

### ISSUE THREAD

**Issue by Okumba** [wowsims/cata#686]
**Describe the bug**
I changed the Rotation (APL) to cast Pyroblast (I tested with some conditions to check when to cast Pyroblast, but I suppose it would also happen if you just change the Fireball cast to Pyroblast). After a hardcasted Pyroblast landed midfight the PyroblastDot is not applied.
The PyroblastDot is applied when an instant pyroblast is cast from hotstreak and from the prepull hardcast pyroblast.

**To Reproduce**
1. Change APL From Auto
2. Add a Pyroblast with conditions (or change fireball cast to pyroblast)
3. check Timeline feature: casted (with casttime) pyroblast does not apply PyroblastDot on landing, while Pyroblast casts with hotstreak (no casttime) does apply the dot on landing.

**Expected behavior**
The PyroblastDot should be applied whenever a pyroblasts lands.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 125.0.6422.176
 
 
![image](https://github.com/wowsims/cata/assets/12104185/d2ea579a-5168-4127-baaa-1f96ff462257)

**Comment by julianwn** [comment]
Small addition: The precasted pyroblast does apply a DoT.
