### ISSUE TITLE
Crash Report -2107595911

### ISSUE THREAD

**Issue by chistvas** [wowsims/cata#687]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzlUc8rbUEcn+985557zSPjRh02hyl1U2ruOW/D5hz+Akt2FHqLtxAru2uhuCW3LHDL4i1evUJZIgoLv7l3haSUXrkLxZJQZu5hxeYmK5+p6fv5zOcz328zvDEGAgL4BQMwBjAD8A9gA+AMoACQojBGYYlCOzOmOKnLRLJodfzuGe4bjHGBdQfAy8X8NkprYZY9TCOPivw1Jv4aeT2HErWWyADnYjOPdsExJ3Gx9oz2pSOt2+m383IxuoL2gyOBJIa4EKcnaP93JNMOYjIVIn2Hkk3OaKrtlWI3h3amXlpaMW0rxdUx2k+ORJ0wAUus7TN9VVRMLBc7RMXcU7FgIrWMej/KmWkv9FiPjqaFNJOxWETVdLBO1rRI+T2Qb4q4KjXRStrpAGSBccrJKg2UUp56h2bXU56nXDeZdFXS1ctzvWTzB9YtSnYpy9Mf55RcUWpDgfaOYNjrZ/DnteoK0kjkIS0rslR/UBXq1UFtdtZgz28Jlbzf0F/Eid92dGhw47tTtL7TjjR98T8nxoNS7KnenZL8n0H4OOu3QVvI7/1ueAFjwX8G

RNG Seed: 2168834883

When validating reforging for item 63498, the reforging could not be validated. 144
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x107820, 0x333aee0})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0xf80a, 0x0, 0x0, {0x32f5688, 0x2, 0x2}, 0x90})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe32b, 0x0, 0x0, {0x32f5660, 0x2, 0x2}, 0x0}, {0xf3d0, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x334c680)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x33290e0, 0x0, 0x334f0a0)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x33290e0, 0x0, 0x334f0a0)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x31cba20, 0x0, 0x3376730)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +0x1d
github.com/wowsims/cata/sim/core.NewRaid(0x3371400)
	/home/ru...

**Comment by 1337LutZ** [comment]
@chistvas Could you let us know the following:
- How did you create the gaer set? Weakaura export (not supported by us), Addon export or manually in the UI?
- Can you validate that this also happens on the latest release of the local client?

**Comment by 1337LutZ** [comment]
No response for 5 days, closing for now. 
@chistvas If you see this error again please open a new issue, but make sure to let us know more details about the steps to reproduce.
