### ISSUE TITLE
Error importing from bags

### ISSUE THREAD

**Issue by IOEggception** [wowsims/cata#690]
**Describe the bug**
One of the items in my bag is failing to import when i try to do "import from bags" in the new Batch tab.  I'm use WowSims Exporter to get my bag items, and when I go to import them I get an error saying "Error: Cannot parse JSON null for proto.ItemSpec#gems".  I narrowed it down to being a specific piece of gear in my bag causing the problem, which is Bloodthirsty Gladiator's Felweave cowl.  This helm does not have a meta gem equipted, but it does have a mastery gem equipted, so when wowsims generated the json string it's pulling null in for the meta, and then choking when it goes to import is my guess.
In the string below, this helm is item ID 64746.

**To Reproduce**
1) Go to new Batch tab for Demonology Warlock
2) click import from bag
3) use this string:  
      {"items":[{"id":45691,"gems":[]},{"id":58188,"gems":[]},{"id":58157,"gems":[52208]},{"id":56319,"gems":[]},{"id":65167,"gems":[]},{"enchant":4115,"gems":[],"id":62357},{"enchant":3854,"gems":[],"id":56461},{"enchant":3252,"gems":[52219,52219],"id":59454},{"id":75065,"gems":[]},{"enchant":3834,"gems":[],"id":56357},{"id":54498,"gems":[]},{"id":55810,"gems":[]},{"enchant":4091,"gems":[],"id":56306},{"id":56276,"gems":[]},{"id":65169,"gems":[52207]},{"enchant":4063,"gems":[],"id":55998},{"id":56440,"gems":[]},{"enchant":4068,"gems":[52207],"id":58158},{"id":59519,"gems":[]},{"id":54496,"gems":[]},{"id":54499,"gems":[]},{"id":64725,"gems":[]},{"enchant":2332,"gems":[],"id":64723},{"id":54487,"gems":[]}**,{"id":64746,"gems":[null,52219]},**{"id":54489,"gems":[]},{"id":60480,"gems":[]},{"id":54494,"gems":[]},{"id":54497,"gems":[]}]}

**Expected behavior**
the import to work

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

**Comment by 1337LutZ** [comment]
@IOEggception Thanks for the report and the detailed research! 
I'll dive into this.

**Comment by 1337LutZ** [comment]
@IOEggception a fix for this was just pushed to the addon! Should be on curse soon. Thanks for reporting.
