### ISSUE TITLE
Missing items: [Synapse Springs]

### ISSUE THREAD

**Issue by ibjonnyc** [wowsims/cata#705]
Links to [Cataclysm Wowhead](https://wowhead.com/cata/items "https://wowhead.com/cata/items") for each item:
https://www.wowhead.com/cata/spell=82175/synapse-springs

Permanently attaches synapse springs to a pair of gloves, allowing a skilled engineer to increase their highest primary statistic by 480 for 10 sec.  The gloves can only be activated every minute.

**Comment by rosenrusinov** [comment]
Synapse springs are not an item you equip. They are a tinker and as such are part of the tinker menu once you select engineering as a profession in the sim.
