### ISSUE TITLE
Crash Report -2022137882

### ISSUE THREAD

**Issue by wobaron** [wowsims/cata#707]
Link:
https://wowsims.github.io/cata/death_knight/unholy/#eJztUk1IFGEYnvf7Nnedkj4XoWmJ+JzTICizuwXVoR2NoFN4KPqhQ+POLC7MzsjsrKEQWISUUEmX1Fz/DhVEINElq4tFGRRssAoFHSqKKAkPGUX+9I2jVl7EDpG4z+l93+d5n/djnuGFAChwHFoAOgAmAM4iGESQQ1BTTBjTAO0AQS70ZV0XLqo11CbdDvgJH2pDfJBkp7EwQcWiG52+r5ex1ANsNt3vk1tn5wFSO/AbSS/TfaQi7u3A0jng/eTVFBbOUKa+wphW5sCYSebA1CXkPiP7ykXgXG0J6Z7Goo+RnHQV+BB5MYPlgZkFf7GIHf7sbYbIW8Y9X+SEnkVjfgMZyWERu6+8BqwbHvvVBcl7tvfnm/3k4SMstbnF4BSW+oDnyacfWLgecocccxj4zhzcy30grg+ALNTCYfdbVdxE/Dfg1iiC8ko3dnE13NGNoRK+uNQbTMSC3BDaHZGjYXkJKpcOvGGUKaORcCTqVmG3CA+jLYHePCLj75CQzSN6awxJ5/NI7s6jHR2jaAT5csj/EnFvEBLgA9JOYe94mdI/Xx1R2jAnXthUPNe1JJTSBcXmrk4XT2I7vUkuVp6Yw1is+tlTF+OxyGvccGd8Fpq3VpvJlOroGq2xTJ0eUm07adk0sp3uo5U0TA8KgYr/63dp0R4rK5Ar2abT1X97y/uCtweUTngwKR27ODwaW/BSLkEWAhAs3Wvocce24hlHp3usjOlUnNyfSdXpNrUS9HcyrqadNHUsmrI03aiiByxHNWjcXaEnkoZB63SabrB1VaN6o24aTdRqZC5OvU51c07GOi1jq07SMtmGU09VaqumZqWSzSxAK5FI605Vufe+MsXNeGj5jCOFjLlVnfHd5TOOFjLmVnXG95bPeFshY66Q8b9HIeNCxkuwdjP+CQ3tm+E=

RNG Seed: 3346123836

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x13e940, 0x1cddec0})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Spell).applyEffects(0x31bf180, 0x32e18c0, 0x0)
	/home/runner/work/cata/cata/sim/core/spell.go:561 +0x4
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFuncSimple.func5(0x32e18c0, 0x0)
	/home/runner/work/cata/cata/sim/core/cast.go:236 +0x2e
github.com/wowsims/cata/sim/core.(*Spell).Cast(0x31bf180, 0x32e18c0, 0x0)
	/home/runner/work/cata/cata/sim/core/spell.go:547 +0x1d
github.com/wowsims/cata/sim/encounters/bwd.(*NefarianAddAI).ExecuteCustomRotation(0x38b55c0, 0x32e18c0)
	/home/runner/work/ca...

**Comment by rosenrusinov** [comment]
You're trying to sim the boss preset that is made for tanks Siming the Nefarian adds tanking. You should reset your encounter to the default raid one instead.
![image](https://github.com/wowsims/cata/assets/5707996/ffdc7f29-7de2-4f74-83c8-2f83b7a48289)
