### ISSUE TITLE
Crash Report -2145705395

### ISSUE THREAD

**Issue by AxPython** [wowsims/cata#711]
Link:
https://wowsims.github.io/cata/paladin/retribution/#eJzlkj9oFEEUxvd7b3O5jELGI8V4ILcuCktA2NtrYgp3kyplytgpxGBhIXZ2l+6ioodXXHKFcISAIMFgFU78s0HQwEWPK6KIIoiaQ0UFiUaI4OxuUmh3iJUfU7z5zffNGx4jDqchEeA0zqIEzALXgfvAM6ADFAklwhJhVEgMYQwT2pgxso97apwaP3Py/KlzOm5m30BkZOMpqy+WnboxZ5Zn2alBmPJWi0W//LbN6r1l86cqO2UIIb+2WH3PRZaMvPuT1aucndKHm9U4JuXlB6x+5GxTM8O5GJF72vVBk82IVKEvXdrgOLRzab+8rftfs3aZBu0NVtu5pO00RK9cXGanArFXvqibCb4a4WKHnYWoWF2O+wu58oTV2gGnDmGIPjn/jmO3vScNV43rIZSBwUUSWzD+U2XcbhPDxqjRQCprClJo0DHPLbiu5/6mI3+CGHoF7fXyemlFoUI+v0KH0jffkny5TupKSFYpJKcSkjsT0tClkIJOm8aabXpEZot6n5PxmnTXDk1Oc/KagaC+Ux0PLrBhN6kv3hWngn27jv21uUir/tGEtPyDU7HW/ZG1ZqSPvlcha0L1DP7jn+DMBN3Yi5MPu/L/jZLh3PkcjCT7Lf8EfgHXsJjq

RNG Seed: 1504668154

simulation failed: No random suffix with id: -225
Stack Trace:
goroutine 21 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x107ac0, 0x395aa90})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0xff5a, 0xffffff1f, 0x0, {0x3312100, 0x2, 0x2}, 0x0})
	/home/runner/work/cata/cata/sim/core/database.go:343 +0x35
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xebba, 0x0, 0x1070, {0x3312398, 0x2, 0x2}, 0x9a}, {0xf3ef, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x328dd40)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x321c480, 0x0, 0x3358b60)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x321c480, 0x0, 0x3358b60)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x31cedc0, 0x0, 0x33ff450)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +0x1d
github...

**Comment by 1337LutZ** [comment]
@AxPython When importing your link it seems to not throw an error. Could you provide a step-by-step to reproduce this?

**Comment by AxPython** [comment]
I cant reproduce it exactly right now because I'm having issues exporting items from my bag, but I was trying to use the batch sim feature.

I was using my gear preset I made, I imported gear from bags then deselected all except the belts and when I tried to run the sim it would hit me with an error and refuse to run. Then it gave me the option to auto post this to github so I thought I would if it would help.

I can try again tomorrow or when I can get bag export working properly to see if I can reproduce

**Comment by 1337LutZ** [comment]
@AxPython Good to know!
Would be great if you can then also post the import string you've used for your bag items :)

**Comment by AxPython** [comment]
Also attaching this crash report string from the crash just now:

Simulation Failure:
simulation failed: No random suffix with id: -225
Stack Trace:
goroutine 1271 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x98
panic({0x13a87c0?, 0xc001fd4010?})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.NewItem({_, _, _, {_, _, _}, _})
	/home/runner/work/cata/cata/sim/core/database.go:343 +0x69a
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xebba, 0x0, 0x1070, {0xc000cb6108, 0x2, 0x2}, 0x9a}, {0xe832, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x107
github.com/wowsims/cata/sim/core.ProtoToEquipment(_)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0x158
github.com/wowsims/cata/sim/core.NewCharacter(_, _, _)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x56f
github.com/wowsims/cata/sim/core.NewAgent(0xc0000a4ea0?, 0x0?, 0xc000c12700)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x10a
github.com/wowsims/cata/sim/core.NewParty(0xc00068e000, 0x0, 0xc000cb0780)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +0x1dc
github.com/wowsims/cata/sim/core.NewRaid(0xc001d2dd00)
	/home/runner/work/cata/cata/sim/core/raid.go:167 +0x1e5
github.com/wowsims/cata/sim/core.(*Environment).construct(0xc0000a4d80, 0xc001d2dd00, 0xc001d2de80)
	/home/runner/work/cata/cata/sim/core/environment.go:73 +0xfa
github.com/wowsims/cata/sim/core.NewEnvironment(0xc00007e800?, 0xc0015431d0?, 0xba?)
	/home/runner/work/cata/cata/sim/core/environment.go:54 +0x54
github.com/wowsims/cata/sim/core.NewSim(0xc000cb0730)
	/home/runner/work/cata/cata/sim/core/sim.go:189 +0x25
github.com/wowsims/cata/sim/core.runSim(0xc000cb0730, 0xc000709c80, 0x0, 0x0)
	/home/runner/work/cata/cata/sim/core/sim.go:140 +0x8b
github.com/wowsims/cata/sim/core.(*bulkSimRunner).getRankedResults.func2.2({0xc000cb0730?, 0xc000b98160?, 0xc0005f36c8?})
	/home/runner/work/cata/cata/sim/core/bulksim.go:383 +0x74
created by github.com/wowsims/cata/sim/core.(*bulkSimRunner).getRankedResults.func2 in goroutine 1267
	/home/runner/work/cata/cata/sim/core/bulksim.go:377 +0x79

**Comment by 1337LutZ** [comment]
@rosenrusinov Assigning this to you. I see -225 exists in the Database, however when importing this into the bulk sim bag import:
```{
  "items": [{ "id": 65370, "gems": [], "random_suffix": -225 }]
}
```
Makes it fail when trying to sim. Frontend resolves the suffix properly

**Comment by rosenrusinov** [comment]
@ToxicKevinFerm can you think of why this reforge is not found during bulk sim? I'm not that familiar with the reforge db building so maybe we are building only a list of reforges for currently equipped gear?
