### ISSUE TITLE
Crash Report 1735234297

### ISSUE THREAD

**Issue by DOnyaggg** [wowsims/cata#714]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzlUktoE1EUnfveNEmnQp+hyliEvA4IMVCZTBSqm0ziJoJK/YB1OTTTdnDysRkJdpUWF6m7aiVNUVBBUVBwIWiLC1Hxg6a0FYIKovihWQjFZKGlDTqTSUXQTRAX4nmb9+45597LvY/b5AICMgxAErIAEwBXAO4CvAAoAWQQZBHcQBBmLZGbab/fNIkd3bpyXB10NRPc/h44N3lexPwiFRzX8uxiDnsvA+ckswvYewm4VlI0yRIVsMVMAMeRuYeYP029Oct5p4r5Nx7BYZJLJp+z+OmbmF/yCMBwhEyZ/GuPYKVl7HQLV3FNXi/USsZXMD9GV2NmoLyA+RXPj4JOkl2utbKGjFWxsGpkydwKNsnhEvaOWmU/38Z8xWO14CTlW5hf9piX8aplFVyuJnFdN9vD+q4j7isw/yncYqOOHUwYJWESWA5xzDQKimJA/AWdUkAMBERJ8vsl0S+ZJyAF/J2/kd5DG12VAiLfCoj/UkB0ZAZ5ywXU9WEeyU/n0WPEzqKWV4h5hxAPJRQdxnYbW+UL9dth+SRmhDOO5tor0yevteNt8obJvIUnwe12ZDbY0VdDMRgqPLPwKSidx8mPD9BQyx6lP6akqbSNRmgPD76//Ce6T8iNyDPRR43od3edOxtqqJ+fUJtW5mJzKA/2AF8G67lY+RQcdYG7bVcsqegq3a8qvYaWiNODWkz17Y0k0lRPxPtpWtN1agyYAkWLUkM5olIjQeumiKpEqRanB9TeRDya2kK9oT5DHazptbhmaIpO/WJqc4dds02WplBydAQPrQ/rypBmpt+ZiKeMwWO9hr2tQ//6tpisb9+fbYvJVuR8fQRvV7fFyCJ8B4Xo2t4=

RNG Seed: 4219266641

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 23 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x13e8a0, 0x1cd8ec0})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Dot).periodicTick(0x30816c0, 0x33e8480)
	/home/runner/work/cata/cata/sim/core/dot.go:224 +0x26
github.com/wowsims/cata/sim/core.(*Simulation).Step(0x33e8480)
	/home/runner/work/cata/cata/sim/core/sim.go:526 +0x25
github.com/wowsims/cata/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/cata/cata/sim/core/sim.go:483
github.com/wowsims/cata/sim/core.(*Simulation).runOnce(0x33e8480)
	/home/runner/work/cata/cata/sim/core/sim.go:370 +0x7
github.com/wowsims/cata/sim/core.(*Simulation).run(0x33e8480)
	/home/runner/work/cata/cata/sim/core/sim.go:338 +0x3f
github.com/wowsims/cata/si...

**Comment by 1337LutZ** [comment]
Same as https://github.com/wowsims/cata/issues/677
