### ISSUE TITLE
Death Knight Incorrect Ghoul Scaling

### ISSUE THREAD

**Issue by Cazera90** [wowsims/cata#716]
This one I'm not 100% sure on but I think I figured it out. 

All of this was done WITHOUT the glyph of raise dead.

The sim is showing this for my ghoul's stats, 18102 attack power with only Horn of Winter:
![inherit](https://github.com/wowsims/cata/assets/171865119/a867138b-2790-4225-b485-d4fc46bbbd3c)

Meanwhile ingame my ghoul has 13010 AP:
![ghoulingame](https://github.com/wowsims/cata/assets/171865119/cd007aa0-0fb7-455f-b84e-6e756c0af14e)

In the sim it is saying the ghoul is inheriting 8585 strength which I believe is incorrect. When I use Horn of Winter I gain 720 str. My ghoul gains 1454 AP which seems almost appropriate for a 720 str gain. I don't know why its more, the pet sheet doesn't display str anymore.

The sim seems to show the ghoul having 476 base str. When my strength is added you get 6455 x 2 = 12910 AP which is very close to the 13010 on the pet sheet. I believe the ghoul gains 100% of the player's strength.

Also the Raise Dead for Blood/Frost have the same scaling as the base unglyphed unholy ghoul. I think on the current sim they both do have the same scaling but I'm not 100% sure. Frost is top and Unholy is bottom. Removed cloak as unholy so both have about the same strength:
![raisedead](https://github.com/wowsims/cata/assets/171865119/98fe1cf9-b7c0-4ce0-9998-7badc8841049)
![uhghoul](https://github.com/wowsims/cata/assets/171865119/c4df9b9c-acad-48b4-8f4b-ee98b3cb8a11)

**Comment by Cazera90** [comment]
After looking at the sim source code I found that the ghoul inherits 101% strength, has 476 base strength and -20 ap.

(((5979x1.01) + 476)x2)-20 = 13009.58 rounded up to 13010 is the exact AP my ghoul has.

I think this is causing the incorrect scaling, it is making the ghoul inherit 143.54% strength:
![ghoul](https://github.com/wowsims/cata/assets/171865119/b6c0fcdf-880e-442e-a967-48c2de90cff3)

**Comment by rosenrusinov** [comment]
@Cazera90 Can you also provide your ghouls AP in the same set but with the glyph equipped?
