### ISSUE TITLE
Crash Report 6223076

### ISSUE THREAD

**Issue by gkane1990** [wowsims/cata#728]
Link:
http://localhost:3333/cata/mage/fire/#eJzlVV1oFFcUnnPv7GbmZI03t9ZMrpWdTJuyDEZnZrMY87KrRWh9USkt6Ys/bZRSREKXUoIvUYzVQqExD9Y8tFjoT/ojsr4YoVSkVUvdsoY2SAsNlKQNrTSCFCNY0zt3ZsN2tT9B+tSzC3vPd/7P/WYW2w1gUIDnoQ8OA7wB8D7AOYCrADMAAwQOEzhFYINuQRdwTVxpGqHJLXt29u960WhkVEwBcjZWodas7ZgfHdenK3SiQnEpu3BC9+bvzEcCmGJv3qbWjO3QW8coNrDTZ6g1bEu/ryeoNZl2krPHlGUJOy2BQdsBLTMEyNjPMvdU2tGlXcu8DjLip1Gq3OU3825Y/hsZMWQ7yesRdiR0+u0StW6nHQUMheWHfqeR9h7I8tfPKLiBXbxAM++Eh8kpdUD22hi1bqTDsybhzyphhGMYCa9li96jux8TnAPtfyrcW2xEt7aB9MEI6EhQO0vynpf17pKOIOtls14Q+H7g+YH8ZIOs33EP1/PkEeNGmbCbZWLNl4l94CuSmfueeKPTpGtynBS+HCePT42TS0SvkMZvifYDOWRaFB9EQyRRN47+Co6JDZjoyK3OFfGBGD55ijoSRNrRGYJJIbu1mmPPIPRchg1C2o0fe2pQrgvSrfGHhEDmNhkJLrUwH5K1RZV3rAx/Y72zP8EtsRxTAtF4G8L0t54OLeyXzynvFAFm+KPY7C4NYzdpQnXoe8Uq9GwMBbn26nB8n+jHPr4X9/AXlJuuqkaRa4u40l0hI1PnweSEhQVP9go1j9o0pko1BlxSkg9XqOnG6HcEm0rQqNSE3IINaJYgnlFErfNXQBwE3Mf78WX+0r3Kt7otBuXm2YVAA+VJLfgvO/P/ubO7O+kTe3EXfw538u3Vbf2rNfi5xa6hWnGH2IZP8SdxK9+sKtKaK7u/8aoVVgkX23gazaM0nPbaTYLcZTE3jA9IRM+YpXy1WIUOtzHlSHIFybj5mIibYiLmIiJKS0REp46IxoeHEjxtgFhRT8OsV6w+OfwJ6bCxOnSVlJ1e+wFYIzMNbxM1NF7grNdev6bAK9aTvnuB4cX6/Os8RXr26VuEZ4W/EJX8U8L6KF9GheNNr+EbxWPYzbvqG5Me+LDbFs/aWiLLDeDGiNruIFT3PBjd+yDwlXI3NdcQOR5sEdEPN0X03rjKZkjvfhq9EzsLJ+LTM4VXqeZcJqbSBnYXmiN8WaF15HgoX+TXRUgl37ZbyUR+fflyKNfywTCxe6yE+x//H2WOFBbjPtB7cVH+9yPRcj6ZLayP9Ln8DvgDqzQ+qQ==

RNG Seed: 1144478949

simulation failed: No random suffix with id: -214
Stack Trace:
goroutine 1448 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x98
panic({0xfa87c0?, 0xc0314271f0?})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.NewItem({_, _, _, {_, _, _}, _})
	/home/runner/work/cata/cata/sim/core/database.go:343 +0x69a
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe839, 0x0, 0x106f, {0xc...

Import-String from addon:
{"items":[{"enchant":4113,"gems":[52207],"id":54505},{"id":66907,"gems":[]},{"id":55260,"gems":[]},{"id":56449,"gems":[]},{"id":56450,"gems":[]},{"id":56458,"gems":[]},{"id":56333,"gems":[]},{"enchant":4200,"gems":[52208],"id":58157},{"enchant":4115,"gems":[],"id":62361},{"enchant":4068,"gems":[52207],"id":60247},{"id":62352,"gems":[]},{"id":63498,"gems":[],"random_suffix":-214},{"id":62434,"gems":[]},{"enchant":4115,"gems":[],"id":62357}]}

works fine when removing {"id":63498,"gems":[],"random_suffix":-214}

**Comment by 1337LutZ** [comment]
@rosenrusinov Probably also related to https://github.com/wowsims/cata/issues/711

**Comment by 1337LutZ** [comment]
@gkane1990 Closing this. This has been fixed in the latest Web sim release. Todays local sim version (0.0.22 deployed later today) should also contain these versions.
