### ISSUE TITLE
DK Ghoul Crit Rate Too High

### ISSUE THREAD

**Issue by Cazera90** [wowsims/cata#729]
The sim is showing my ghoul as having 10% crit vs lvl 88 mobs while in game I'm seeing it as almost half that amount with a 600 hit test:
![ghoulsim](https://github.com/wowsims/cata/assets/171865119/6db100ef-1a6f-4d33-bb65-f46b33dfb216)
![ghoulcrit](https://github.com/wowsims/cata/assets/171865119/87514811-b068-4ee5-b030-eff8b618cd3a)

The sim is showing my ghoul inheriting 827 crit rating which is the rating after converting all my agi into crit rating. I believe the ghoul should only be inheriting the crit rating I have on gear which is 337:
![ghoul inher](https://github.com/wowsims/cata/assets/171865119/8066653b-fdac-4be2-8be4-5fd5e6c647a2)
![crit](https://github.com/wowsims/cata/assets/171865119/e3bff0cf-2ad6-498a-8301-db5c9a8fce9b)

I believe there might be something else wrong with ghoul crit chance because removing the 490 rating doesn't fully explain the ~4.5% gap between the sim and game. I don't if it is crit rating conversion being wrong for ghoul, attack tables being incorrect, or crit suppression. Or maybe something else.

**Comment by Cazera90** [comment]
Looked through my logs and it looks like Leader of the Pack 5% applies to ghouls and also the crit rate difference between melee and claw leads me to think the attack tables are wrong since in the sim both have the same crit rate. (100-24)x.121=9.2% crit which is what the logs show for melees.
![ghoulcrit](https://github.com/wowsims/cata/assets/171865119/cc151a48-1dbe-450c-a420-89c69c5a8aa5)

**Comment by rosenrusinov** [comment]
You sample size is very small to make an assumption that melee and claw are using different crit tables. To me they look like they use the same and its just RNG. I dont think LotP affects pets in-game and it does not in the sim atm. If you're seeing it affect them in-game we have to enable it for the sim for pets then.

**Comment by Cazera90** [comment]
I mean that the crit from LotP on the player transfers to the pet. It currently works that way on the sim. The only thing I think the ghoul shouldn't gain crit from is the player's agility. I will do more testing.

**Comment by rosenrusinov** [comment]
Ahh i understand what you mean. Yes right now the crit that the owner gets from lotp is transfered maybe that shouldnt happen. I dont have tests for that.

**Comment by Cazera90** [comment]
I removed all crit from the sim except the base 118 agi my draenei has and simmed vs a lvl 85 enemy to try and find the ghoul's base crit chance. The sim shows 10.7% crit:
![basesim](https://github.com/wowsims/cata/assets/171865119/c71bfb03-61a0-48e3-b6fe-566949dbc862)
![inheritedcrit](https://github.com/wowsims/cata/assets/171865119/562d524d-cb75-4fd7-8062-8fbf29c8e43a)


Then in game I tested vs the lvl 85 dummy with only my base crit for 2000 attacks:
![critnohorn](https://github.com/wowsims/cata/assets/171865119/b7a9d969-2459-4572-aeaa-3bdf80b6443b)

Then again while keeping Horn of Winter up:
![crithorn](https://github.com/wowsims/cata/assets/171865119/da0513d1-891d-4737-adf7-0665c9b3c8a0)

I think I was wrong and the ghoul does inherit crit from the player's agi.

I decided to do another 3k without horn:
![crit2](https://github.com/wowsims/cata/assets/171865119/e8984853-bd62-49b4-ac36-011388570e57)

Is there a chance the ghoul has the wrong base agility? It seems to gain ~2.3% crit from my horn of winter which is how it is on the sim. I think it just gains whatever crit% you have on your sheet. It could also be that the ghoul has the incorrect agi to crit ratio for its own agility. Currently it has 3333 agi and gains 1% crit per 324.75 agi.

**Comment by Cazera90** [comment]
I checked simulationcraft and it is just showing ghoul crit=player melee crit with no base crit. Which is definitely wrong.

**Comment by rosenrusinov** [comment]
Your ingame tests show that we have it wrong somewhere and I think you're probably right with the guess it is to do with base agi or the crit per agi formula. If we cant figure out exactly which part of the base is wrong I can just remove the agi to crit scaling from the ghoul and give it a flat 5% base. Considering there are no buffs that affect the agility of the ghoul that should work.

**Comment by Cazera90** [comment]
I did another 3500 and my total is now 8469 hits, 461 crits. 5.44% crit rate minus my .48% base crit is 4.96%. I think a base 5% would be close enough. I can't find any other info.

**Comment by rosenrusinov** [comment]
That data set is good enough for me to just go with 5% base.
