### ISSUE TITLE
Crash Report 1569997388

### ISSUE THREAD

**Issue by Chertus** [wowsims/cata#730]
Link:
http://localhost:3333/cata/hunter/survival/#eJzlUk9IFFEcnu/31mn2YfgcCsa97OxkMAjF29kOWwgzetqjR7sZmHiIkE51U7qoBEVGrnsIohIJiq4GQQTZP9tZ9uBKQoFpeBBK8OAhpDc99WCnJTr1nb7v+33v/X7v8eMnLQhEGMYIxoEyMAe8BJaBDWCUME54RuhNWyjpiG1kxswKM/suXbh28YqVFpT5Bm6Lmw3mbLme+XgmtTXN/EfgrWK3zDy2rVQFvE0sVZmz6WpDlblYm2fOByvhbWJb8S9ZXSyDHxVVZXx2PRj+bCIbSt7tSOStJL4yzzxTZffuskX1Rsq55x54s0mosaAaZg8atoqf+/P8oVLi6xrjR8TrBeZPQJHKU+Zcz3EjGTNmTs31p+Fxi+TxPuqngZauJ8R3YPynsGWzJ84ZvTSCSUh+mp8Q2cwxiwSKLEKJDbOrevcop7M/Qon2j4sJNsPn1C0L8jBOBQUZHPZkIVC2SifFIB/kC/n8K+q0bsckHqyT83Cd3KmY/HJM8k5MxUadopU6ld7X6S1ZNeKfyFgl7sAz7RQnbmzQ4BjTMxWj+3vsfDTJDG+R0lpejto1ORN1VGYSvAvPaqcW5oZ+Yyns2X9OMEVuv9PS9Y93x5+ImomPDr5pKv830J/z4nvUo/VOOIBf8lqiiw==

RNG Seed: 1964005605

no base result for equipped gear found in bulk sim

**Comment by 1337LutZ** [comment]
@Chertus Closing this. This has been fixed in the latest Web sim release. Todays local sim version (0.0.22 deployed later today) should also contain these fixes.
