### ISSUE TITLE
Suggest Reforges not working properly when using resilience bracers as a Feral Druid

### ISSUE THREAD

**Issue by bmking1124** [wowsims/cata#733]
**Describe the bug**
Reforge not working when using resilience bracers

**To Reproduce**
1. equip a bracer item with resilience
2. suggest reforge
3. it does not calculate hit/expertise properly

**Expected behavior**
it should reforge to my hit and resilience cap, but when i use resilience bracers it doesnt work.  when i swap back to pve bracers it works fine.

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/cata/druid/feral/#eJzjEuNgzGBsYGScwMi4gpFxByNjAxPjBiZGJyYPRiEGqaXss5jZAnISK1OLONgEGKXOMXIJCey/wCzxUUGJc9VMlqcXmB9eYObiFzi8kMXg97//EMDIxSOw+w+zxBsFJeYv05m52AWunGeWOM0BVPf/GrPEfXklNqAwSIZLYP1NZol7CkqMDFy8AhuBeu7KK7EAZRi4xAVu/2M2mAo3E66HX6DhOrPEDSW4AI/AD6DGe/IQy1gEZj0HkWdmsgDJlhcgdscOkCPm3GeWaFbkYuDiFJj/kxmsWomXg8lAMoApgqkCFAJaa5m4fjAyjFAgZECqDisGJ4YsFikmBcZdTI4GWICukbGRgbGRkbGhkYGhEQgaGBkbGOoaAEUNDNEUH2JS4Vj4hEng2H4miaP7mRQO7mfSmNfPYnB2P5PFrKtMDocvMXkcv8R0gonlAhPHLSaGR0xvGCWYlJ4zct1jrFZKSk0sCk9NLEtVsiopKk3VUcpNzMwrAWK3xNSizFS3zCKETGaec35uUn6xW35RUGaBkpWpjlJpcWpQYjZcCZDrlFkC5yYB2SGZuUC+oSGqfogqU4gSl9KizLx014rU5FKE3qLMAp/U1PLESqBmsN6g/MQi/7S04tQSJSsjSx2l4rzUbFSXp+akpiKJ1AqxcDFxMbxg8m5khgS8pcNCKCvSoYuZQekMEyeEm+cgCGHoOUjOmgkCJ+0tISIX7BXTwOCavSNE6qW90WQmhQgJVi0aJ3qNTgdSlDekHCdJPSUAEjh73zs4Qvg/7BMYAVGH6y4=)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Firefox
 - Version [126.0]

**Additional context**
when i use resilience bracers it doesnt work.  when i swap back to pve bracers it works fine.

**Comment by 1337LutZ** [comment]
@bmking1124 Could you post screenshots of what you are seeing?
Because when I open your link and press reforge I get near perfect hit and expertise caps.
![image](https://github.com/wowsims/cata/assets/1216787/5c803135-79be-4a44-8667-5b5f1124f67b)

**Comment by bmking1124** [comment]
Hey,

It is actually working this morning.. oddly it didnt work the past two days
i tried reforging.

Thank you for the quick response.

**Comment by 1337LutZ** [comment]
Happy to help, closing for now. Feel free to open a new issue if this issue comes back.
Make sure to once in a while reset your settings, we sometimes ship updates that are not backwards compatible.
