### ISSUE TITLE
Crash Report -426309764

### ISSUE THREAD

**Issue by Lenzord98** [wowsims/cata#759]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzlUT1IJDEYzZdvdm6N6OWWE6LNrFMNgjA7Y+M1E60sLbVT8MTiCjkruxUs1Cv0sNh1Owv1BAvhChdBFFFUUFhB18NGkBO3ONhFLfxBMXHstBG1upcQ8r7v5b2QsFoJPdALQwBpgF8AKwB/AAoASQpDFOYpNBscJMRIzXIkg2brt87+r9+jBseaY2AxPrqGohi3zbkJYzCNzjSwD3y3iM4UsI/8tIiiELdRd2aAMf47iyIZd37qk3t5FEeWbV6lUE0nBayCn8yiuLVsIJpyfqAkfy1bOxPtWMlHSmibo2n8oRz7VMJ+XnHV1g5pHXmRQ3FihZFTOnLsFEXJcsb0xUpZ1NkGP8iiWq9zqATzJRTnVig+W0BxY2mNye+UuM+ORiNuVavRZtStU3YJ5D9FrOWtnL6QZtoLGTAYZWSRStd1ffcJ6j3f9X3X8xIJz014avien6h/RrpKySY1crT8kJJjSgUUaNcAhlkNcvJx1y5HkNjbtOyBJbvlp7D+WVZnJjS2gsawkgtqux+QD5p2tjX+Bd44jbeJSN07/78zLF8iT3ZtvEj/GoSPs1SUTSG/DDrgHtPChvE=

RNG Seed: 0

When validating reforging for item 63498, the reforging could not be validated. 115
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x107b40, 0x3880a10})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0xf80a, 0x0, 0x0, {0x380e838, 0x2, 0x2}, 0x73})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe20f, 0x0, 0x106f, {0x380e810, 0x2, 0x2}, 0xa6}, {0xf7d1, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x3876b40)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x33990e0, 0x0, 0x33a8000)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x33990e0, 0x0, 0x33a8000)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x3882160, 0x0, 0x33da820)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +0x1d
github.com/wowsims/cata/sim/core.NewRaid(0x3892080)
	/home/runner...

**Comment by 1337LutZ** [comment]
@Lenzord98 It looks like you have an outdated import link. If you try to change the belt to the proper reforge and export again it should work.
Please create a new issue with a bit more details if you can't manage to fix it as described.
