### ISSUE TITLE
Crash Report 280702184

### ISSUE THREAD

**Issue by BerrysLive** [wowsims/cata#762]
Link:
http://localhost:3333/cata/mage/fire/#eJzlUk1IFHEUn/f+47aOB6dli8nL/h0KtgVjdrbAuuysXTaosA/IjoM76tDsRzqx5Emlw+YlCmJdMagg6VDQrY9TRPZBbpmVVAeVMNxDIeIhJaH+szNCUBepDtGby/u/9/t4vDfCNj+IoEEX5KAAMARwHeA+wFuACkAfQgHhFkIL74ACXMN0zTDxtVr6aaObEUnDNAgB8dUUkRao7LtR4leKJHwNhA3ixHw1qRenWLNCZbLAOkNO5+UjEi46tNesMxOSfazj0FhNEMfuEGklJAMniOLIPJHmQjJfKBIuPOpoDa6SKnyh6Em8YRLnmfO5oTX9evHmKpFWQ67hqGP4Yt5Lxl1nXuyvEPacmfNmXWSmSyHm/plRv4bcMSu3HZbs99com1r5Nj4yhsIycP9pBJJ/SmkP14I5GAZeQIG7h3FFiSk/RZMaU2IxRVWjUVWJquyLqbFo0y+gD3Cr/1sZxS9llJbKSAeeY3ixjMryNDbPTKL2bBKTc5P4BPkJrHuP3AdECSqY6ifuODu1K152XBsknHzRV1t9zea0jW49qG0ZLjnxNL7brUzEGzuqMRVPlMed+BRXL5Pcx4fYW3dA70zrearuoknaJkHkL/8zrWe09cD7Uo/Xg9/ffGkksa55fojqtvqu1iZK4C7wXdzT4rULcNIPgeC+dE63DHrY0NttM5uhR820ETmYzOaplc100rxpWdTuYgDdTFFbP2FQO0s9UtLQU9TM0CNGezaT6tlBw4kO2+iu4s2MaZu6RaNKz/ZG1zOoqXcxd3aA9G5usfRek8nvzWZ67O5T7bZ7rWP/+rW4QuTQ712LKyxpJW8Fs2vX4jQFvgPD5N1W

RNG Seed: 3411437582

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 94 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x98
panic({0x1a623a0?, 0x3fa6e70?})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.(*Dot).periodicTick(0xc0003ff420, 0xc00011a120)
	/home/runner/work/cata/cata/sim/core/dot.go:224 +0xac
github.com/wowsims/cata/sim/core.(*Simulation).Step(0xc00011a120?)
	/home/runner/work/cata/cata/sim/core/sim.go:526 +0x14e
github.com/wowsims/cata/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/cata/cata/sim/core/sim.go:483
github.com/wowsims/cata/sim/core.(*Simulation).runOnce(0xc00011a120?)
	/home/runner/work/cata/cata/sim/core/sim.go:370 +0x30
github.com/wowsims/cata/sim/core.(*Simulation).run(0xc00011a120)
	/home/runner/work/cata/cata/sim/core/sim.go:338 +0x2f3
github.com/wow...

**Comment by 1337LutZ** [comment]
Pretty sure this is related to: https://github.com/wowsims/cata/issues/677
Something with Magmaw big add encounter
