### ISSUE TITLE
Warlock Spell Tooltip says it's a Mage Spell

### ISSUE THREAD

**Issue by jones1973** [wowsims/cata#772]
**Describe the bug**
In "settings" -> "raid buffs" -> "Misc". "Dark Intent" is a Warlock spell, but the tooltip indicates it's a Mage spell. Can't imagine it'd have any effect on the final DPS number, but could cause some confusion.

This is on a chrome web browser

**Comment by rosenrusinov** [comment]
We dont control the tooltips. That is a blizzard/wowhead issue out of our control
