### ISSUE TITLE
Suggest Reforges - Not Working

### ISSUE THREAD

**Issue by DevinDyer24** [wowsims/cata#792]
Bug Description:
I've been using the Suggest Reforge feature via the Sim Options > Show Experimental check box. This has worked amazingly until today. Now, all I get is a spinner inside the Suggest Reforge button. I've tried clearing, refreshing, and changing things, but I have the same result. 

This just started happening today. 

![Suggest Reforge](https://github.com/wowsims/cata/assets/7153243/91fdd41e-408a-4478-aba3-52cdfc0ce430)

This is fantastic work; thank you for creating this!

**Comment by 1337LutZ** [comment]
@DevinDyer24 Can you provide the following:
- Export Link so we can reproduce it
- Which browser you are using (Operating System as well)

**Comment by DevinDyer24** [comment]
I deleted cache and reset everything. It's now good and working. Thanks for the quick reply. I am using Chrome.
