### ISSUE TITLE
Hyperspeed Accelerators dont seem to import with /wse or in website.

### ISSUE THREAD

**Issue by IOEggception** [wowsims/cata#796]
**Describe the bug**
importing my gear from /wse addon doesnt seem to be account for engineering enchant on gloves, Hyperspeed Accelerators. 

**Expected behavior**
I went to import this, which in game has Hyperspeed Accelerators enchant on my gloves, but it doesnt come in on wowsims website.  So i just manually add it, but still a bug it seems.
{"talents":"000000000000000000-3312212300311212211-3320200000000000000","glyphs":{"minor":[{"spellID":58079},{"spellID":58094},{"spellID":58070}],"prime":[{"spellID":56218},{"spellID":56228},{"spellID":63303}],"major":[{"spellID":56240},{"spellID":63320},{"spellID":63312}]},"class":"warlock","unit":"player","race":"Orc","name":"Dothappy","gear":{"items":[{"id":59449,"gems":[68780,59479,59493],"enchant":4207},{"id":57933,"gems":[]},{"id":60252,"gems":[52207],"enchant":4200},{"id":59457,"gems":[],"reforging":144,"enchant":4115},{"id":65262,"gems":[52207,52217],"reforging":144,"enchant":4102},{"id":60211,"gems":[],"reforging":145,"enchant":4089},{"id":65259,"gems":[52205]},{"id":54503,"gems":[52235,52207],"reforging":167},{"id":60250,"gems":[52205,52207],"enchant":4112},{"id":59234,"gems":[52207],"reforging":151,"enchant":4092},{"id":58188,"gems":[],"reforging":144},{"id":63494,"gems":[],"random_suffix":-114},{"id":59326,"gems":[]},{"id":62047,"gems":[],"reforging":165},{"id":65041,"gems":[],"enchant":4097},{"id":59484,"gems":[]},{"id":59314,"gems":[],"reforging":117}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"demonology","realm":"Mankrik"}

**Desktop (please complete the following information):**
Chrome, Windows

**Comment by TheBackstabi** [comment]
Accelerators (and all other Engi Tinkers) are NOT enchants, and thus are not on the enchant UI. You can apply a regular enchant + Engi tinkers onto the same item.

They are listed under the Settings tab, in the Engineering section.
