### ISSUE TITLE
Crash Report 1895089946

### ISSUE THREAD

**Issue by nosoju** [wowsims/cata#800]
Link:
https://wowsims.github.io/cata/hunter/survival/#eJzlUj1oFEEUnvfe5twbESeLwuQKb29FWALK3p7FKcJOUl2ZMnYRoqQQCVbaXRDhPEUODvKHiMFfrLQ7RCFoxB+iuwS5ExtBCKQI5ATBFAk4m1ELrYJa+THFe+/73nvfDMMP2CBAwRiMQw1gGuAewDzAe4AVgCpCDeEBwmDWhoqROCw3kZmlzNDpE+dPnrWzAnMxcEfMJyQ/u172/ozVTqiTEN8hns1Zfh34btF+S3LV9ejLFPl3gXPxLiY56aaxIxodkh/zXkaTG5q/k/Jf10he3OcB40I0NT/Z51maZ/5Uyj5eIJPq7qtdktfdn91X0nWXF/S6vFmnx1mi2k3tbLa2eEs81O4sUWuRntXYJHmh4N8GzrSkpX3FrrfLxmDvEA7jSE8DoP858nVg/ymcyt+adJQN4jjUIeCH+H6Rz+2xUUCZFFRojM6Z/4cFo+1GAfS+WUyxGj3CY0Ep+BUHw1IQ/l4LU6lm9AmLYbFULD5F1765jOJGjPLWMrrXYvSbMQbTMZZfL6HqLOFLtBLc+QHZJ+QSvIxjceRsBUcnyPgpq7nv0XFVJ+YtYtakZ1SvCQ6rvtmZFK+iI6aSRIVTW2hHAz+uEjbRHZY9/f/4P/mX1Hbk1dEX29L/CczjPFlTAyZfj0bgG2N/mkc=

RNG Seed: 3060176482

When validating reforging for item 69827, the reforging could not be validated. 138
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x1085e0, 0x334f350})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0x110c3, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x8a})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe840, 0x0, 0x1071, {0x3315b70, 0x3, 0x3}, 0x0}, {0x110c3, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x33c2780)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x31658c0, 0x0, 0x33b2fc0)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x31658c0, 0x0, 0x33b2fc0)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x31e5b80, 0x0, 0x33b4f00)
	/home/runner/work/c...

**Comment by rosenrusinov** [comment]
@nosoju did you happen to follow an old link from someone? This error happens when you try to open a very old link that has wrong random suffix/reforging data. If you have any information on how you get to the state where your Tot4W items have reforges but not a selected random enchantment please re-open this ticket. If the bug happens just from following and old link there is nothing we can do and you just need to update your old setups with correctly selected random enchantments
