### ISSUE TITLE
BDK Haste Value

### ISSUE THREAD

**Issue by Notdoomn** [wowsims/cata#804]
**Describe the bug**
BDK Sim is incorrectly values Haste in the current SIM.

**Expected behavior**
There should be haste breakpoints where the rotation can more effectively get more death strikes in. I’m not a math guy - so I’ll leave the math to the experts.

**Comment by rosenrusinov** [comment]
Haste does affect rune regeneration in the sim and the more haste you get the more Death Strikes you get in the sim. Can you provide any evidence of this not being the case so we can look into it?
