### ISSUE TITLE
Crash Report -2046310800

### ISSUE THREAD

**Issue by BGannon2** [wowsims/cata#811]
Link:
http://localhost:3333/cata/paladin/retribution/#eJzlkk9oE0EUxvd7bxvT6cFx8TDm0jUoLAVhs7lUD91tTz32WG8KtXjwIN68RQRJVTQQaNIchApCQcRejSiuSLUQJVSsRfAiSIMVWyiVBvw3uxsDegvSkx9zmPfN73vzGEYcTUMiwFmcRxGoAgvAE2ANaAEFQpGwSBgTEsMYx6QGLSPzpq/GqYlzpy+euaDjZmYDwpL1t6y27Gzq7pxZqrJTg9gnN9fZqUDsl1+/sfpkZ/lLhZ0ShJDbTVazdkRZ8vF3Vld0Uh/uVDqBG89YtQdjTy8NPdDtN7qGU42gxXXuGqWo00MN3bK73kIEvV5i9WMwuToeankpvsOS17bYLf7sCE4ZwpRrr1gjhRY7dyK2ree+bAtD9MvbbY6bZAfScNWEfosSMHSPxC6M/1SW22vihDFm1JHKmIIU6jTiuXnX9dw/dOxvIza9vGa9nF5aUSifyz2lI+n7H0m+XyV1MyS7GJIzE5JbDmm4tULB9ZDGGyv0gswmDbwj4wORohZNXeJkmoPBfGd3MrjKRrZB/XFVmA4O/CYO1eYiLfvHE6fpH56OteqPvmxE+ux7ZbInVd/QHv8EZyboBS9MPe+J/xclj/NoMxhN6l3/FH4BjmGiTg==

RNG Seed: 565449413

over 1 million combos, abandoning attempt
Stack Trace:
goroutine 96 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.(*bulkSimRunner).Run.func1()
	/home/runner/work/cata/cata/sim/core/bulksim.go:69 +0x49
panic({0x13387c0?, 0x2cf40f0?})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.(*bulkSimRunner).Run(0xc000116100, {0x2cfe7a0?, 0x393b060?}, 0xc0004bf920)
	/home/runner/work/cata/cata/sim/core/bulksim.go:184 +0x1445
github.com/wowsims/cata/sim/core.BulkSim({0x2cfe7a0, 0x393b060}, 0xc000355e40, 0xc0004bf920)
	/home/runner/work/cata/cata/sim/core/bulksim.go:41 +0x71
created by github.com/wowsims/cata/sim/core.RunBulkSimAsync in goroutine 49
	/home/runner/work/cata/cata/sim/core/api.go:61 +0x94

**Comment by rosenrusinov** [comment]
> over 1 million combos, abandoning attempt

This should not produce a reportable error but just not allow you to batch sim. @kayla-glick 

We will get a ton of issues opened with nothing we can do if this opens a bug report
