### ISSUE TITLE
problem with sim fire mage

### ISSUE THREAD

**Issue by qvortx** [wowsims/cata#814]
[**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
](https://wowsims.github.io/cata/mage/fire/#eJzlkktoE1EUhufcO02T6cJrCDp2k9tBIQYqk4lCdZNJ3ERQqQ+wLodm2g5OHiYjxa7a4iJ245s2RUEFQVBBcNOKiypaFRsbCy1akIokGEGo2kUVWnQeEQXdFHUh/rM59/zfPfdwznAb3EBAhi7IQB5gCOAqwBjAc4AqQC+CPIKbCGKsBXmZxpd1w9jVqitH1azbQ3DjLHBeMlrC/DwVPNcLbKWEZ0qYqyd3R3BgELhVZHIE81Uq4M+DdoIjz8Yxf4ZasZfcWcb8nF9wzQ9+92/NYP6NXwCGI2TU9Mt+gTV9JnDFKjc9iW183sG9ZNrET1HBdWLIzg1Z0I0lzC/5BTth3qonE+M2XU/em20NWMFc2bZY0lfF5qNvFzHfZzfFmObZZcsUGtx14tpWto09CRB8gLhPwPyn8sb/VKVtTAxlYBhYDnHMbRQRxbD4k5qlsBgOi5IUCkliSDK/sBQONf8CvYfWuxeLiCwUEf+liGj/UxT4UETixyJqeTKF5PIUil+roEeILaGGWcS8RoiHKkr0YaedzfKlWnRQHsCMcM7lsU9jWXm1k/fJ64YLlh5HtjqZUqSpw9ZMJFqcsPQuIl3Emcp91NOwS+lMKt1U2kLjtI2H4F/+Z1qPySvBexMPV8LvbLlwPrqifn6QPa3ey55oAZwBvojUarHyaTjsBq9vRzKj6CrdqyrthpZO0f1aUg3ujqe7qZ5OddJuTdep0WUCipaghnJIpUaa1i7FVSVBtRTdp7anU4ncJhqIdhhq1ua1lGZoik5DYm5jk/OmT5ZGUeZ4P+5ZE9OVHs0svz2dyhnZI+2Gs60D//q2mHxwz+9ti8kvyIXaCF592xYji/AVxv/b+Q==)

**Comment by 1337LutZ** [comment]
@qvortx This is a known issue with the Magmaw encounter. Best to use another raid encounter for the meantime.

**Comment by qvortx** [comment]
Thanks i will try other boss.
