### ISSUE TITLE
Crash Report 1455893409

### ISSUE THREAD

**Issue by KyoxWins** [wowsims/cata#820]
Link:
http://localhost:3333/cata/druid/balance/#eJzlUjFoFEEU3fdnb7MZA06CwuZAbl0QlkBgbtci2uxeKsuUZ6cSg4VFEBu7szuDimDgLgdCYiEWCtcZBFlRiAp3egSNMQoHcpAIwgk2CSI6s2slNodY+aaY/997f+YxDD9iQyDGOcyjCtSBu8BjYBPYASqEKqFJmBYCUziBsrI1U3XMyK/lGsyaOX/60tkL9rBA/gP4ftF8xZy+61n3lsx+jfEh0dlm/m2trL9kTs/1mKL9OjgX1RXTWTjkL2pxb4M53YJnfamxq3WmxE8PmAfDvwYuxHcl9gqePtDI7K+3mWepVp9VAx8V35Tluptyat6/yEfE5ipzlsfT+1SMGyqGGh0SrbW0MMWPjua7vTQeF20V/GvBv6M9t1aZLkbE8h7LAi/Cs+2cPDhjls2J+8R3YfynGJODThw3pnPz+s+csfImJ248pFIYBqEMgmIxSJfaZXFSFuUfMCkDGYa/S0/ItbcSEm8Tct4n5LYT8itdku8Smmq8ofjpOj0nq0P7tsj4SORgh2YvsyzQ0XjlV3UyXmCG16LhtKvMxaMZfyAebyxpvIiOZUwnOjyXYiMqtVsan6PgJrllJzfxjz+DfyUexF6ZfTaQ/2+QPc6jflzK+t3oFH4CtomXFg==

RNG Seed: 1509199646

simulation failed: No random suffix with id: -215
Stack Trace:
goroutine 136 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x98
panic({0xb54780?, 0xc0004bf420?})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.NewItem({_, _, _, {_, _, _}, _})
	/home/runner/work/cata/cata/sim/core/database.go:343 +0x69a
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe7b0, 0x0, 0x106f, {0xc0000b3928, 0x2, 0x2}, 0x0}, {0xf3d0, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x107
github.com/wowsims/cata/sim/core.ProtoToEquipment(_)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0x158
github.com/wowsims/cata/sim/core.NewCharacter(_, _, _)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x58f
github.com/wowsims/cata/sim/core.NewAgent(0xc00013cb40?, 0x0?, 0xc0004e81c0)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x10a
github.com/wowsims/cata/sim/core.NewParty(0xc00025fa20, 0x0, 0xc0004c4af0)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +0x1dc
github.com/wowsims/cata/sim/core.NewR...

**Comment by 1337LutZ** [comment]
@KyoxWins Can you try again? Importing that link works fine for me.
Please make sure to have the latest version.
