### ISSUE TITLE
Crash Report 1251277287

### ISSUE THREAD

**Issue by ibimcoll** [wowsims/cata#826]
Link:
https://wowsims.github.io/cata/druid/guardian/#eJzjEuVgdGDMYGxgZJzAyNjAxLiBifECE6MTpwCjBaMH4w1GRismAUYhBqknbLOY2QJyEitTizi4BRil9jNy8QususasxHZsBvOkGcwafYxcLAIHe1i4eASmHWNWgomxC5w/BmbwC2w7D1Q9CaJ6MSMXl8CpncxKjAwaUxm5eAUePmdWYgHKQLk3gVIsfSBuO0hr/weg1j64RTwCn05ArZgKsvYA0Fp2gTs7oNwb25mB3Mk7wNawC8xaB9bEANQ2/ydcmxIXB7OBZABTBFMCq9ZRJq4fjAwjFAh5UMskKwYnhlXM3FKcghC+nsMuJkcDLEDXyNjAwNjIyNgQiIB8QyMjA2NDQ10DIAUWQAaHmFQ4Fj5hEpjTzyJxZD+TwsH9TBpn9zMZHNjPZDHrKpPDsUtMHocvMZ1gYr3AxHmLiVNw1kwQuGn/iKmdUYJJqYmRq7BaKTcxM68EiN0SU4syU90yi1KVrEqKSlN14DIuqbn5RYk5mVWZeelB+YlFMPkUoHhIZi5QvYmOUkFpThnQgKpUhEhRKlAwJ7gkMbcgNQVqaq0QLxcTFwPcKS+YUn4wMS5khoRLpEMXswhnKAjM3+sADSwmBwU2pTNMnGBOQxpMWMRBEmLISXtLiMgFe8U0MLhm73j2DAi8sTeazKQQIcGqReNUrNHpQIryhpTjJKmnBEACZ+97B0cI/4d9AiMAe5a8YQ==

RNG Seed: 1109790724

simulation failed: When validating reforging for item 63503, the reforging could not be validated. 142
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x108ec0, 0x334f1a0})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0xf80f, 0x0, 0x0, {0x330fa90, 0x2, 0x2}, 0x8e})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xeb2a, 0x0, 0x0, {0x330fa60, 0x2, 0x2}, 0x8e}, {0x10641, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x33b9000)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x31b5c20, 0x0, 0x33be380)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x31b5c20, 0x0, 0x33be380)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/...

**Comment by zoristaken** [comment]
What tool did you use to import your gear? If none, could you tell us what steps you took to replicate the error?

**Comment by ibimcoll** [comment]
I used the weakaura export button, that show up when viewing ur gear.

**Comment by zoristaken** [comment]
The weakaura is not supported or created by the wowsims team. The creator needs to update it to handle random suffix items. I would suggest using the [addon](https://www.curseforge.com/wow/addons/wowsimsexporter).
