### ISSUE TITLE
Tinker

### ISSUE THREAD

**Issue by ibjonnyc** [wowsims/cata#827]
Synapse Springs is not listed.

**Comment by rosenrusinov** [comment]
Synapse springs is available in the tinker options once you select engineering as a profession. 

Synapse Springs are not an enchant as it seems a lot of people confuse tinkers and enchants

**Comment by ibjonnyc** [comment]
and yet hyperspeed accelerators is a tinker option listed under enchants.
Weird.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rosenrusinov** [comment]
That is a leftover from wotlk when hyperspeed accelerators were an enchant and not a tinker. Try being a smart ass in another way.
