### ISSUE TITLE
Chimaera missing Froststorm Breath from rotation.

### ISSUE THREAD

**Issue by Firsthunterz** [wowsims/cata#833]
Kinda self explanatory. https://www.wowhead.com/cata/spell=92380/froststorm-breath. The only abilitys that show up when simmed using Chimaera are Bite, Wolverine Bite, and Attack.

**Comment by 1337LutZ** [comment]
@Firsthunterz It will only cast this ability when the encounter has more than 4 targets.
Most likely because it's a DPS loss otherwise.

**Comment by Firsthunterz** [comment]
I have 4 targets active in encounter and still doesnt show it being used.

**Comment by 1337LutZ** [comment]
@Firsthunterz More than 4, so 5+
