### ISSUE TITLE
Lightning Well Belt of the Undertow isn´t include on Wowsims Cata

### ISSUE THREAD

**Issue by Chemonguito** [wowsims/cata#835]
The waist Lightning Well Belt of the Undertow who is a item drop in The Conclave of Wind Heroic it wasn´t include on the wowsimis cataclysm.

**Comment by zoristaken** [comment]
![image](https://github.com/user-attachments/assets/b8f78f6a-4a32-412c-b57e-6a6aac74cc48)

whenever you select the base version, go to the random suffix tab and select the version you want
