### ISSUE TITLE
[MAGE] Talent Piercing Ice is not updating UI stats

### ISSUE THREAD

**Issue by Cajovajo** [wowsims/cata#837]
**Describe the bug**
When I add points to the Mage's talent Piercing Ice, it didn't increase my crit chance in stats 

**To Reproduce**
1. Go to Mage talents
2. Click on Piercing Ice 3x
3. Check stats before and after, it didn't show up increase

**Expected behavior**
It should increase crit chance by 3%

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.]

Without the talents
(https://wowsims.github.io/cata/mage/fire/#eJzlkT9oFEEUxue9t3cmo3LjEWFyza2DxRAQ9nYtNM1uUqW01E4hBguLYGcXmxC1SEKKu5xYpNAEkl4NsRH/4i0sgifYKOGOnCCcXookcMk5uyv2IVr5TTPz8c3vfczwXAA3YBJmACoAKwCjLM8KLzNVyl66ee329Vt9GUGFDvC8eBaRbNuqf23RqkfUjIgfE5tbpB8BPyHqdZItW1G7TPy0eL9kOb2DXiqQC7aejwkb+ySnbZU1ob0y6TngJ0WnS3KvqIDFHCE+GU6jqCwTSZyC+HpAzoM/LJWdrdD9SnI5Jz6a9JwB/igng3Ois0WyWVRkQroCpmDtNelyXHB+n5J2+jFwSzzsxu2/NJL2XHzbIbldjJnM2K0npJdBsaFXyHeB/afKj/0t0jAbxUmogsWRs3UcdBzvnOs5nue4bqnkOiXXLM/1Si/wbN92iGInRNkL0f4Zou6E6HRDvPC0TcFqE8caH/AtWhEe/4xsE1FCC8fvUDrofLD0e3cluEdM1bA/OU1NBKdSfyAYrC7GeudfTJ3IPzORqO6PhLVY3313Ae3LMjP0jz9f3w0OE58af3Oo/FGUPs7zdjCSnnf9q/ALNNOdug==) 

With talents:
https://wowsims.github.io/cata/mage/fire/#eJzlkT9oFEEUxue9t3cmo3LjEWFyza2DxRAQ9nYtNM1uUqW01E4hBguLYGcXmxC1SEKKu5xYpNAEkl4NsRH/4i0sgifYKOGOnCCcXookcMk5uyv2IVr5TTPz8c3vfczwXAA3YBJmACoAKwCjLM8KLzNVyl66ee329Vt9GUGFDvC8eBaRbNuqf23RqkfUjIgfE5tbpB8BPyHqdZItW1G7TPy0eL9kOb2DXiqQC7aejwkb+ySnbZU1ob0y6TngJ0WnS3KvqIDFHCE+GU6jqCwTSZyC+HpAzoM/LJWdrdD9SnI5Jz6a9JwB/igng3Ois0WyWVRkQroCpmDtNelyXHB+n5J2+jFwSzzsxu2/NJL2XHzbIbldjJnM2K0npJdBsaFXyHeB/afKj/0t0jAbxUmogsWRs3UcdBzvnOs5nue4bqnkOiXXLM/1Si/wbN92iGInRNkL0f4Zou6E6HRDvPC0TcFqE8caH/AtWhEe/4xsE1FCC8fvUDrofLD0e3cluEdM1bA/OU1NBKdSfyAYrC7GeudfTJ3IPzORqO6PhLVY3313Ae3LMjP0jz9f3w0OE58af3Oo/FGUPs7zdjCSnnf9q/ALNNOdug==

**Desktop (please complete the following information):**
 - OS: Widnows
 - Browser Chrome
 - Version 126.0.6478.127

**Comment by 1337LutZ** [comment]
Just like with Balance I will modify the character stats in FE to indicate this.
The talent itself however is working

**Comment by 1337LutZ** [comment]
@Cajovajo This has been merged and should be on Web shortly. Thanks for the report!
