### ISSUE TITLE
Missing items: Librams for pally

### ISSUE THREAD

**Issue by rehaynes62** [wowsims/cata#839]
Since the holy pally isn't currently able to be simmed, I am attempting to store my h-pally gear set under the ret profile  Everything works well except for the libram selection in the ranged slot.   No librams are available for selection.

**Comment by hillerstorm** [comment]
Just storing a gear setup is better handled on either https://sixtyupgrades.com/cata/, or if you want something sim-like https://questionablyepic.com/live/.
