### ISSUE TITLE
Crash Report -266156065

### ISSUE THREAD

**Issue by mathwro** [wowsims/cata#841]
Link:
https://wowsims.github.io/cata/hunter/survival/#eJzlU11oFFcUnnPu7O7dE9vc3CZ1vIRmM/1bF6MzsxtYg7hjnrb6IvTFvrVgg7QVrPNS3yIWiVIhtIXEPCWp1GJfimArQkFK1apts6SwDVIq2ASlWKzggw8m9d6ZHYg/YBDfeh527/3u933n586lVzkICGEX7IERgHGArwDOAswB3AAYRhhB+AZhMM+hnlCkpY63TbDs9g/e2ffuXp4TqP4AkuJsgzm3C27+xFG72WALDUa2uPwjo1Wi+StzbhZcdmeMUU4cnLKdy1wLjtxjztUeN6vhe2OseAjoOfH5aeb8WXDBKo4DCTEyx5z5HtfW55YhtIu5JeZmb48ZL0NR4toS875d+i8JcObc1FCTm7e0W0+cuPgl6NyLp1nxE7OYuM6KY6Ar/Gve1HTufJw/J0YXmXOglywisfgdc2YKmu62cfS6tuMOHAUonUO6C9b/NGT9WTkNWIO4Bw6DR+vpZdGjOjkK8KDK6mwX+8h8Z6OAvQn335oHHb/8bOJm7Qxu8srew9EXlD3/YcwrBxrWbP0bBH7glwP/B3yFf7GAYnIGnWMLWDi+gMXxGfQ+m8Hq77MYXprFenMWf0K7gfwKWtdwMuMAvUA5lSHG77zvcsqS3Rf0RxrMKpvQ6XDzlKNMn7++ElEXcaUJ/MJVezmcGvwz1DLwvYhkC/ybu5pIrK9siIn+yDRrgZVIvqg6SZSe5xmJA5Y5JvSjAUsW1WvUrRRlLiFyoI5SO7clbrVUrNQ1Gq6YOs9ihzZTUGASnmmP8/7WKUkl6a5PMvkxqP1AkfyQeGCwU5OM1pVKPCv5e6296j6JazjI/AlMESLdkJn97ojyE7BcaK9E2K+Fbrwmu9/fHclBFZIvN5AqOZxpQWqp4nEGhh93mpHsU7s1jUplbxvlp1Oq3KrqtFltolXG+YFm2EqbUanXWvU6vSS74wvIxtONU1Yj4tNgxnilWyV/0tyFKS27rLSqF5/Or5bb1BsUys2PMCpe7G0/4L261KVJy7qPD8pRapZenP7ObuDO/Sx5KtVwqrV6KzzMLHce8/FueCjsSPDOcM3EURMXaxsTpFHrHYqjWduSvrLgayzscDKlUXxWD/6xUTwUPo1seOeFJ+jefCrflUQytO9vhVuS/d3a23AftvgIIw==

RNG Seed: 1208601348

When validating reforging for item 65368, the reforging could not be validated. 152
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:50 +0x10
panic({0x108ec0, 0x334a890})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0xff58, 0x0, 0x0, {0x33e1c18, 0x2, 0x2}, 0x98})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe840, 0x0, 0x1071, {0x33e1bf0, 0x3, 0x3}, 0x0}, {0xe24b, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 ...

**Comment by zoristaken** [comment]
What tool did you use to import your gear? If none, could you tell us what steps you took to replicate the error (this is tied to the random suffix items from throne of the four winds)?

**Comment by zoristaken** [comment]
see if you're having the same issue as #826
