### ISSUE TITLE
new "Batch" Feature causing crash consistently

### ISSUE THREAD

**Issue by heh947** [wowsims/cata#842]
**Describe the bug**
Everytime i try and use the new batch feature at the top it crashes my .exe and freezes the sim
**To Reproduce**
1. start the wowsim.exe
2. click your spec
3. click on batch
4. import your gear from the wow sims exporter addon bag option
5. scroll down and set gems
6. click "simulate batch"

**Expected behavior**
batch sim to run

**Desktop (please complete the following information):**
 - OS: Windows 12
 - Browser: Firefox

**Comment by 1337LutZ** [comment]
@heh947 Could you post your wowsims link and also the Bag code?

**Comment by heh947** [comment]
bag code :

{"items":[{"id":56380,"gems":[]},{"id":63441,"gems":[]},{"id":56339,"gems":[]},{"id":56285,"gems":[]},{"id":56267,"gems":[]},{"id":56349,"gems":[]},{"id":75065,"gems":[]},{"enchant":3722,"gems":[],"id":63448},{"id":56458,"gems":[]},{"id":56333,"gems":[]},{"id":67126,"gems":[]},{"id":63482,"gems":[52208]},{"id":63802,"gems":[]},{"id":57921,"gems":[52235,52235]},{"enchant":4063,"gems":[52207,52207],"id":58153},{"id":56311,"gems":[]},{"id":56281,"gems":[]},{"id":56385,"gems":[]},{"id":56344,"gems":[]},{"enchant":4092,"gems":[52207],"id":59234}]}

wowsims link:
https://wowsims.github.io/cata/warlock/demonology/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnfgEGD0YI4CKNoDlhBikjrDOYmYLyEmsTC3iYBfgkDrDyMUvcP89sxLbmpksH6Yzayxl5GIXOHuEWWM5IxePwPkdzErMP4HCExi5OAVuvGeW6JLVKOUSElh5jFnivrwSG1CuewZYF6/A0R3MEnOElBgZNCaC9P4CmgoykgGogV/g+UqgHUClINXLQZa+WsksMUFBCSwwASTw6ByzxB95JZh57AK9O8Ay7AJ7gIyJIMbkHVCp48dganaC1TBwsQhM/MysxMHBaiAawBLBonWUiesHI8MIBUIe1DLJisGJtQCUdiYxsXGxcDFxsO5isjLAALrGxoZGQGBsYGBsaGAEZBsaAsWMDIxQ1R1ikuC4fppJ4MFpJokrT5kU7j5l0nh8msng5lOmE0wsF5i4bzExPGJikmB8wZTygWkaYyMzxBmWDgshrIYwhy5mBqUzTJwQbpqDIESFnYPkrJkgcNLeEiJywV4xDQyu2TuePQMCb+yNJjMpREiwatE4aWh0OpCivCHlOEnqKQGQwNn73sERwv9hn8AIANggjDs=

**Comment by 1337LutZ** [comment]
@heh947 20 items for the Web sim is just too much. Try downloading the local sim here: https://github.com/wowsims/cata/releases/tag/v0.0.42
