### ISSUE TITLE
Fire mage wont show Gear

### ISSUE THREAD

**Issue by ChapsMongoose** [wowsims/cata#850]
**Describe the bug**
When I imported my firemage's gear the sim stoped letting me change my gear. then I reloaded and now it wont show any gear. wont allow me to put on any gear but sims like I have my in game gear on.
**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

![Screenshot 2024-07-16 120455](https://github.com/user-attachments/assets/0522ccaf-2b93-46eb-8545-187c80da2ad7)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChapsMongoose** [comment]
I do use the WA I think, forgot it wasn’t an addon.  I just erased my
history to before using it and it fixed the problem

**Comment by 1337LutZ** [comment]
@ChapsMongoose great to hear! Closing the issue 👌
