### ISSUE TITLE
Crash Report 644921648

### ISSUE THREAD

**Issue by Baabaganoj** [wowsims/cata#853]
Link:
https://wowsims.github.io/cata/rogue/subtlety/#eJzlVV9oW1UYv9+5N8nN59KcnaaaHhGy6ybXO6snN02XdnNJN5XSp6E+1IexFdtZi3SlFUSfsg10U9BOxbiCQvfi8EXJXjQwHIJEXSWjwjoVX4bDKQWZ9CFC7Dz3T9okLcM5ffLjEs793d/3+/7eG9ymA4UcjMEkHAd4F+AMwHmAywDXAPIEjhP4mMAejEvSAAxJGlN4ns6qwX3PDb84OqWHaJDPEGT0uz/V+PWEEfzwlFYrqOZJkFh1ThN/rNzwDMw3AaP0B8lbShiqQ5JAB601keIXdI+3KHkvS73lgkPFCJ2tqfHTWwxQzA8AKb0sn7/TaWjyuWK+5kQrX1KNsOQuu5fDuodeXVHFJ2vi768KmjNOkKrUPCGTcfhnHI1FyW/OOERLNbccjS7XVPl7VP4i/VR6Hks4QZBWC5pzdsnlmlOWEdGJ6NxHhshBbQbA+oJgFZT/qbGBf0upT9mj/AoxZHIdIE4Sqhl79Jv5+YfFjFoiO4WdEkJeDdYlhC1arEukUrZIJVN2MpUUImnLw+dkq/5jhdDFConPV0jiQoWY5atEfFshmd8XSO76AhmoLJAvSegi0b4nyhWyFI6rMo8QD6CqnzWNEMpDV8+0g407WDXiY/b0Ku/niTWsHfXxIGr62c80H0xOswzvQfUoKPZDvsdPe1HnDu1GHjDINSR62kfmXiH+aeVIgO3l/ZhhPUiNNtxUhDAj1PEvRJFabXqQOaqOIkLaR8ig4ngjSQruUdnTfBjbrxCKbU+MDY8cfiFxeHJydGJ0yh70Ix15W/VPX79H1lJsORRpC0JrO1cRluYptJi5QV4xi+ka89pXiHpoj6/IBvkA7ma78E4rJknhEvjN82ipv1Wm78Ke51P4LHsGO6x2qaWXwBui59jtOkKTVNSK+FIukMHt/P6NvW3XW2PkJT9sSvgrwu7mneuzrJd3EvjrgMeAyTlvNqIYKcrPkTNDTf/oXAAjxh0YLkJ9BpsMRL0I3p6tLxR38T4XVRtCdeN9bOs6dLVN9Xwzor5vrJfvwC62vTGXN8qBDST0WfCGW18NluO7sZvVm7HGtVvDpUVzMfU1Y+N8DA+w/cituFSIlBpTaG71zdVv1jm3+efbmOAP4jZ277rKbHfwAUb6fCDpv8bsAW5tvK5TrDWHHWl2gO/HJ/nj/3QkvenmrZd1NKYj36nH+CO3M/PetPdlYXfxDq9Dp8FrjRvgl4lrZGRO9b7BT+VeVRVjnoTdu/yh3GYPj+U6Z0859lW210MuZrcccu1Stl9+paUtZe23SGIoHrD+439D80TuVuj5kfIt8W/HvOac+y3X791XswfhL4wNXlI=

RNG Seed: 642467597

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 12 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x1401a0, 0x1d09060})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*APLValueSequenceIsComplete).GetBool(0x39bc810, 0x39b2fc0)
	/home/runner/work/cata/cata/sim/core/apl_values_seque...

**Comment by kayla-glick** [comment]
This can be resolved by updating your APL from using a strict sequence to a regular sequence with the same name as the condition below.

![Image](https://github.com/user-attachments/assets/77a39d56-1aa3-448e-bbe4-1f71c0c28b5d)
