### ISSUE TITLE
Cant add engineering enchants to gloves (Synapse Springs)

### ISSUE THREAD

**Issue by IOEggception** [wowsims/cata#858]
**Describe the bug**
Cant add engineering enchants to gloves (Synapse Springs).  It also doesnt import with wow sims exporter.  

**To Reproduce**
Open up gloves > Look at enchants > see that "synapse Springs" doesnt exist
This needs to be an additional secondary enchant too, since we can still use regular enchants on the gloves in addition to the engineering one.

**Comment by rosenrusinov** [comment]
synapse springs is not an enchant so you wont find it in the enchant menu. It is a Tinker so you can find it in the tinkers menu in settings
