### ISSUE TITLE
[Retribution] Tricks of the Trade not applied

### ISSUE THREAD

**Issue by MattZeeX** [wowsims/cata#860]
In the Ret sim, when you apply add Tricks of the trade as a Misc Raid Buff under settings, it does not actually increase the damage of the Ret pally.

With just one tricks it appears to get instantly cancelled, and when you add multiple tricks it seems like they don't all get added? Can't really see it in the timeline but under the buffs the number doesn't match the amount you selected.

**To Reproduce**
1. Sim a baseline
2. Add a tricks of the trade in the raid buffs
3. Notice DPS doesn't change, check the timeline and see tricks of the trade immediately gets cancelled

**Expected behavior**
A DPS increase and tricks to last the full 6 second duration

**Comment by 1337LutZ** [comment]
@hillerstorm I believe this is due to the fact that the APL doesn't have this APL entry set, thus it will never cast manually controlled cooldowns.
![image](https://github.com/user-attachments/assets/90e2e037-9d3d-429b-8240-e633ad4a415e)

**Comment by 1337LutZ** [comment]
@MattZeeX For now you can just add Tricks to the Default APL in the Prepull section:
![image](https://github.com/user-attachments/assets/332e8009-7539-47a8-b6dc-25944e26d30f)

**Comment by 1337LutZ** [comment]
> > @hillerstorm I believe this is due to the fact that the APL doesn't have this APL entry set, thus it will never cast manually controlled cooldowns. ![image](https://private-user-images.githubusercontent.com/1216787/350931745-90e2e037-9d3d-429b-8240-e633ad4a415e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDcxODcsIm5iZiI6MTcyMTY0Njg4NywicGF0aCI6Ii8xMjE2Nzg3LzM1MDkzMTc0NS05MGUyZTAzNy05ZDNkLTQyOWItODI0MC1lNjMzYWQ0YTQxNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTExNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ0YTEyYjUyNzc1ZmM3ODIxMzQwMmU2ZWMwYWIxYTNlZmJlNjQ1MjcxODYxNmU0NDdlMDljOTZhMDhmNzM5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aGYDJYjNbIzWZI2HfsVlqJaym6bRhYmFnccW7Tnq0dw)
> > It probably needs that entry, or just like Bloodlust, add Tricks to the prepull
> 
> Is an `If: <None>` entry for auto cast needed? There's two places in the rotation where I pop them, I just don't ever want to pop trinkets "whenever possible" :D
> 
> Doing the change you suggested is a -500dps loss because it pops trinket

Yea I noticed, I think adding it to prepull actions is best, like you did with BL.

**Comment by 1337LutZ** [comment]
Or actually, that will only allow you to receive it once... Perhaps just add it as a first priority cast so it will always cast it on CD

**Comment by 1337LutZ** [comment]
Like this: 
![image](https://github.com/user-attachments/assets/eb5fdc5e-12f8-4dae-893b-91d4be98e370)
