### ISSUE TITLE
Fire Mage Gear page is empty and uninteractable

### ISSUE THREAD

**Issue by lambertwang** [wowsims/cata#861]
**Describe the bug**
Fire Mage Gear page is empty and uninteractable

**To Reproduce**
1. Download latest windows client
2. Run windows client
3. From home page navigate to fire mage
4. See error. 
  a. The gear is empty and no gear can be selected.
  b. Importing a gear set does not fill in the page
  c. Other classes and specs do not have similar issues.

**Expected behavior**
The gear page is not empty and is usable.

**Sim Links and Screenshots**
![image](https://github.com/user-attachments/assets/2d1e476d-fde9-4e60-a6f1-e56ca1e7b9a0)

Sim settings: No change from default.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 128.0

**Comment by lambertwang** [comment]
I looked through some older releases and found the issue comes up between V0.40 and 0.41. Maybe related to #840

**Comment by 1337LutZ** [comment]
@lambertwang How are you importing the gearset?
Locally the client still uses the browser to store preferences, thus once they are bricked they stay bricked.
If you open a new private browsing window, you will see that the Sim works properly.

Reasons you encounter this are:
- Importing using the Weakaura which is unsupported, put on private and doesn't have the latest Mage bugfixes, thus bricking your settings.
- Importing using an outdated WSE Exporter addon (or cached, so try to uninstall > reinstall the addon)

To properly reset your settings I would suggest the following using the Chrome DevTools and press **clear site data:**
![image](https://github.com/user-attachments/assets/21f0f37d-b26f-4cee-aeff-7ee031319e24)

**Comment by lambertwang** [comment]
Ah, It worked after clearing cookies and site data. Thanks
