### ISSUE TITLE
Elixir of the Master is not properly calculating block % for prot paladins

### ISSUE THREAD

**Issue by calaris0099** [wowsims/cata#863]
**Describe the bug**
When using Elixir of the Master the resulting block % displayed does not match the Blizzard UI, nor does it match properly match the popular tank stat weakauras such as Tankadin. It is understated by approximately 0.50%.

**To Reproduce**
1) Add gear. Match against Blizzard UI. Observe matching figure to Wowsim. 
2) Add Elixir of the Master in the Wowsim and in game. Observe the mismatch between the Wowsim block% and the in-game value.

**Expected behavior**
Block % values should match.

**WowSim without Elixir of the Master - 64.14%, matches WoWUI (see attachment)**
https://wowsims.github.io/cata/paladin/protection/#eJzlUk1oE1EQ3jdvjcla7TMEWYvQ18VDDFR2Nwg1l2ziJYJK/UM9Ls22Lm6TmK4Ue5BQCqkVPCjSHxWtePJQxZuCQtRqxIohYvCHgghtcxBBRFo1FV+yrXgN6kH8TvO+mfm+YeYJnpcIlREqAIqChkJcCAjyck3XVoxhV7ulHzfSbkz4pjwSGsnpChY/UMk1OYLnh7HgIfdLWMLfWLiGTC1icZZKODuC/SeEleT6HBa/NgtekmeJLGtaHK7lMkgQyDwTmqYS4oTV5GMBi6eoxDMZTmggdytYcrG4qtpIcqx5ouUn0UDOs87vzY4pT548xIKLTFSqljx5Ualy2TJm9s+fYbGfsmBgnBc/N7NZr35xZpW4wCQIC4j7T+GN/SmlEBeFFLqJ+CYQuNuwoTWoympQVoKKqiqqosiKGlRaZcYG1Xuw0T2UA3JjBsTpEtCzOfDPFUF+U4K2chG0qSLEZouQB/YT3a+BewcgojLEFwCNY8fukDaEfZ79VVy6o611SNCoSzrn8tQemc5l2qetHxut4nF4q8MUwi2dNZTCkadTVbwPq5dxauYB9K3aqXd1671U3UJj9KCIAn/5d7QPaPWUZ+KP6qnf0XbxQqSueX5BbVuZK57IKHIW+Cq8pMVrZ9BRN/L6tnendMugewy9wzaTCbrP7DYCu2LJXmolE12017Qsah9mBboZp7Z+xKB2ki41xQw9Ts0E3Wt0JBPxns3UH+m0jXSt3kyYtqlbVJF7NrU4nj5NvQWpk/24b13U0vtMJr8tmeix08c6bOdaB/71a3GDgd2/dy1u8JM2urSCt8vX4jQZ/QB0b86l****

**WowUI without Elixir of the Master - 64.14%**
![WowUI - No Elixir](https://github.com/user-attachments/assets/56733045-fa65-4d0c-a52b-e343e4d89938)

**WowSim with Elixir of the Master - shows 66.96%, correct value is 67.47% (see attachment)**
https://wowsims.github.io/cata/paladin/protection/#eJzlUk1oE1EQ3jdvjcla7TMEWYvQ18VDDFR2Nwg1l2ziJYJK/UM9Ls22Lm6TmK4Ue5BQCqkVPCjSHxWtePJQxZuCQtRqxIohYvCHgghtcxBBRFo1FV+yrXgN6kH8TvO+mfm+YeYJnpcIlREqAIqChkJcCAjyck3XVoxhV7ulHzfSbkz4pjwSGsnpChY/UMk1OYLnh7HgIfdLWMLfWLiGTC1icZZKODuC/SeEleT6HBa/NgtekmeJLGtaHK7lMkgQyDwTmqYS4oTV5GMBi6eoxDMZTmggdytYcrG4qtpIcqx5ouUn0UDOs87vzY4pT548xIKLTFSqljx5Ualy2TJm9s+fYbGfsmBgnBc/N7NZr35xZpW4wCQIC4j7T+GN/SmlEBeFFLqJ+CYQuNuwoTWoympQVoKKqiqqosiKGlRaZcYG1Xuw0T2UA3JjBsTpEtCzOfDPFUF+U4K2chG0qSLEZouQB/YT3a+BewcgojLEFwCNY8fukDaEfZ79VVy6o611SNCoSzrn8tQemc5l2qetHxut4nF4q8MUwi2dNZTCkadTVbwPq5dxauYB9K3aqXd1671U3UJj9KCIAn/5d7QPaPWUZ+KP6qnf0XbxQqSueX5BbVuZK57IKHIW+Cq8pMVrZ9BRN/L6tnendMugewy9wzaTCbrP7DYCu2LJXmolE12017Qsah9mBboZp7Z+xKB2ki41xQw9Ts0E3Wt0JBPxns3UH+m0jXSt3kyYtqlbVJF7NrU4nj5NvQWpk/24b13U0vtMJr8tmeix08c6bOdaB/71a3GDgd2/dy1u8JM2urSCt8vX4jQZ/QB0b86l****

**WoWUI With Elixir of the Master - 67.47%**
![Elixir of the Master Added - WowUI](https://github.com/user-attachments/assets/1cf5de80-b9f0-4f7d-8982-1e77c18aa199)

**Comment by 1337LutZ** [comment]
@calaris0099 Your export links don't seem to include any Consumable configuration (I double checked both).
![image](https://github.com/user-attachments/assets/01a9105a-d4d9-4b12-aa38-d3b87837ee3e)

**Comment by 1337LutZ** [comment]
@hillerstorm Weird thing is that also ingame the Flask seems to give `1.48` Mastery points but `225 / 179.280040` should be `1.25`.
I took a second look and found out that we are not applying the bonus from Alchemists. 
This increases the Elixir value from `225` to `265` .

**Comment by calaris0099** [comment]
> @hillerstorm Weird thing is that also ingame the Flask seems to give `1.48` Mastery points but `225 / 179.280040` should be `1.25`. Edit: I took a second look and found out that we are not applying the bonus from Alchemists. This increases the Elixir value from `225` to `265` .

Great catch! I didn't even notice that Alchemy bonus myself. Thank you!
