### ISSUE TITLE
Fire Mage Import Does not work

### ISSUE THREAD

**Issue by Serverfrog** [wowsims/cata#884]
**Describe the bug**
When Importing Equipment, or changing it, nothing happens in the UI.
In the Javascript Console, an error is thrown

```
Uncaught (in promise) TypeError: s is undefined
    Bn http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    Bn http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    Bn http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    getTalents http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    s http://localhost:3333/cata/bundle/shared-BTkyPsjP.chunk.js:1
    modifyDisplayStats http://localhost:3333/cata/bundle/sim-CFqrd8OY.chunk.js:1
    updateStats http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    vr http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    emit http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    onAny http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    emit http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    onAny http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    emit http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    parties http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    emit http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    playerChangeListener http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    emit http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    onAny http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    fireEventInternal http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    freezeAllAndDo http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    freezeAllAndDo http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    freezeAllAndDo http://localhost:3333/cata/bundle/detailed_results-BsmoS6T5.chunk.js:1
    finishIndividualImport http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:2
    onImport http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:2
    Lm http://localhost:3333/cata/bundle/preset_utils-DKpxPYFQ.chunk.js:2
```

This is On the Web Version AND the local hosted one

**To Reproduce**
1. Go to 'Fire Mage Sim'
2. Click on 'Import Addon'
3. Import the Equipment Below
5. see that nothing changed
6. Reload to see that no equipment is there

`{"talents":"0003000000000000000000-231330221110121213231-0300000000000000000","glyphs":{"minor":[{"spellID":57924},{"spellID":63093},{"spellID":57925}],"prime":[{"spellID":56368},{"spellID":56384},{"spellID":56382}],"major":[{"spellID":62126},{"spellID":56373},{"spellID":56365}]},"class":"mage","unit":"player","race":"Human","name":"Falearielle","gear":{"items":[{"id":56460,"gems":[68780,52217],"reforging":144,"enchant":4207},{"id":62434,"gems":[],"reforging":165},{"id":56399,"gems":[52217],"reforging":144,"enchant":4199},{"id":58193,"gems":[],"reforging":144,"enchant":4096},{"id":60244,"gems":[52207,52217],"reforging":144,"enchant":4063},{"id":56389,"gems":[],"enchant":4065},{"id":60247,"gems":[52239],"reforging":165,"enchant":4068},{"id":54503,"gems":[52217,52207],"reforging":167},{"id":60245,"gems":[52208,52207],"enchant":4112},{"id":62450,"gems":[52239],"enchant":4069},{"id":58188,"gems":[],"reforging":144},{"id":56432,"gems":[],"reforging":145},{"id":62047,"gems":[],"reforging":165},{"id":58183,"gems":[],"reforging":165},{"id":56441,"gems":[],"reforging":138,"enchant":4083},{"id":56306,"gems":[],"reforging":145,"enchant":4091},{"id":56296,"gems":[],"reforging":167}]},"professions":[],"level":85,"spec":"fire","realm":"Lakeshire"}`

**Expected behavior**
Equipment is imported and usable

**Sim Links and Screenshots**
Link after reload http://localhost:3333/cata/mage/fire/#eJzlUj1oFEEU3vfe3mUdA04OhTHNroPCEgjsj4Xa7CRVypSxMxCDhUWwszutYhBMSJHkOgtR0cIuURBEyEXxVpOgUSwMOS7cFcLFpPCChc7uHqTQJphU+ab55nvfe+9jGHbOAg4KrsEYjAPMAjwCeAXwBaABUEQYR3iG0G8mpoLRXc2VKD94ffjm1RtWjlP3BrACv/ucRNOR+adz5u4MuZPAOni1Tu4DYCf4hwUSdUdSu8L4SplE0Ul4gX9cI7Fuy3xzZq++qBs2bAkG4/yzrtdsad6bJSMbV39MMq+9usN9mAiftGVSL99KNdbJt+skNm1JukfnqJTbgbYWyJ1KyHotTdbBl8opYXxXb9yx3YmEb8+T+GVnzsZ8skNaVs47NWgOmT2LyFpgHFEUBg5q0iWjH8egBCZDZrxA5Xle6P2F3iD0w9ALAt/3PT/QJ9RK7z+sr/GstRMj/xmj+B2j0/qG7u336P2I8cK7VVRPNnGgtopv0FzG41/RqCIKaODILcrynFf32+yymiBDVvBYeiuOqq5MP6lOl+YSvI0uZspydGY0xVrUF1cSfI+CaXSGRK7nkP+Ie0ftx14cWdqX/3+QPc7LpurL7q3oCvwBhmCY8A==

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 128.0.3 (64-Bit)

**Comment by 1337LutZ** [comment]
@Serverfrog Please make sure to use the Addon and not the Weakaura.
If you are using the addon, and you are sure it's up to date; Please delete and re-install it.

When a talent string of a Mage starts with this `"0003` it indicates you are using the WeakAura or an outdated addon, as there was a bug fixed 2 months ago that ignores the hidden Mage talent that was never added.
