### ISSUE TITLE
Simulation starts and then gets stuck after a few iterations with an error. "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by dmyates5** [wowsims/cata#885]
**Describe the bug**

Simulation gets stuck with error after a few iterations. It starts for a min and then gets stuck no matter how many iterations I set it to. I'm getting an error that says "invalid memory address or nil pointer dereference".

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

https://wowsims.github.io/cata/mage/fire/#eJzlVUtsTFEYvv85d6Zn/rbc+VW1B6lOMyI32t650wkayQxCygYRUhuUEhGRxkSksalHvZYkQjfCyiNBJrHQRDQSKanXShp2TYjEKyyoDc65j2aMdxAL/+Kc//zvxzd3MCnAghxshi44CHAc4AzAAMAwwFOAHgYHGVxiMN/URmTIt5V9PLpsa0f3xu2i3OKyA7l1Zi6a1psBrs79x7gSXGxX7OuXHKPWUF0CDCyzPu4xNRO17jXpm1vXFqtj1FKGQ3tNdR4/pv33Kt5Qd89l7t1DAzwhRMSZuMxsN+1BVgM4CsZ/StT2pyK1GvNZF/SBiQyNflbe6KaddNpx3VTqOjNuMvM+K3/IjBH2IqYmPhGFjKIpjryERAzLMNKYacrkcUIgvnCJJ5QQeWOLFkaliloTDyxdbVmFZVLpxZP2IimZkrUaNEVKtOxxIkLqpeMhm5X34l65A9/RftgdoRpZjRUSUZwGHf79Kq2xnt3g1CJdnEHTMW6P175LDOlVmHLyoWh9IHIzybA52iW7sYu24Vba4pmZXlbfc1Yep9qTlWfFdYgRs3TCC53S6yftKMKKQpECKwuA3ssUZx8xHFeAcu8ZUVOYBhgrQNCj9EunAyD3Ae6ibtxJO76WvtaeJDjF+sccBSrOG/A3K0v9uLIvK+mS23AjbcAOWhtO66fGkMr86hjCjOvkGlxJK3A5LfUy8qKV/V57YYaZ0sZ6qsPYEa67ff6OIdlWgA1xjvnwDFBKzbIRG6geK0fM4uoDJC4JkJjxkag0PhITJUgU5/dHqE6AnFyKw7STD386tFgZLAy7DlHZ4iT3QLOKdHSNLMLxGGidZOmcXCdfivrWMYjnS+PPcTzUW9dOMkrL1JhX9LOApV4p5aXbe9xMnXI9ttEinGDHg8a8hWSa9L6SdoMCb1WBxQWQ2BIMSfJ+MzBzPDPhBppENX7VmBbKBdhKs0vbV3Vgg10fJK4tsGrt2uctsRfCdfb68OoFmqo2ULRt33DfJOlfFJP+52nYeso6d3P/E9mSOxVwq3OHuZG4y9og5r17NuXivqYqV9t3QtOt7Bxfcj9bv8mjB9l5d25rep51j7Jp7TUR+x//cc04lPsbYXs6B38Y1x/O1Ve5ef57NLsOPgHBfv20
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 1337LutZ** [comment]
@dmyates5 This is a known issue regarding the Magmaw encounter and Dot spreading. Best for now to not use it.

**Comment by 1337LutZ** [comment]
Actually, it looks like your equip is corrupt? The link you sent shows no gear equipped and broken talents. Did you export using the Weakaura or a outdated WSE addon?

**Comment by dmyates5** [comment]
I’m using the WSE addon. I just installed the addon yesterday so it should be updated.

**Comment by 1337LutZ** [comment]
@dmyates5 Good to know. Do the items show up in your interface?
This is what I see with your link
![image](https://github.com/user-attachments/assets/25fde987-0a26-478d-8b4a-55a3e06fddf6)

**Comment by dmyates5** [comment]
Yes it does show up. I’m unable to take a screenshot of it right now bc I’m at work, but it did show my gear.

**Comment by dmyates5** [comment]
I was finally able to take a snip of my gear. 

![image](https://github.com/user-attachments/assets/04fbe18b-b68b-4b36-80a1-a5f7e42a7f70)

**Comment by 1337LutZ** [comment]
@dmyates5 This is not for Cata is it? This looks like gear for SOD?

**Comment by dmyates5** [comment]
No this is Cata. I don't play SOD.

**Comment by 1337LutZ** [comment]
@dmyates5 I am actually not sure we support that. The Sim is intended for endgame simming, so lvl 85 and Heroic dungeons/Raids.

**Comment by rosenrusinov** [comment]
We dont support levels lower then cap.
