### ISSUE TITLE
Prot pally HOTR cd incorrect

### ISSUE THREAD

**Issue by Amordrone** [wowsims/cata#889]
**Describe the bug**
The hammer of the righteous spell on the prot pally sim has the incorrect cd. The current cd is 0-1.5 sec (effectively 1.5 due to global cooldown). The cd should be 3 secs.

**To Reproduce**
1) Set target number to greater than 3 using default rotation. The nef add default encounter works for this.
2) check timeline to see HOTR casts being used every 1.5 secs unless at 3 holy power where SOTR/insp will correctly be used over it.

**Expected behavior**
HOTR should be cast every 3 sec at most due to its cooldown.

**Comment by hillerstorm** [comment]
Fixed in #890
