### ISSUE TITLE
Crash Report 1959855629

### ISSUE THREAD

**Issue by heh947** [wowsims/cata#895]
Link:
https://wowsims.github.io/cata/warlock/demonology/#eJzlUj1IHEEU3vfe7t5mDDo5CExsbl0QFiGwt1dpkV2trrSSKxVUUqSQdHZnE4yi+BNyel2KkARS2EYwJEE85VSukIsGg8F45ArhjtgYOIgztzaSwiYhhR9TvHnfe9/7mHms0wIOITyEMZgEWAJ4DfABYB+gCpBFmERYQehr5ZCGjCxaaXJxrb1s5MnsfzQ0PvLYinGr/RBYnB+USdRsx3y7rNdy5L4EFuM76+ROAWvjh5Ks2g4pJg+M8Y8lEou2O6fI9zI+SjhmPUe/ciTbfjbIAY1xvi/bThKOEtRU7W3+4w055vQSySNnPmuQmJMzJa+U55Xa8S6JRiIalVPGntTJm/19CXBfKWPbG6T0Yvzo5NJqYaMZMD7zjsRZQrEa0/n8GTmWZXh3+/WM3lVAAewctBuKePpvKfVofcaY2qYFNJnO0DJWscf7A/dTqaQvkfK8VNLzZZxMypzv+VfrPqGwPheRfyui2Kug/bWC7vciegcV3ES9hC1fUDtG+XlVHK7jc5igyEZ3+CKKsgPhFGnOLqbhVpQYDe9ENQ/Ce/llha2gO8qUgo7RJspB7862wmngL6KdEUbXf14O92n4L2Szw4VrdaPHWauFvdH9PBiEC7RSmss=

RNG Seed: 1694737210

Couldn't find proto field for talent #57, full string: 000000000000000000-3312222300310212211-3320200000000000000
Stack Trace:
goroutine 104 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x1102a0, 0x3b1a790})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.FillTalentsProto({0x423338, 0x38adb00}, {0xb4a72040, 0x3a}, {0x12, 0x13, 0x13})
	/home/runner/work/cata/cata/sim/core/character.go:703 +0x36
github.com/wowsims/cata/sim/warlock.NewWarlock(0x339a000, 0x4877a40, 0x49de7c0)
	/home/runner/work/cata/cata/sim/warlock/warlock.go:135 +0xe
github.com/wowsims/cata/sim/warlock/demonology.NewDemonologyWarlock(0x339a000, 0x4877a40)
	/home/runner/work/cata/cata/sim/warlock/demonology/demonology.go:32 +0x14
github.com/wowsims/cata/sim/warlock/demonology.RegisterDemonologyWarlock.func1(0x339a000, 0x4877a40)
	/home/runner/work/cata/cata/sim/warlock/demonology/demonology.go:16 +0x2
github.com/wowsims/cata/sim/core.NewAgent(0x38dfb00, 0x0, 0x4877a40)
	/home/runner/work/cata/cata/sim/core/agent.go:173 +0x24
github.com/wowsims...

**Comment by Tharre** [comment]
Not sure what went wrong there, but not reproduceable and looks like a browser bug/some other issue.
