### ISSUE TITLE
Arms Sim

### ISSUE THREAD

**Issue by Mettalikat** [wowsims/cata#901]
**Describe the bug**
Sim hangs up around 2k iterations.

**Comment by 1337LutZ** [comment]
@Mettalikat Try to disable Multi Cores in the Web sim by opening the options menu ⚙️
![image](https://github.com/user-attachments/assets/c0308699-69ce-4742-b1de-74284c5109e6)

**Comment by Mettalikat** [comment]
Super fast response thank you so much.
Now I'm just getting an eternal loading wheel after disabling multi core
support when trying to sim.

**Comment by Mettalikat** [comment]
I swapped it to 12 cores to reflect my cpu and was able to achieve
2750/3000, bust still hanging up.

**Comment by 1337LutZ** [comment]
@Mettalikat Setting it to `Off` will make it behave like before we added this functionality. If it's not doing anything after turning it Off and refreshing the browser I assume the fault is somewhere else. 🤔

What CPU / Browser version are you using?

**Comment by Mettalikat** [comment]
CPU: Processor 12th Gen Intel(R) Core(TM) i7-12700K, 3600 Mhz, 12 Core(s),
20 Logical Processor(s)
Browser: Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by 1337LutZ** [comment]
@Mettalikat Did turning it to `Off` and refreshing the browser make it work?
