### ISSUE TITLE
Missing firelands patch procs implementations

### ISSUE THREAD

**Issue by zoristaken** [wowsims/cata#902]
## **1. Raid items**

- [x] [Vessel of Acceleration](https://www.wowhead.com/cata/item=68995/vessel-of-acceleration)
- [x] [Vessel of Acceleration Heroic](https://www.wowhead.com/cata/item=69167/vessel-of-acceleration)
- [x] [Matrix Restabilizer](https://www.wowhead.com/cata/item=68994/matrix-restabilizer)
- [x] [Matrix Restabilizer Heroic](https://www.wowhead.com/cata/item=69150/matrix-restabilizer)
- [x] [Variable Pulse Lightning Capacitor](https://www.wowhead.com/cata/item=68925/variable-pulse-lightning-capacitor)
- [x] [Variable Pulse Lightning Capacitor Heroic](https://www.wowhead.com/cata/item=69110/variable-pulse-lightning-capacitor)
- [x] [Jaws of Defeat](https://www.wowhead.com/cata/item=68926/jaws-of-defeat)
- [x] [Jaws of Defeat Heroic](https://www.wowhead.com/cata/item=69111/jaws-of-defeat)
- [x] [The Hungerer](https://www.wowhead.com/cata/item=68927/the-hungerer)
- [x] [The Hungerer Heroic](https://www.wowhead.com/cata/item=69112/the-hungerer)
- [x] [Spidersilk Spindle](https://www.wowhead.com/cata/item=68981/spidersilk-spindle)
- [x] [Spidersilk Spindle Heroic](https://www.wowhead.com/cata/item=69138/spidersilk-spindle)
- [x] [Necromatic Focus](https://www.wowhead.com/cata/item=68982/necromantic-focus)
- [x] [Necromatic Focus Heroic](https://www.wowhead.com/cata/item=69139/necromantic-focus)
- [ ] [Eye of Blazing Power](https://www.wowhead.com/cata/item=68983/eye-of-blazing-power)
- [ ] [Eye of Blazing Power Heroic](https://www.wowhead.com/cata/item=69149/eye-of-blazing-power)
- [x] [Apparatus of Khaz'goroth](https://www.wowhead.com/cata/item=68972/apparatus-of-khazgoroth)
- [x] [Apparatus of Khaz'goroth Heroic](https://www.wowhead.com/cata/item=69113/apparatus-of-khazgoroth)
- [x] [Scales of Life](https://www.wowhead.com/cata/item=68915/scales-of-life)
- [x] [Scales of Life Heroic](https://www.wowhead.com/cata/item=69109/scales-of-life) 

## **2. Avengers of Hyjal and Quest Rewards**
 There seems to be heroic versions of the avengers of hyjal items in the database, but those were not available back in the day, just like the heroic trash loot from tier 11 raids.
- [x] [Stay of Execution](https://www.wowhead.com/cata/item=68996/stay-of-execution)
- [x] [Rune of Zeth](https://www.wowhead.com/cata/item=68998/rune-of-zeth)
- [x] [Fiery Quintessence](https://www.wowhead.com/cata/item=69000/fiery-quintessence)
- [x] [Ancient Petrified Seed](https://www.wowhead.com/cata/item=69001/ancient-petrified-seed)
- [x] [Essence of the Eternal Flame](https://www.wowhead.com/cata/item=69002/essence-of-the-eternal-flame) 
- [x] [Dwyer's Caber](https://www.wowhead.com/cata/item=70141/dwyers-caber)
- [x] [Moonwell Chalice](https://www.wowhead.com/cata/item=70142/moonwell-chalice)
- [x] [Moonwell Phial](https://www.wowhead.com/cata/item=70143/moonwell-phial)
- [x] [Ricket's Magnetic Fireball](https://www.wowhead.com/cata/item=70144/rickets-magnetic-fireball)

## Brewfest
 Do we even bother implementing the tank's brewmaiden on use? [bubblier](https://www.wowhead.com/cata/item=71334/bubblier-brightbrew-charm) and [bitterer](https://www.wowhead.com/cata/item=71333/bitterer-balebrew-charm)
- [x] [Brawler's Trophy](https://www.wowhead.com/cata/item=71338/brawlers-trophy)
- [x] [Coren's Chilled Chromium Coaster](https://www.wowhead.com/cata/item=71335/corens-chilled-chromium-coaster)
- [x] [Mithril Stopwatch](https://www.wowhead.com/cata/item=71337/mithril-stopwatch)
- [x] [Petrified Pickled Egg](https://www.wowhead.com/cata/item=71336/petrified-pickled-egg)

## TBD
The legendary staff will require more thought than any of the other items to implement. There needs to be a discussion if we even bother implementing it following simc and old data for now, or we wait for more information.
- [ ] [Dragonwrath, Tarecgosa's Rest](https://www.wowhead.com/cata/item=71086/dragonwrath-tarecgosas-rest)

**Comment by InDebt** [comment]
Regarding Dragonwrath.
I think it would be a good Idea to open a research ticket where we can collect all info on the staff and people can report issues so it's in one place. After that we should implement a baseline implementation. People will inevitably want to sim the staff and bug us in discord, or will be forced to use other means to sim the staff. I.e, loading the old simc versions and trying to sim it there, potentially drawing the wrong conclusions.

My idea would be to either have a general info box, or only when we select / equip the staff, that the staff's exact interactions are to be verified and should not be trusted deeply.

@1337LutZ What do you think about that and do you have a good Idea how to design a proper UX around that, potentially without any big dev work involved, can we do something like this already?

**Comment by 1337LutZ** [comment]
@InDebt it should be fairly easy to add a persistent warning toast using the equip emitter. This would be non dismissable and will be shown in the sidebar 👍 informing the user about the usage of the staff, and also a link to the issue/thread where they can add findings.

**Comment by Bisonpasfute** [comment]
Regarding Ancient Petrified Seed and probably the others 1 minute CD Trinkets from the Avengers of Hyjal,
Would it be possible to add them to the Cooldowns so we could use them like the others on use trinkets ?
Thank you!

**Comment by zoristaken** [comment]
> Regarding Ancient Petrified Seed and probably the others 1 minute CD Trinkets from the Avengers of Hyjal, Would it be possible to add them to the Cooldowns so we could use them like the others on use trinkets ? Thank you!

This should already be the case, the heroic versions were not available in the game but are still in the database, so if that's the one you are trying to use it won't work because I did not implement unavailable versions

**Comment by hillerstorm** [comment]
Began work on the missing trinkets [here](https://github.com/wowsims/cata/compare/master...hillerstorm:cata:add_missing_trinkets), got Jaws of Defeat and Stay of Execution done, gonna finish the last two (Spidersilk Spindle and Scales of Life) this weekend.

Skipping Eye of Blazing Power for obvious reasons 😅 would require a healing sim!

**Comment by hillerstorm** [comment]
All trinkets should be done now (except the above mentioned Eye of Blazing Power) 🫡

**Comment by zoristaken** [comment]
Im closing the issue, cheers
