### ISSUE TITLE
Fire Mage Sim Failing

### ISSUE THREAD

**Issue by sim-user** [wowsims/cata#910]
**Describe the bug**
When attempting to run a simulation for  fire mage, the engine will process around 2250/3000 iterations and then just hang and eventually a toast message pops up in the bottom corner letting me know something has gone wrong and that I should reload and try again.

**To Reproduce**
1. Cata > Mage > Fire
2. Import gear from addon (_re-downloaded today to ensure I had the latest code_)
3. Click "Simulate"
4. The UI updates to let me know that it is iterating, but at about 75%, it just stops and then after a short time, the error toast appears 

**Expected behavior**
Import gear (_and optionally "Suggest Reforges"_) and simulate with successful results

**Sim Links and Screenshots**
![image](https://github.com/user-attachments/assets/78121cc6-fdb4-4d85-8e00-116416b0b9d3)

**Desktop (please complete the following information):**
 - OS: macOS - Sonoma 14.5
 - Browser: Chrome 
 - Version: Version 127.0.6533.88 (Official Build) (arm64))

**Additional context**
I checked the console and see an OOM error (_see attached log_)
[wowsims.github.io-1722710435183.log](https://github.com/user-attachments/files/16482542/wowsims.github.io-1722710435183.log)

**Comment by 1337LutZ** [comment]
@sim-user You could try disabling multi core and see if that helps:

**My sim stalls part-way through and never completes (web only)**
Try clicking the ⚙️ in the top right then change the number of CPU cores used. If this doesn't work, try turning multiple-core usage off.
