### ISSUE TITLE
Crash Report -1312450110

### ISSUE THREAD

**Issue by volbiathenewb** [wowsims/cata#927]
Link:
https://wowsims.github.io/cata/warlock/demonology/#eJzlVF1oHVUQ3pmz996zE43bk5+uR+jdbH24LG28PwgxlN5N8CGID6EU6WsgbbUolURBfUrUh6hVUiumubQPDYgaLhLypIEWDNpGU+ntj61tIxFtuCkEGhRF0ahn9+yG1Pqo+OC8zOw3M9+cmTNnaQuHAB6HEYCjAO8BzAF8BbAKMIIwhdDdGPr3wHMwFTmEId9oqLB075N9z+8d4Bmby5tAwv6oxpxbrmdVx82lGrtSY5Sxa3WWGwW6xz55jjnLrsd+GYsAsj9W0Ufc0Bb29cvMWcx66Vtjkf8I0N32ReU/0eaBkRsDsu1jdebcyHqm8kfIXXb9feal1adKUhTXFMVh10uPHA2BXCWs+b3K+S3rJUDGPns6Km7Zh9dYBCvs1LkIy9iLN1junfBkU6vMGXb1KRfUKX7N6uy31sJIz+Kp/OZecxTAP4MO0M9g/E9F9PxTTJ1GtzUE8X69iSYhGTMot5dKhaKSUj5fKuSLyi4UFFbMF2fxfv7NPNpX5tG5tITud/OYu7qE+a+XsOP3Cxi8eBF71i7gHJo1bLiGxrd4MqXuqoW4TJPJZz81PYsylNre0Z4fpCZKS1XT2RSDxfYHB9djK8uwEW6mjEwR4+cLMZpXqDAldhqiXW4jT7rUNA02NfJXWt0/ElFbV4GQ7uaiKWMtdsodtFW0kTUduYY/MRPzpQ9TiTkxb4oWsh4+ePCp/c/2DfQLfayVURAtsomsCYg7SjoTO2QnFeQDCYGCEvPHVaTNfgtnwpqJgLnXIUwjLA3GXYmwAR2TORBC103JK2ZsaSUmQb4LdBykehjdIqBtvh9yHlDz4AvogrxvGh0OglcwzFhASRUzcZLtN/KUwEcMXVoNdbfYRW1+VnE0zdw5Oh1WHCTHb729jDKIFZTn7yYudWk9JT38yUMRWajv6LMKSZ9VnVq9bcArh5iM9UbG8Z9Qxlq4cgs1C0GpzxH5+oV/+ZquqXRUs9Vv5mlhzUbO86dSYS2CQhRTV0tBcn3vhCX1sn3QsIz9q/g2DDP9YNzghLaGHgteZYZXxx6wNLAv2KRjdgb3VsZD+az8kEZq5bZ9kVwud31xNpSVcrGKT0/+AC807Op7ot/d3Tewf+8z7h4n4//H/7Xel4N/g3ao/8xG3kc7jh/r+mtMNK2hCatrHPQAr5bjGDP4E/CwLRo=

RNG Seed: 1871982685

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x14a000, 0x1daebc0})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/warlock/demonology.(*DemonologyWarlock).registerSummonFelguard.func1(0x33fe120, 0x38ad400, 0x38ad528)
	/home/runner/work/cata/cata/sim/warlock/demonology/demonology.go:92 +0x6
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFunc.func6(0x33fe120...

**Comment by kayla-glick** [comment]
Bug caused by trying to cast summons without a pet selected in the settings
