### ISSUE TITLE
Feral Druid Rotation

### ISSUE THREAD

**Issue by WilliamTalafuse** [wowsims/cata#928]
**Describe the bug**
I am unable to get the simulator to provide any dps estimate without utilizing the "feral druid optimized rotation" option.  I cannot manually select any rotation options as it gives zero dps.

**To Reproduce**
1. Go to 'Feral druid dps simulator'
2. Click on 'Rotation'
3. Scroll down to 'Optimized Feral Druid Rotation'
4. Remove the rotation
5. Select any and/or all options you can think of
6. Click Simulate
7. See error

**Expected behavior**
I expect to be able to modify the rotation as I see fit and determine the difference between different builds/rotation choices by manual selection.

**Sim Links and Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 127.0.6533.100 (Official Build) (64-bit)

**Additional context**
Boomkin and any other specs/classes all show a dps value regardless of options selected, as long as you select a spell to be cast.  I cannot reproduce this as feral dps.

**Comment by 1337LutZ** [comment]
@WilliamTalafuse can you provide a screenshot? I cannot find the option you are mentioning anywhere
![image](https://github.com/user-attachments/assets/9dea7675-d943-4e62-9499-c42745f58343)

**Comment by 1337LutZ** [comment]
@WilliamTalafuse This is a preset rotation which has a lot of complexity and is therefore not editable.
You can create a custom APL using the inputs yourself if you want to do so. 👍

**Comment by WilliamTalafuse** [comment]
I understand that I am unable to edit the preset rotation. My issue lies in the fact that removing the preset rotation and selecting literally any apl options all fail to provide any dps output whatsoever.

________________________________

**Comment by WilliamTalafuse** [comment]
<img width="1043" alt="wow_sim_cata_feral_druid" src="https://github.com/user-attachments/assets/24adbf10-55ff-4b32-9e46-d8bc1b06bcb8">

**Comment by 1337LutZ** [comment]
Sorry @WilliamTalafuse I misunderstood your issue description 🥲

**Comment by 1337LutZ** [comment]
@WilliamTalafuse I just checked and it works for me. Are you sure you are in a Form though?
![image](https://github.com/user-attachments/assets/88c77191-2d0b-46f1-ba4e-63ae66ecb5b3)
![image](https://github.com/user-attachments/assets/8cd61e2e-5a20-458a-a0cb-6f1ca91c2c1b)

**Comment by WilliamTalafuse** [comment]
It also doesn't matter if I switch to the web version. I get the exact same behavior.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WilliamTalafuse** [comment]
I have only attempted this with mangle. I wanted to see what the difference between mangle and take dps would be, but I can't get mangle to work.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1337LutZ** [comment]
Did you try the other Mangle? There's 2 entries, 1 of them indeed doesn't seem to work.
![image](https://github.com/user-attachments/assets/64932ac8-ccff-4d1c-ad63-285dad2b28de)

**Comment by WilliamTalafuse** [comment]
It doesn't seem to matter which I pick, if I do a prepull to cat form, or if I switch browsers.
________________________________

**Comment by 1337LutZ** [comment]
I am actually able to replicate this on the Web version. It seems to work locally in devmode.

**Comment by WilliamTalafuse** [comment]
I appreciate your follow through. I will attempt to figure out how to install dev mode and see if I can get it to work, though my experience is limited in that area.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1337LutZ** [comment]
No worries, but this is for sure a bug that we need to fix 👍

**Comment by 1337LutZ** [comment]
@WilliamTalafuse I figured it out.
Distance to target for Feral is 25 because it always assumes you charge on pull. When making your own APL you should probably add that it should charge, or reduce the distance.

**Comment by WilliamTalafuse** [comment]
Thank you!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
