### ISSUE TITLE
Won't finish SIM

### ISSUE THREAD

**Issue by Caldorwow** [wowsims/cata#929]
SIM freezes before it finishes.
I downloaded the local SIM to see if the batch would actually be faster. Now I can't SIM my characters even after deleting it. Is there a way to fix this mess?

**To Reproduce**
1. Run SIM

**Sim Links and Screenshots**
![image](https://github.com/user-attachments/assets/eb600422-9c48-447d-94b5-2ee163b415d7)

**Comment by FelixPflaum** [comment]
Are there any errors shown in the terminal that opens when you start the exe? If not, can you check if there's any errors in the browser console when it gets stuck? (shift+ctrl+K for Firefox, shift+ctrl+J for Chrome)

**Comment by 1337LutZ** [comment]
Extra ping @Caldorwow
