### ISSUE TITLE
Make combined spell metrics aggregation configurable

### ISSUE THREAD

**Issue by InDebt** [wowsims/cata#93]
**Is your feature request related to a problem? Please describe.**
Right now aggregated spell metrics in the damage overview show incorrect DPC (Average Damage) values. For some spells this might be requried, for other's where proc's or other effects happen by pressing one button i.E.  (Improved Devouring Plague)[https://www.wowhead.com/cata/spell=63626/improved-devouring-plague] Even though the instant damage needs explicit cast metrics, the average damage of devouring plague should not be reduced by those procs.

**Describe the solution you'd like**
Having an option within the Aura/Spell to define how the metrics for this spell are aggregated would be lovely. So each dot / spell can chose how the aggregation should happen.

**Additional context**
[Shadow Sim.](https://wowsims.github.io/cata/priest/shadow/#) - you can go there and run a sim, then view the Result Tab and see the damage break down of Devouring plague.

**Comment by 1337LutZ** [comment]
@InDebt As discussed; I believe when refactoring the Metrics table and adding Passive flags + have Dots not be a Hit but a Tick this issue was mostly tackled.
The only point where this is an issue with Pets and how those metrics are displayed.
