### ISSUE TITLE
Crash Report -1067829048

### ISSUE THREAD

**Issue by Holiness69** [wowsims/cata#933]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzlUk9IFFEYn++9cd0dC1+L1GTCPgcP24IxO1tgXXZWLxtUWAbZcXBHHRp3N52QPK1Ssdllq4OuJFYQdSgQOlkREuEfcmPzsFBESih6CJQ8lLhRs7OrhGiHqC795vC+P7/f9733fcPtk6EVohAH6Ad4ADABsAiQQDCMoJatARmcTPnzogFsq9eVi2q73UFw+QfgnGQkjfklKjgeJtn5NM6kMVdM0gvYfQ+4HSSTwfwiFfBSH+Y48mYM8zepO5GTPfuG+StUsJmZa/04F9tJHpvsVZcAjPs6cISMmJQ5l8CaeSZXrpT0ZrFgW95QlJKnJiVBrdiq2aKUPMpiPusScl5OUkziawVjaszSFJPBbMGYmcPu+2Dea3gZ8900T3tvPmfNxbFkYYgVHPYicU8jmwDwjCMeuK/AbIXZy6PWGWsY3TLP1G2KBzb50ja6dXi2yS/7f637XVTI1iEPbfR1Bv9U7SNMLYrCALAc4pgnqEIUfdWST/T5REnyeiXRK5mfT/J5q0XfC1RlX0kh8iWF+O8pRD+nkLvnNRKzKVQzM43kV9MoODeNJhCbRiXvEPMRmVtaRKFunO91UL5TsM7KvZgR+mxBcFh+rFnelc+UyXsHkjlM+g/nI2l/ZbOFjD+Qmsrhk1+6jaPzL1FXyXGlpU3ppNIhGqSNPHi2+SX+FeovyX+jbCw0/nPdYzWDtwKbOda0YncdgSTkB/jWX+Cw8g04bwdn2dG2qKKr9JSqNBlaJExPa22q50Qw0kn1SLiFdmq6To1Wk6BoIWoo51RqRGhBFFSVENXCtEFtioRDHQeoO9BsqO0WXwtrhqbo1Ct27K/M96ySpREUvdqDu3bX6kqXZpavi4Q7jPYLTUZ+W2f+l20xcc/JrbfFxFfkZGEEs+vbYmQRfgANCt/e

RNG Seed: 1000163433

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x14a000, 0x1daebc0})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Dot).periodicTick(0x3983490, 0x30a8480)
	/home/runner/work/cata/cata/sim/core/dot.go:224 +0x26
github.com/wowsims/cata/sim/core.(*Simulation).Step(0x30a8480)
	/home/runner/work/cata/cata/sim/core/sim.go:524 +0x25
github.com/wowsims/cata/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/cata/cata/sim/core/sim.go:481
github.com/wowsims/cata/sim/core.(*Simulation).runOnce(0x30a8480)
	/home/runner/work/cata/cata/sim/core/sim.go:368 +0x7
github.com/wowsims/cata/sim/core.(*Simulation).run(0x30a8480)
	/home/runner/work/cata/...

**Comment by hillerstorm** [comment]
Must've been fixed, running this with the RNG seed supplied runs fine
