### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by JonySilver** [wowsims/cata#936]
Links to [Cataclysm Wowhead](https://wowhead.com/cata/items "https://wowhead.com/cata/items") for each item:
https://www.wowhead.com/tbc/item=22559/formula-enchant-weapon-mongoose

**Comment by 1337LutZ** [comment]
Is there any relevant use case for Mongoose in Cata?

**Comment by 1337LutZ** [comment]
Closing this issue due to no reaction.
