### ISSUE TITLE
[Item] Dragonwrath, Tarecgosa's Rest

### ISSUE THREAD

**Issue by InDebt** [wowsims/cata#946]
> [!IMPORTANT]
> With the approach of the next phase, the desire to accuratley simulate and gauge `Dragonwrath, Tarecgosa's Rest` will be higher and higher. This Staff is the newest legendary introduced with the Firelands raid and will be in high demand for every caster. Therefore, it's very desirebly to provide a high quality implementation for this item, as it has many class specific interactions. This issue shall be used to gather all information we can, as it's unlikely the staff will be available for testing on the upcoming PTR. Please contribute any old resources and references you have. Take the results of the simulations with the staff with bit of scepticism until we have larger testing and reference datasets.

> [!NOTE]
> This issue will be constantly updated with the latest references and feedback gathered

## General behaviour
* When equiped the staff provides the ability to duplicate the casters damaging spells.
* Direct damaging spells will be replicated as a direct copy of that same spell
* Periodic damaging ticks will be replicated causing the exact same amount of damage as arcane damage through [Wrath of Tarecgosa](https://www.wowhead.com/cata/spell=101085/wrath-of-tarecgosa) [^1]
  * As it's another spell, players will not benefit from talents here. A good exaple would be `Shadow Orbs` which can trigger from `Shadow Word: Pain` ticks. These will not be triggered by a tick replication from the staff.
* The replicated spells from direct casts behave the same way a cast would that player's cast themselves. i.E. consuming procs and benefitting from the same modifiers. [^1]
* Spells are replicated on damage. Causing spells with projectiles to be replicated on impact [^4]
* Even though it is stated that the Staff has an internal cooldown, it seems to be around the 10ms visible through wowhead. [^13]
  * Procs occuring immediatly after another can be seen here [^12] 56s

## Class specifics
* There seem to be different proc chances for different classes as indicated by blizzard.
> Furthermore, the proc chance is adjusted favorably for pet specs that derive a significant portion of their DPS from pets.
[^2]

### Proc Chances per Spec
| Class | Spec | Proc Chance | Reference |
| ----- | ----- | :-----------: | ---------- |
| Druid | Balance | 8% | [^3] [^10] [^19] |
| Mage | Arcane | 9.16% | simc (4.3) |
| Mage | Fire | 8.0% | [^16] |
| Mage | Frost | 9.16% | simc (4.3) |
| Priest | Discipline | ? | - |
| Priest | Shadow | 9% | [^17] |
| Shaman | Elemental | 10.8% | PTR - Sheet missing |
| Warlock | Affliction | ~10.5% | [^18] |
| Warlock | Demonology | ~12.6% | [^18] |
| Warlock | Destruction | ~11.6% | [^18] |

#### Shaman
* [Fulmination](https://www.wowhead.com/cata/spell=88766/fulmination) Will be replecated based on the initial casts damage calculations for Lightning Shield. [^5] (56 seconds)
* **Flame Shock** initial can be replicated, the dot duration is not affected.
* [x] Can overload procs be replicated
  * Yes. Overload procs can be replicated [^11]
* Replicated spells do not proc overload 
* [x] Can lightning shield procs be replicated

#### Mages
* Flame Strike replicates the ticks as DoT ticks [^1]
  * Whole spell can be replicated. A second Flamestrike on the ground will not be placed.
* Bast Wave will be replicated as another Blast Wave [^1]
* If talented into `Improved Flame Strike` a replicated Baste Wave will cast another Flame Strike [^1]. There will be no 3rd Flamestrike.
* Procs on Arcane Blast will also apply a debuf stack [^1]
* [x] Can Flame Orb / Frost Orb procs be replicated? We have conflicting statements
  * [x] Flame Orb and Frost Orb are not replicated [^1]
  * Flame Orb and Frost Orb are replicated as direct spells [^16]
* Pyro Cast and Dot Ticks are replicated [^15] 2m05
* Final explosion of Living Bomb can be replicated

#### Shadow
* Mind Sear replicates each tick as a cast [^6] 6m8s. Proc chance per target and way lower than single target spells.
* MS and MB are replicated. In OG cata the replication spell was severly delayed after the initial hit. This allowed for orbs being procced again and the proc can consume those orbs [^6] 1m21s
* We will have to see how large the delay of the procced spell will be on current version of wow
  * [x] Delay is practically 0
* SW:D will replicate and deal the damage feedback twice as well [^8] 03m30s
* [x] IMP:DP can not be replicated

#### Warlock
* Hellfire is treated as a DoT similar to Flame Strike [^9]
* [ ] How does Conflagrate interact with DTR? Is the initial damage used when calculating the immolate damage? As the proc might trigger when Immolate is not active on the target.
* [x] Havoc does not replicate duplicated spells 

#### Balance
* [x] MF
  * MF initial can be replicated. The second damage event will not refresh the dot duration
  * Lunar Shower does not proc off the replicated damage tick
  * Clear casting can proc from the replicated damage
* Starfire
  * Replicated starfires do interact with the Starfire Glyph
* Hurricane ticks are replicated fully. Proc rate is based per target. Reported right now ~1%.
* Mushrooms are replicated fully and also have a lower proc chance than single target spells
* If a spell that takes you of eclipse procs DTR, the copied spells gain eclipse bonus

## Open topics
In general the following information would be nice to gather additionaly:
- [x] Are there any spells that should not be replicated but would be expected to be based the outlined behaviour
  - Warlock's Immolation Aura does not seem to be replicated
- [x] Should spells and procs from enchants, trinket or other items be replicated
  - Anything that is a proc (Overload seems to be an exception) is not replicated
- [x] Should procs be replicated (i.E. can an elemental shaman's overloaded spell be replicated)
  - No procs are replicated, except their flagged with "Not a proc"

## Implementation
- [x] Sufficient research and resources gathered
- [x] Task to implement a baseline staff implementation, see #989
- [x] Make disclaimer available in the UI
- [x] Finish implementation

Please provide any information you have, that is based on reliable evidence like videos, old combat log snippets, class forums or old elitist jerks threats. Private server information or memory can not be used here.

### References
[^1]: https://www.wowhead.com/cata/item=71086/dragonwrath-tarecgosas-rest#comments:id=1492763
[^2]: https://web.archive.org/web/20110623014842/http://us.battle.net/wow/en/forum/topic/2674988056?page=1#15
[^3]: https://web.archive.org/web/20120620030834/http://elitistjerks.com/f73/t114017-balance_wrathcalcs/p14/#post2041883
[^4]: https://web.archive.org/web/20120126094819/http://elitistjerks.com/f80/t125554-dragonwrath_tarecgosas_rest_warlock_specific_analysis/p4
[^5]: https://youtu.be/OkWBIBpf1xw?si=y-iY1y162m9FKo4h
[^6]: https://www.youtube.com/watch?v=TJLDHQL47AU
[^7]: https://web.archive.org/web/20120125062754/http://elitistjerks.com/f80/t125554-dragonwrath_tarecgosas_rest_warlock_specific_analysis/p3/
[^8]: https://www.youtube.com/watch?v=ErzB9phDrMU
[^9]: https://web.archive.org/web/20120124053831/http://elitistjerks.com/f80/t125554-dragonwrath_tarecgosas_rest_warlock_specific_analysis/
[^10]: https://www.youtube.com/watch?v=TNpCovslvtI
[^11]: https://www.wowhead.com/cata/item=71086/dragonwrath-tarecgosas-rest#comments:id=1570599
[^12]: https://www.youtube.com/watch?v=fnoKFCLHkYw&t=55s
[^13]: https://www.wowhead.com/cata/item=71086/dragonwrath-tarecgosas-rest#comments:id=1450301
[^14]: https://www.dual-boxing.com/threads/45109-Dragonwrath-(legendary-staff)-and-elemental-shaman?s=713730a586409e4fb0200593a6afbc4c&p=342528&viewfull=1#post342528
[^15]: https://www.youtube.com/watch?v=5Of2uN0baDQ
[^16]: https://web.archive.org/web/20120208065305/http://elitistjerks.com/f75/t110187-cataclysm_mage_simulators_formulators/p16/
[^17]: https://docs.google.com/spreadsheets/d/e/2PACX-1vSzCde3Y9Cx4D_tFS3IhT4Iu0z6H1jfz_zE4L9pSmIHZ7pTYYlZtTQ9KgWJycCZ2ZcD9CayIQ0BLKgT/pubhtml
[^18]: https://docs.google.com/spreadsheets/d/12jnHZgMAYDTBmkeFjApaHL5yiiDlxXHYDbTXy2QCEBA/edit?gid=707775684#gid=707775684
[^19]: https://docs.google.com/spreadsheets/d/e/2PACX-1vTaCACFb7dqXpF2qwAZIAgXX-p2VTuJWqmyWXqaJ3c49FNWm61E9-unEdN3cn7YHevoGWWPmqkqJv6h/pubhtml

**Comment by 1337LutZ** [comment]
@InDebt Found some old posts for Mage:
Staff + Ignite: https://web.archive.org/web/20120225125845/http://elitistjerks.com/f75/t110187-cataclysm_mage_simulators_formulators/p18/#post2087545 
Staff + Combust/LB: https://web.archive.org/web/20120208065305/http://elitistjerks.com/f75/t110187-cataclysm_mage_simulators_formulators/p16/#post2010872

**Comment by stn-ms** [comment]
Some more info on Balance:

- https://web.archive.org/web/20111230201811/http://www.owlkin.org/moonkin-guides/balance-druids-dragonwrath/

**Comment by 1337LutZ** [comment]
Weak evidence, but good to test;
VPLC trinket being replicated

https://web.archive.org/web/20120809013459/http://elitistjerks.com/f80/t125554-dragonwrath_tarecgosas_rest_warlock_specific_analysis/p3/

**Comment by InDebt** [comment]
> Weak evidence, but good to test; VPLC trinket being replicated
> 
> https://web.archive.org/web/20120809013459/http://elitistjerks.com/f80/t125554-dragonwrath_tarecgosas_rest_warlock_specific_analysis/p3/

Yeah - the video reference I posted for Balance PTR Proc rate testing also mentioned it. For now I have implmented it that way but I have not found any video evidence yet.

**Comment by Polynomix** [comment]
Elemental ptr testing : https://github.com/wowsims/cata/issues/1114

**Comment by stn-ms** [comment]
According to our weekend PTR testing, Moonfire / Sunfire impact spells are indeed duplicated - I'll mark that as done.

**Comment by InDebt** [comment]
Yes I can confirm they're replicated. The following interactions for them are noteworthy though.

* Lunar Shower is not procced from the replicated MF
* Clear Casting can proc from the replicated spell
* The replicated spell does not affect the dot duration / pandemic

**Comment by ssabbyccatt** [comment]
We have over 10k 3-shroom-explosions to make up the data. The fact that you got a lower proc chance is only because you only did 446 tests. When we were at only 446 tests, our proc chance was significantly different from what is recorded. That's why we did 10k+ tests per spell, to arrive at a number that is supported by data.

**Comment by Polynomix** [comment]
> Therefore my hypothisis woudl be that AoE abilities have a reduced proc rate and proc per damage event.
I think it really depends on the ability. Shaman's Thunderstorm procs per cast on every target hit for example.

**Comment by InDebt** [comment]
> We have over 10k 3-shroom-explosions to make up the data. The fact that you got a lower proc chance is only because you only did 446 tests. When we were at only 446 tests, our proc chance was significantly different from what is recorded. That's why we did 10k+ tests per spell, to arrive at a number that is supported by data. The methodology is explained in the sheet; if you're trying to discern single shroom proc chance it is obviously not 8% because that's on a full 3-shroom explosion. Once we have finished analyzing our data, we will provide the proc % chance for a single shroom.

First of all, thanks for the feedback. I've noticed that my sample on WCL is useless as I did not keep myself infight. Thus kinda screwing proper log parsing on WCL. I've manually parsed the combat log in google sheets now and got 7 procs on 600 casts for a single shroom.

Really appreciate the effort by the way that went into collecting all that data. Would be nice if the data can support either a proc chance per shroom or a proc chance per target and shroom. For Mind Sear for example the current data we have suggests that the proc rate significantly increases with the amount of targets hit per tick.

**Comment by ssabbyccatt** [comment]
> > We have over 10k 3-shroom-explosions to make up the data. The fact that you got a lower proc chance is only because you only did 446 tests. When we were at only 446 tests, our proc chance was significantly different from what is recorded. That's why we did 10k+ tests per spell, to arrive at a number that is supported by data. The methodology is explained in the sheet; if you're trying to discern single shroom proc chance it is obviously not 8% because that's on a full 3-shroom explosion. Once we have finished analyzing our data, we will provide the proc % chance for a single shroom.
> 
> First of all, thanks for the feedback. I've noticed that my sample on WCL is useless as I did not keep myself infight. Thus kinda screwing proper log parsing on WCL. I've manually parsed the combat log in google sheets now and got 7 procs on 600 casts for a single shroom.
> 
> Really appreciate the effort by the way that went into collecting all that data. Would be nice if the data can support either a proc chance per shroom or a proc chance per target and shroom. For Mind Sear for example the current data we have suggests that the proc rate significantly increases with the amount of targets hit per tick.

We should be able to get proc rate per shroom data once we've had a chance to fully go through it. Should have that done later this week; our other TC is unavailable until Thursday iirc. Proc per target won't really matter for Shrooms, they actually fully dupe the entire shroom, functioning as if you just have a 4th/5th/6th mushroom up (relatedly, we have also confirmed no ICD at least for shrooms, we have at least 2 logs with 2 shroom explosion dupes within 0.001s of each other).

**Comment by stn-ms** [comment]
> Yes I can confirm they're replicated. The following interactions for them are noteworthy though.
> 
> * Lunar Shower is not procced from the replicated MF
> * Clear Casting can proc from the replicated spell
> * The replicated spell does not affect the dot duration / pandemic
> * VPLC can procc off the replicated spell

We tested Glyph of Starfire, duplicated Starfires do extend Moonfire/Sunfire, when there are 'extensions' left.
