### ISSUE TITLE
Crash Report -34239793

### ISSUE THREAD

**Issue by chikywan** [wowsims/cata#961]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzdUj1IHEEU3vfe3t3eEHByKExsdjMQOARhd89CbXa1srQ0nQEjKVJIOru1U4v8VPcDFhaikCBCmhAIhBDUgBs2xlwkBBISA1cIQiTo6Ukyu5suARtR8Ku+n5lv3oNhNwzg4MMdmIBpgArAEsBLgG2ABkCAMI2wgjCox4cKWuf3TI2yw3dvTd6+Z2Q4dW4Ba+Pv35LMPqnqDypUXACW44dRQtp4vU6iYUmaV0kFGOPvVkkEVrEMrMC3VPjFlFkVNssUe4w/VV7TlKAxzj8qvmPKuFYrPgR2hc+21ENKqhuq/IPK71uJsVcmFf9aJ9EyJSmD5fmjE5JJkOMbqxQX6PwoiuVcK5E53nxGYspS5HNE4thU5LWafBGkYWTsjmF9RO/6ioLYNmiXFIXgwlfr1wZxAmqgM2Tac/Rsu2T/g2635JZKtus6jms7rmM7Sjvd/zn6CoVxECLfD1H8DtH6GWLvzib6j3/gOuYizH9C7RuigAaOTVE6Qo8//5fd9GdJk8s4RPlEB+P+1TRp96/VqjHeeH2pE3nXxxPUvYFwI8au5+6DNSIyXef0Y4oz/lnWBWNrp/aly7/Y8wdSfeiNwh9lAY6i

RNG Seed: 2877000340

Iterations can't be 0 or negative!

**Comment by 1337LutZ** [comment]
@chikywan The shared link works fine here.
Could you try disabling Multi core Sim in the options @ the ⚙️in the top right?
You can do this by putting it on **Off**
![image](https://github.com/user-attachments/assets/67fbca3f-ee64-447d-9851-bf8818a5500d)
