### ISSUE TITLE
Demo Warlock Sim Returns error and has no functionality 

### ISSUE THREAD

**Issue by Calyus** [wowsims/cata#966]
**Describe the bug**
Using the Local Sim there is no functionality with only Demo Warlock and returns an error "Something went wrong running your raid sim. Reload the page and try again."

**To Reproduce**
1. Go to Warlock
2. Click on Demonology
3. ~~Scroll down to '....'~~

**Expected behavior**

**Sim Links and Screenshots**
http://localhost:3333/cata/warlock/demonology/#
![Untitled](https://github.com/user-attachments/assets/d3c7f621-a792-42fc-94e4-7e3bc6022162)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 129.0.2

**Additional context**
It worked as expected prior to installing .64 last night saw .65 today and I have the same issue. It is only the Demo Warlock Sim that has this issue.

**Comment by InDebt** [comment]
Hey @Calyus. We've tested the features introduced in .64 thoroughly but it seems some stuff still got through.

> [!warning]
> **This will reset all settings and delete all saved item sets**
> * Usually a quick "fix" for this would be clicking on the `Cogwheel` in the upper right and `Restore Defaults`.

If the item sets and other settings are important and you want to keep those, you could try to Press `F12` and open the developer console. Within it you can select the `Console` tab and share a screenshot of anything that would pop up red after a page refresh.

**Comment by Calyus** [comment]
The issue remains even after Restoring Defaults as well I have relaunched the local sim after clicking restore defaults and the issue remains. While it claims to have done it, it does not actually remove any of Item Sets. I understand that it is expected to of removed them but something is preventing it from doing so it would seem.

**Comment by InDebt** [comment]
Hm... this is indeed odd.
Could you provide a sreenshot of any errors that might be displayed in the developr console of the browser?

`F12` -> `Console` -> `Page refresh` and then screenshot anything red.

@1337LutZ Do you have any idea why even the `Restore Default` would not work here. It seems local storage is not changed at all.

**Comment by 1337LutZ** [comment]
Restoring defaults actually doesn't remove item sets.
@Calyus when you open the localhost URL in a private browsing window, does it then work?

**Comment by Calyus** [comment]
> Hm... this is indeed odd.
Could you provide a sreenshot of any errors that might be displayed in the developr console of the browser?
F12 -> Console -> Page refresh and then screenshot anything red.


Here is the errors displayed in the console
![Error 1](https://github.com/user-attachments/assets/7bb6bc38-1ada-49f4-a2c3-991ae7117f12)
![Error 2](https://github.com/user-attachments/assets/f3533b13-edef-433d-8652-bcbb61734f8b)


> Restoring defaults actually doesn't remove item sets. @Calyus when you open the localhost URL in a private browsing window, does it then work?

It does indeed work in private browser.  

Side note: I updated to .66 today and the issue remains with only the Demo Warlock sim.

**Comment by 1337LutZ** [comment]
@Calyus In your broken environment, could you please try the following and send it to us?
- In the Chrome Devtools open the **Application** tab 
- Go to **Local Storage**
- Go to **localhost:3333** 
- Search for Demonology
- Double click the **Value** input
- Copy and share the contents
![image](https://github.com/user-attachments/assets/07d1a706-830c-4b3d-99d0-eb54c4580e28)

**Comment by Calyus** [comment]
The code seems to end abruptly but I triple checked, it's definitely all that is listed there. 

`{"settings":{"iterations":3000,"phase":2,"showDamageMetrics":true,"showEpValues":true,"useSoftCapBreakpoints":true,"language":"en","faction":"Alliance","filters":{"armorTypes":["ArmorTypeCloth"],"sources":["SourceRaidH","SourceRaidRF"],"minIlvl":359,"maxIlvl":379,"oneHandedWeapons":true,"twoHandedWeapons":true,"favoriteGems":[52205]}},"raidBuffs":{"markOfTheWild":true,"blessingOfKings":true,"powerWordFortitude":true,"strengthOfEarthTotem":true,"trueshotAura":true,"blessingOfMight":true,"icyTalons":true,"arcaneBrilliance":true,"demonicPact":true,"moonkinForm":true,"wrathOfAirTotem":true,"communion":true,"leaderOfThePack":true,"bloodlust":true},"debuffs":{"ebonPlaguebringer":true,"bloodFrenzy":true,"mangle":true,"sunderArmor":true,"demoralizingShout":true,"frostFever":true},"partyBuffs":{},"player":{"name":"Player","race":"RaceOrc","class":"ClassWarlock","equipment":{"items":[{"id":60237,"enchant":4207,"gems":[68780,52217],"reforging":144},{"id":59512,"reforging":165},{"id":65263,"enchan`

**Comment by 1337LutZ** [comment]
> The code seems to end abruptly but I triple checked, it's definitely all that is listed there.
> 
> `{"settings":{"iterations":3000,"phase":2,"showDamageMetrics":true,"showEpValues":true,"useSoftCapBreakpoints":true,"language":"en","faction":"Alliance","filters":{"armorTypes":["ArmorTypeCloth"],"sources":["SourceRaidH","SourceRaidRF"],"minIlvl":359,"maxIlvl":379,"oneHandedWeapons":true,"twoHandedWeapons":true,"favoriteGems":[52205]}},"raidBuffs":{"markOfTheWild":true,"blessingOfKings":true,"powerWordFortitude":true,"strengthOfEarthTotem":true,"trueshotAura":true,"blessingOfMight":true,"icyTalons":true,"arcaneBrilliance":true,"demonicPact":true,"moonkinForm":true,"wrathOfAirTotem":true,"communion":true,"leaderOfThePack":true,"bloodlust":true},"debuffs":{"ebonPlaguebringer":true,"bloodFrenzy":true,"mangle":true,"sunderArmor":true,"demoralizingShout":true,"frostFever":true},"partyBuffs":{},"player":{"name":"Player","race":"RaceOrc","class":"ClassWarlock","equipment":{"items":[{"id":60237,"enchant":4207,"gems":[68780,52217],"reforging":144},{"id":59512,"reforging":165},{"id":65263,"enchan`

Then I'm pretty sure that's why your Sim is broken. You can remove this entry from the LocalStorage, your gearsets should be saved in another entry called `savedGear`

**Comment by Calyus** [comment]
Deleting the variable and refreshing has solved the issue, Thank you very much.

**Comment by 1337LutZ** [comment]
It's very odd that your storage has been corrupted this way. It looks like either memory corruption, or something was writing to the store and then the website was closed/refreshed.
