### ISSUE TITLE
[UI][ENHANCEMENT] Highlight changed reforges after applying "Suggest Reforges" 

### ISSUE THREAD

**Issue by Lawdie** [wowsims/cata#967]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When you press "Suggest Reforges" but already have gear with reforges, highlight items that have their reforges changed in a different colour text or with a border. 

This makes it easier to update reforges after a gear slot upgrade instead of having to check every slot again. 

**Describe alternatives you've considered**
N/A

**Additional context**
Scuffed example
![image](https://github.com/user-attachments/assets/3103e2ba-fdba-4749-b2b9-7591532a4f8d)

**Comment by 1337LutZ** [comment]
@Lawdie We already have discussed this topic.
Our idea is; Add a link in the "Reforging done" Toast (bottom right) that will open a Modal/Popup showing what the changes per slot were.

**Comment by Lawdie** [comment]
> @Lawdie We already have discussed this topic. Our idea is; Add a link in the "Reforging done" Toast (bottom right) that will open a Modal/Popup showing what the changes per slot were.

Sounds fine with me, just anything to make it more obvious what got changed!

**Comment by hillerstorm** [comment]
> > @Lawdie We already have discussed this topic. Our idea is; Add a link in the "Reforging done" Toast (bottom right) that will open a Modal/Popup showing what the changes per slot were.
> 
> Sounds fine with me, just anything to make it more obvious what got changed!

In the meantime, ReforgeLite actually has an import feature that accepts the json from wowsims `Export -> JSON`. This way you can reforge in the sim -> export from the sim -> open ReforgeLite -> press `Import WoWSims` and paste the JSON -> press `Show` and go to reforge npc 😃

**Comment by hillerstorm** [comment]
Fixed in #1061
