### ISSUE TITLE
Crash Report 346860096

### ISSUE THREAD

**Issue by SergeyKulikoff** [wowsims/cata#973]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzdUU0oRFEUfueeOzxPmmuiHhvPK/VS6jE2bN4zK8tZsqOQhYXs7MaG8VOImjE7RSyQrb+S1IyixkZSIixmQSM2fsbPee9ZyMZGlG91zne+7zv3dJUqGQTY0A29EAWIAywCbAMcA2QAIgyiDFYZhLgjCkjlSV8C88I97f2dfXKBwPIhpgTEwRGqWU3PW5rhjzE0YkDc0yw3317fPIAxCYpfbL2gmtF0zJIo7hApMk4RMR5HY95xbZJikJJI4SRNgFIk7nKojmk6SI5EiDWSjGo6v42hy/jFSA5dR9Zz+MUGSSYohWKJI2KZIqIfi909p6/45XX54jLnDrk4zCG1Z1duWyrmpj9fog5onvyGMp8rqNhNo7EAuiz7zNIwb+HV50xF5Rikf4pA5M9Pa5RCrBcSwBWmSOtMrqkLmmbQrN1hUorxNCs8YdIFYypkWMcAep56e/ajarVHUNJXWDMWuH2kyy72JiV2WWLGwZ7V4DFpq7LLxZHVdLDv4NqquwetRfVV/9IXG8P2T8ZFOpLf5nnHb2XtJq9/sNrgHYaQmpY=

RNG Seed: 4279937697

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:57 +0x10
panic({0x14cc40, 0x1df0ee0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/mage.(*Mage).applyImpact.func1(0x381a340, 0x33f6b40)
	/home/runner/work/cata/cata/sim/mage/talents_fire.go:403 +0xd
github.com/wowsims/cata/sim/core.(*Aura).init(...)
	/home/runner/work/cata/cata/sim/core/aura.go:118
github.com/wowsims/cata/sim/core.(*Aura).reset(0x381a340, 0x33f6b40)
	/home/runner/work/cata/cata/sim/core/aura.go:123 +0xa
github.com/wowsims/cata/sim/core.(*auraTracker).reset(0x33b4488, 0x33f6b40)
	/home/runner/work/cata/cata/sim/core/aura.go:496 +0xb
github.com/wowsims/cata/sim/core.(*Unit).reset(0x33b4000, 0x33f6b40, {0x426ba8, 0x30310b8})
	/home/runner/work/cata/cata/sim/core/unit.go:549 +0x40
github.com/wowsims/cata/sim/core.(*Character).reset(0x33b4000, 0x33f6b40, {0x426ba8, 0x30310b8})
	/home/runner/work/cata/cata/sim/core/character.go:495 +0x4
github.com/wowsims/cata/sim/core.(*Party).reset(0x32d4d80, 0x33f6b40)
	/home/runner/work/cata/cata/sim/core/raid.go:76 +0x8
github.com/wowsims/cata/s...

**Comment by InDebt** [comment]
Thanks for the report.
The issue is caused by some sim code that actually expect some talents to be picked and intialized in the backend. Looking at your talents you've only spent 9 points. If you click abort and use the default talents it shoudl worke for now.

We'll take a look to make the code more robust and not fail if certain talents are not picked.
