### ISSUE TITLE
Crash Report -535796283

### ISSUE THREAD

**Issue by MarkShulhin** [wowsims/cata#992]
Link:
https://wowsims.github.io/cata/warlock/demonology/#eJzdVV1oHFUUnnPuzO7sibSTm6Sd3ILdDhXi0GxnJqaxqXU3FST60voiQRGsxCpFacnaB98SRY3Wh1RRk4UKKQgFayjxRQS1BKuVtNBEaauJJEZDI2lMqSBCm+CdmTvbTVsRRXzwsDDf/c7/uWdm6Q4TLCjA07AfegH6AY4CnAC4ADAH0I3Qi3AcYccqC9qhQxodj3RcEy+tKrHUrmd2P/9kl2lYppgE4taZc8xezDqpYwP6wX7W0AeUtmYuRuA2a3GJ2XNZhy2+w+TplDR9U54W5Ilbv0jdy9JR6pQjWVeuMXtwgwMaWda81H+/3gmjaqF2tTW9zJyUPIbm74XEgjQ5JEPIgHGGD6R/r8qXtnqvRnZp6/QXqrCpnxRz+JrKeEh69GRjckHiq+spZR2V2qJTZRpe3S69Q+8DcKfRZnQBtP+p8O5/2Nrl/K2ff19atR3G/nDT3sAU6YSm8TG2ejdJY1OTF0hp8j35C/wg8H3JBV6w0m4EN5rTo2idH0X7m1nMfjuLDedn0ftxFO9eHsfCC19j+9I4nkL9LFZ9h9oM9po2UC2ZQqY3R+bBMUmiRt8rUp1if57SnQylyWi8K1dBj5xcQddSWhjEzA+NSraGUkK2ZVcrMsg1X4/QP84q6STCkHErdhIV6+VailwX2Krxx8SjlOObKDMMYbyez/UEHhktw3fHjAS++JHB76RM5759zz51YHdXJ4/rGHwFFVruMRS61Af8IbGTkGv8ATKeONBVfI6X58HLI+BJ17zck6ImEt0kKnAMuC8200buEM1gWkWlTAlU2ATKIG6i5nWiJqlf8mESa/4k49vFNgq4RzVutalzfEQT0Xi2tMg1oHp3rSTpSjmJkICYvNV4wlX8HtFKHs9FlqmbLbf4Rap2V5sGl3NWlHROZhQm9/lmEq59g3e0Pn7w5+7hsO8TbdTCm2mdW39DmZkSqkWkNW6tVGbGEyKsnMBPFpW3iGba5Lom45m90l+OOQti3TDaJnCzhPHkBZX0slJdhiOytNatk47pvfG1CLOkK6TuKRr6kWjoPwzpQj0r72LsUyOiL07pldYDv6FQT94u7qftfNuKZBN6kmxCp6x7eziiBzWxZhhrpE1ZFTcbJItEIt6uwwcZrxU8qeGt10G9MZWVLb0fF1yag0rjzxZYZDzm84xI3rTrsGoOOy/j29DD4i/T1sJgjLofLrzGNGcI21kmJvYUqmObewv1pYFQvspvjZmz+Q17IjmXbztzOpRL+eBXyHbYhvsf/ZE0vFr4N8N1d375l/Hi5j9ZLLTF59/zj8Mfr7VHtg==

RNG Seed: 3506684007

When validating reforging for item 65376, the reforging could not be validated. 165
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:57 +0x10
panic({0x1149c0, 0x33609c0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0xff60, 0x0, 0x0, {0x300db08, 0x2, 0x2}, 0xa5})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x2d
github.com/wowsims/cata...

**Comment by Tharre** [comment]
The error message is confusing, but you need to select a random suffix for the belt, then it'll work.
